### PR TITLE
Disable nullability in migrations (RC1)

### LINKED ISSUE #25624: Disable reference nullability in migrations and model snapshot
Our generated migrations and model snapshot don't contain NRT code, so in some scenarios they don't compile if nullability has been enabled at the project level. Add `#nullable disable` in generated files to temporarily work around this issue. #18950 tracks generating proper NRT code in the future.

### PR DESCRIPTION
**Pull request by roji**
Closes #25624

Merged #25626 for RC1
Fixes #25624

### CODE REVIEW

**Comment by ajcvickers** [comment]
Why didn't you just put this in RC1 straight away? Then you only need one PR...

**Comment by roji** [comment]
Will do this next time, it's just not how my head works...

**Review by AndriySvyryd — APPROVED** [review]

**Comment by AndriySvyryd** [comment]
This wasn't targeting the right branch. It's **NOT** merged to rc1.

**Comment by roji** [comment]
*sigh* sorry, will resubmit.

**Comment by roji** [comment]
Opened #25633 against release/6.0-rc1

**Pull request merged**
