### PR TITLE
Bump SQLitePCLRaw to 2.0.6

### PR DESCRIPTION
**Pull request by bricelam**

### CODE REVIEW

**Comment by ericsink** [comment]
@bricelam I plan to be available to provide short turnaround on any fixes needed for your release cycle.  Please let me know if you need anything.

**Comment by gdoron** [comment]
@bricelam 
Not specific to just this Pull request, but I'm wondering why MSFT itself doesn't seem to work with nuget's `Directory.Packages.props` file.

**Comment by bricelam** [comment]
@gdoron I'd love to, but my top priority is keeping [arcade](https://github.com/dotnet/arcade) and (if possible) dependabot happy. 😉

**Comment by bricelam** [comment]
Looks like our CI is hitting https://github.com/ericsink/SQLitePCL.raw/issues/445

**Comment by ericsink** [comment]
2.0.6-pre20210902144138 should fix that.  Do you want to try it and then if it works I'll release it as 2.0.6 (non-pre)?  The only diff from 2.0.5 is that the linux builds were done on ubuntu 18.04.

**Comment by dougbu** [comment]
> I'll release it as 2.0.6 (non-pre)?

Time is tight because we need to shut down 6.0 relatively soon and can't ship non-preview packages that depend on previews. But, this should work if 2.0.6-pre20210902144138 does. Right @bricelam❔

**Comment by bricelam** [comment]
@wtgodbe Can we mirror the 2.0.6-pre20210902144138 versions of [the packages](https://github.com/dotnet/efcore/pull/25730#issuecomment-906587280)?

**Comment by wtgodbe** [comment]
> @wtgodbe Can we mirror the 2.0.6-pre20210902144138 versions of the packages?

Done

**Comment by ericsink** [comment]
FYI, my test suites are passing on ubuntu 16.04, 18.04, and 20.04.  So I'm going to proceed with my 2.0.6 release.  It's building now and will get pushed to nuget.org when the ci is done.  It is still true that nothing has changed except the linux builds of e_sqlite3 and e_sqlcipher.

**Comment by bricelam** [comment]
Success! As always, thank you for your help on this, Eric.

**Review by smitpatel — APPROVED** [review]

**Comment by dougbu** [comment]
`v2.0.6` packages are now available on NuGet. Can we move there to avoid another update before RTM❔

Separately, will likely need the following in dependabot.yml. Same for any other dependencies controlled there and used in product projects. Updates will otherwise violate dependency rules once we stabilize versions for `v6.0.0`.

``` yaml
    ignore:
      - dependency-name: "SQLitePCLRaw*"
        update-types: ["version-update:semver-patch"]
```

**Comment by gdoron** [comment]
@bricelam we are using it and dependabot, and they work perfectly fine together. FYI.

https://github.com/dependabot/dependabot-core/pull/1880

**Comment by bricelam** [comment]
@wtgodbe Can we mirror the 2.0.6 versions of [the packages](https://github.com/dotnet/efcore/pull/25730#issuecomment-906587280)?

**Comment by wtgodbe** [comment]
Done

**Review by smitpatel — APPROVED** [review]

**Pull request merged**
