### PR TITLE
Scaffolding: Use "CodeTemplates" directory

### PR DESCRIPTION
**Pull request by bricelam**
Part of #4038

/cc @ErikEJ

### CODE REVIEW

**Review by smitpatel — APPROVED** [review]

**Comment by AraHaan** [comment]
I would prefer if the person could place their templates wherever they wish to place them and for the scaffolder to still be able to pick them up (or at least a way for them to do so).

**Comment by bricelam** [comment]
@AraHaan Can you submit an issue so we can discuss as a team?

**Comment by AraHaan** [comment]
Sure, I can submit an issue as soon as I can.

**Comment by AraHaan** [comment]
Opened https://github.com/dotnet/efcore/issues/27656

**Pull request merged**
