### PR TITLE
#23395 Include Synonyms for SqlServer scaffolding.

### PR DESCRIPTION
**Pull request by Trapov**
Implements -> #23395

### CODE REVIEW

**Comment by ErikEJ** [comment]
You should also add tests :smile:

**Comment by Trapov** [comment]
> You should also add tests 😄

Ok, I will. Just need more time.

**Comment by Trapov** [comment]
@ErikEJ One simple test was added.

**Comment by ajcvickers** [comment]
Waiting for response on https://github.com/dotnet/efcore/issues/23395#issuecomment-731400055

**Comment by ajcvickers** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
