### PR TITLE
Add ability to configure the navigation on dependent side of Owned-types

### PR DESCRIPTION
**Pull request by lajones**
Fix for #6674 . Based on PR #20271 

This adds the last part - being able to configure the dependent side navigation of an Owned-type relationship.

(This PR will need to be merged with the work in #20271 before committing).

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
This isn't the last part for #6674. We still need to handle fields in the expression as I've mentioned previously. And we should also add `HasField` to `NavigationBuilder` to allow configuring a field that's not found by convention.

**Comment by lajones** [comment]
You mean #11610? I'm going to open a new bug and track that separately.

**Comment by AndriySvyryd** [comment]
Rebase and create an issue for the remaining work

**Comment by lajones** [comment]
@AndriySvyryd Note #11610 already has a bug - it's #11410 - which is assigned to me.

**Comment by AndriySvyryd** [comment]
@lajones Ok, but where are you tracking removing the "old way" and adding `HasField`?

**Comment by lajones** [comment]
Created #20281 to track the `HasField` issue. #6674 will track "removing the old way".

**Comment by lajones** [comment]
Closing this in favor of #20282 (which commits to master).

**Pull request closed without merging**
