### PR TITLE
Use Ubuntu 18.04 build agents

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Review by TanayParikh — APPROVED** [review]

**Comment by dougbu** [comment]
@ajcvickers I suspect the ICU update in this PR changed something in the collations. On macOS and Windows, the following code works fine

``` c#
        [Fact]
        public void FindMigrationId_returns_first_candidate_when_id()
            => Assert.Equal(
                "20150302103100_Flutter",
                CreateMigrationsAssembly().FindMigrationId("20150302103100_FLUTTER"));

        [Fact]
        public void FindMigrationId_returns_first_candidate_when_name()
            => Assert.Equal(
                "20150302103100_Flutter",
                CreateMigrationsAssembly().FindMigrationId("FLUTTER"));
```
but, on the updated Linux build (which is the oldest Ubuntu in support), `FindMigrationId(...)` returns `20150302103100_FLUTTER` in both tests. Should I change the expectation to be platform-specific, standardize the collations (how❔), or just pass `ignoreCase: true` to `Assert.Equal(...)`❔

**Comment by ajcvickers** [comment]
@bricelam What is the goal of having two names that differ by case? Is the intention to find either one arbitrarily?

```C#
        [DbContext(typeof(Context))]
        [Migration("20150302103100_Flutter")]
        private class Migration1 : Migration
        {
            protected override void Up(MigrationBuilder migrationBuilder)
            {
            }
        }

        [DbContext(typeof(Context))]
        [Migration("20150302103100_FLUTTER")]
        private class Migration2 : Migration
        {
            protected override void Up(MigrationBuilder migrationBuilder)
            {
            }
        }
```

**Comment by dougbu** [comment]
Never mind @ajcvickers. The 18.04 images lack `libicu60` and that's a prerequisite for .NET Core on that platform. Not having it explains why string ordering is busted.

I'm submitting an AzDO ticket.

**Comment by dougbu** [comment]
Holding for a actions/virtual-environments#3120 fix (or at least a workaround)

**Pull request merged**
