### PR TITLE
[WIP] Fix for #8434 - Add ability to scaffold IEntityTypeConfiguration classes

### PR DESCRIPTION
**Pull request by APErebus**
As per #8434, it would be nice to have the ability to scaffold `IEntityTypeConfiguration` classes as an option to either `OnModelCreating` or data attributes.

This is still WIP as I'm working on adding tests and looking for feedback on the approach I've taken

In the process of understanding how the scaffolding code works, I realised that the `OnModelCreating`/`DbContext` configuration generation output is very similar (if not identical) to the output required for `IEntityTypeConfiguration`.

I extracted the appropriate parts of that code into a new `ICSharpFluentConfigurationGenerator` (and appropriate implementation) that provides a single location for resolving the model and generating the code required for fluent config. These methods broadly return a list of lines to be written, allowing the consumer class to generate the correct code.

I added a new `ICSharpEntityTypeConfigurationGenerator` which is the class that actually generates an `IEntityTypeCOnfiguration` class for each entity.

I also put in new parameters into the `ef scaffold` command, which allow you to
- Specify to scaffold `IEntityTypeConfiguration` classes
- Specify a default suffix to add to these generated classes. (e.g. `MyEntity[Suffix].cs`)

I'm still working on adding appropriate tests to make sure it's generating correctly, but it seems to be working at least in the basic cases.

Some things I'm not 100% sure about and would love some feedback on:
- I'm not sure if we need a new way to specify what configuration style to run (in the `ef` command). How do we handle if someone specifies `-d|--data-attributes` as well as the new command I added?
- I added a `EntityConfigurationLocation` enum to "track" the "location" of the configuration, as if we have specified `IEntityConfiguration` classes, then we need to write a line into the `OnModelCreating` to search the assembly for these classes. Is this an acceptable approach?
- The `ef` command parameter names are super long (imo) and probably could be more concise. Happy for some feedback on them.

### CODE REVIEW

**Comment by bricelam** [comment]
Have you seen my T4-based sample [bricelam/EFCore.TextTemplating](https://github.com/bricelam/EFCore.TextTemplating/blob/master/EFCore.TextTemplating/Design/MyEntityTypeGenerator.tt)? It's still a work in progress, but it gives users a lot more flexibility to format the code and name/structure things however they want to. Do you think finishing that sample and promoting it would be more helpful to users than adding this feature?

**Comment by ajcvickers** [comment]
Agree that templating is the way to go here.

**Comment by APErebus** [comment]
> Have you seen my T4-based sample [bricelam/EFCore.TextTemplating](https://github.com/bricelam/EFCore.TextTemplating/blob/master/EFCore.TextTemplating/Design/MyEntityTypeGenerator.tt)? It's still a work in progress, but it gives users a lot more flexibility to format the code and name/structure things however they want to. Do you think finishing that sample and promoting it would be more helpful to users than adding this feature?

I hadn't no. I had just followed on from the existing code approach for entity/dbcontext generation.

I think that's probably outside of my skill-set, Happy to close off this PR in favour of that approach, however that's not something I have knowledge or ability in.

**Comment by bricelam** [comment]
Closing since we'd like to focus on templates before generating IEntityTypeConfiguration.

I finished the implementation of my T4 project. See a sample of [a configuration class](https://github.com/bricelam/EFCore.TextTemplating/blob/master/EFCore.TextTemplating/Data/TrackConfiguration.cs) here. I'll tidy it up and add a readme file explaining how it works then before really promoting it, but feel free to start tinkering with it in your own projects.

**Pull request closed without merging**
