### PR TITLE
Fix for culture settings sensitive tests

### LINKED ISSUE #24813: BuiltInDataTypesSqlServerTest.Object_to_string_conversion test fails when run in non en-us localization settings
When decimal separator is set to something else than ',' test fails with:

```
  Message: 
    Assert.Equal() Failure
                         ↓ (pos 11)
    Expected: -1234567890,01
    Actual:   -1234567890.01
                         ↑ (pos 11)
                         
Stack Trace: 
    BuiltInDataTypesTestBase`1.Object_to_string_conversion() line 2067
    BuiltInDataTypesSqlServerTest.Object_to_string_conversion() line 3370                         
```

The expected value is taken from decimal.ToString() from Enumerable and should use ToString(CultureInfo.InvariantCulture) IMHO.

Please confirm I can prepare PR for this.

### PR DESCRIPTION
**Pull request by michalczerwinski**
Some tests were failing in environment having decimal separator set to something else than '.'
This fixes #24813 

Additional justification: all providers are expected to translate ToString to culture-invariant values. Hence we should also use CultureInvariant in expected values for tests.

### CODE REVIEW

**Comment by smitpatel** [comment]
This is not the way intend to fix the issue. And you have not made the test to do client evaluation of ToString rather than server side which is what intention of test was.

**Comment by michalczerwinski** [comment]
@smitpatel : what would be the better way? In the linked bug @roji suggested using module initializer to set  .NET locale to InvariantCulture globally. Would it be ok with you?

**Comment by michalczerwinski** [comment]
@smitpatel: I review the issues related to culture settings and I believe there are different type of problems there.
In this case the problem it pretty straightforward, test is expecting wrong values, as the expected values depends on current culture settings. So the obvious fix is to change the way the expected values are calculated.

Happy to fix this in any other way if you share some thoughts, though.

**Comment by roji** [comment]
@michalczerwinski we discussed this issue in a design meeting, and came up with [these conclusions](https://github.com/dotnet/efcore/issues/14912#issuecomment-840034610). In other word, rather than enforcing an invariant culture each and every time a locale-sensitive operation is done in the tests, we'd do it globally (a module initializer is definitely an option).

The other half of this is similarly enforcing that locale at the *database* side, otherwise tests may fail because of a discrepancy between the two. This means making sure that test databases are created with an explicit locale (or collation) which corresponds to the test locale discussed above.

Are you interested in pursuing this?

**Comment by michalczerwinski** [comment]
@roji: I am definitely interested in fixing part 1: enforcing invariant culture in tests globaly. I will look at options in xUnit and module initializer and adjust my PR.

The second part (enforcing at db side): let me get back to this and confirm once we are done with part one.

**Comment by michalczerwinski** [comment]
Please see the solution using module initializer. This works and solves the issues I seen on my machine with pl-PL culture set as default.

Details:
* module initializer is executed before the first access to anything defined in the module
* CultureInfo.CurrentCulture is static

So this will effectively prevent any other culture being set globally in other test projects using base tests, in accordance with #14912

**Comment by roji** [comment]
Unless I'm mistaken, CultureInfo.CurrentCulture will set the culture for the current thread only. Is there some sort of guarantee that this module initializer code will take effect on all spawned threads? Otherwise it may be safer to deal with this within the xunit infrastructure...

**Comment by michalczerwinski** [comment]
@roji: I updated the PR and now I also set DefaultThreadCurrentCulture which should affect the threads spawned later.

**Comment by roji** [comment]
Seems like there's [this](https://github.com/devlooped/xunit.assemblyfixture), though as indicated in https://github.com/xunit/xunit/issues/187 it hasn't been updated in a long while.

I'm not sure there's a guarantee that all xunit threads are going to be spawned from the thread that initially went through the module initializer... On the other hand we could give this a try and revisit if problems do pop up.

@dotnet/efteam any thoughts?

**Comment by AndriySvyryd** [comment]
If the module initializer works, it should be enough for now. Once we start adding culture-specific tests classes we can move this to `SharedStoreFixtureBase.InitializeAsync` and `NonSharedModelTestBase.InitializeAsync` so it can be parameterized

**Comment by roji** [comment]
> Once we start adding culture-specific tests classes we can move this to SharedStoreFixtureBase.InitializeAsync and NonSharedModelTestBase.InitializeAsync so it can be parameterized

I don't think that would be necessary - it should still be possible for specific tests (or even classes) to override the locale set in the module-initializer (and then set it back when the test completes).

**Comment by roji** [comment]
@michalczerwinski this looks OK, but ideally we'd also take care of the database side at the same time. Otherwise, anyone with a non-English client locale that matches their database locale will start seeing test failures as a result of this. Let me know if you want to look at that.

**Comment by michalczerwinski** [comment]
@roji: how many db providers are we speaking here? If this is SQL Server/Sqlclient I can take care of this.

**Comment by roji** [comment]
Yep, I think this is only those two. It seems Cosmos doesn't have this issue (/cc @smitpatel), and other providers which aren't in the repo would have to take care of this themselves for their databases.

**Comment by roji** [comment]
@michalczerwinski are you still intending to handle the 2nd part of this, i.e. making sure that all SQL Server/Sqlite test databases get created with the `en-US` locale? We cannot merge this PR as-is, because it changes only the .NET side, so running it against a database in some other locale will cause failures.

**Comment by roji** [comment]
Closing as no answer was provided, we'll revisit this at some point.

**Pull request closed without merging**
