### PR TITLE
Update BenchmarkDotNet version

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes memory reports

### CODE REVIEW

**Comment by smitpatel** [comment]
You may need to get the package mirrored in the internal feeds via build team.

**Comment by sebastienros** [comment]
You may think I haven't, wrong you would be

**Comment by sebastienros** [comment]
It just takes time to update the packages, let's try again now

**Comment by sebastienros** [comment]
You might also think that I forgot to ask for BenchmarkDotnet.Annotations, right you would be

**Comment by smitpatel** [comment]
Trust in your skills, I have.

**Review by AndriySvyryd — APPROVED** [review]

**Pull request merged**
