### PR TITLE
SQL row value comparison syntax

### LINKED ISSUE #26822: Db function to translate row value syntax
Row value is part of the SQL standard -though not supported by every database in all places- and it allows using the following syntax (for example in a where clause):
```sql
WHERE (timestamp, id) > ('2019-03-10 00:00:00+00:00', 1032749689)
```

This is in particular a highly valuable syntax when doing keyset/seek/cursor pagination, and being able to use it with databases that support it will be a big win for seek pagination in particular, but also composite conditions that can gain from this syntax in general.

The row value syntax above is equivalent, in theory, to something like this:
```sql
WHERE
    (timestamp > '2019-03-10 00:00:00+00:00') OR
    (timestamp = '2019-03-10 00:00:00+00:00' AND id > 1032749689)
```

But, for one, this logic condition becomes more complex the more columns you have. In addition, the db implementation of row value will usually be much more efficient than this (there are a few things you can do that can help the db engine in the above condition, but it doesn't look nice or readable).

More info about row value here: https://use-the-index-luke.com/sql/partial-results/fetch-next-page#sb-row-values

My use case is a [package](https://github.com/mrahhal/MR.EntityFrameworkCore.KeysetPagination) I worked on that fully implements keyset pagination with EF Core, but does so by building the expressions so that it translates to the logical condition syntax above. I could use a row value translator.

For a related issue to keyset pagination see this: https://github.com/dotnet/efcore/issues/9115

## Proposed solution

What I would love to see is a db function that EF Core understands and translates into the row value syntax for db providers that support it. Something like this:
```c#
var timestamp = ...;
var id = 1032749689;

// Very shoddy for now but to illustrate my example:
.Where(x => DbFunctions.GreaterThan(b => b.Add(x => x.Timestamp, timestamp).Add(x => x.Id, id)))

// Translates to sql:
// WHERE (timestamp, id) > ('2019-03-10 00:00:00+00:00', 1032749689)
```

One thing I'm not sure of is if there's a system in place that would allow a consumer to know if the current database provider supports this syntax or not. Because I want to be able to fallback to my implementation in such a case.

If this seems like an interesting and feasible addition, I'm willing to work on it.

### PR DESCRIPTION
**Pull request by mrahhal**
- [x] New EF.Functions extensions: `LessThan`, `LessThanOrEqual`, `GreaterThan`, `GreatThanOrEqual`.
- [ ] Implement and support a new `RowValueExpression` that translates to SQL row value syntax.
  - [x] `RowValueExpression`
  - [x] `RowValueTranslator`
  - [x] `QuerySqlGenerator`
  - [x] `SqlExpressionFactory`
  - [ ] `SqlNullabilityProcessor`
  - [x] `SearchConditionConvertingExpressionVisitor`
- [x] Override on SQL Server provider and expand to normal comparisons using `RowValueComparisonTranslator`

Closes #26822.

### CODE REVIEW

**Comment by mrahhal** [comment]
Current progress regarding things I had to do but I'm not 100% sure about:

- I had to create a new `ArrayExpression` from `NewArrayExpression` or else the columns array argument of the extension method will result in a non translated expression.
- Added `RowValueExpandedTranslator` in Relational which I'm using only in SQL server provider when I override the a `CreateRowValueTranslator` virtual method on `RelationalMethodCallTranslatorProvider`. (I had to suppress the internal usage analyzer error for that here)
- I'm facing trouble figuring out how to reach the actual values when an `SqlParameterExpression` is involved. Example:
  ```cs
  var a = 2;
  query.Where(e => EF.Functions.LessThan(new object[] { e.EmployeeID }, new object[] { a }))
  ```
  In the above snippet I'm getting an `SqlParameterExpression` instead of a constant expression for the values array because I'm using a variable. I couldn't figure out how I can get the actual values. And without those I can't really generate the row value syntax (or the expanded comparisons).

**Comment by roji** [comment]
> I had to create a new ArrayExpression from NewArrayExpression or else the columns array argument of the extension method will result in a non translated expression.

Let me discuss this with @smitpatel to see exactly how we want to do this. I recommend holding off on this PR for a couple days until we're agreed on this.

> Added RowValueExpandedTranslator (which extends RowValueTranslator) in Relational, which I'm using in SQL server provider when I override the a CreateRowValueTranslator virtual method on RelationalMethodCallTranslatorProvider. (I had to suppress the internal usage analyzer error for that here)

I don't think there's much value in having RowValueExpandedTranslator extend RowValueTranslator - aside from looking up the relevant methods on EF.Functions, these translators shouldn't have anything in common really. We could also consider having RowValueExpandedTranslator in relational for any other provider where RowValueExpression isn't supported.

(BTW naming-wise I'd call the translator RowValueComparisonTranslator)

> I can't figure out how to reach the actual values when an SqlParameterExpression is involved. Example:

Does it help if you add a [NotParameterized] attribute on the array parameters? Again, I'll confirm this one with @smitpatel as well.

Re SearchConditionConvertingExpressionVisitor, this is a SQL Server-only visitor, but there's never going to be a RowValueExpression in SQL Server since that's not supported there. So I don't think that visitor needs to be changed.

**Comment by mrahhal** [comment]
> Let me discuss this with smitpatel to see exactly how we want to do this. I recommend holding off on this PR for a couple days until we're agreed on this.

👍🏻 

> I don't think there's much value in having RowValueExpandedTranslator extend RowValueTranslator

So it's ok to duplicate the shared code between them? For now that's looking up the EF.Functions, but I thought they might share more code like unwrapping the arguments, validating the columns arg, getting the values, etc. Maybe I can have this logic in some other helper class then? I tried to find a translator with a similar scenario to check what you do but couldn't find any.

> Does it help if you add a [NotParameterized] attribute on the array parameters?

That did it! It's giving me the same `SqlConstantExpression` now.

> SearchConditionConvertingExpressionVisitor, this is a SQL Server-only visitor, but there's never going to be a RowValueExpression [...]

Alright, so I can just have it throw a `NotImplementedException`.

**Comment by mrahhal** [comment]
@roji I have an initial working implementation for both row value and expanded comparisons. It wasn't a lot of work after resolving the parameter issue so I implemented some of your feedback too. As you said, I'll wait for your response regarding the array thing before going any further.

**Comment by mrahhal** [comment]
@roji Understood. I'll be ready to get this ready again in the future if necessary.

**Comment by roji** [comment]
Thanks for understand @mrahhal!

**Comment by roji** [comment]
@mrahhal I'm going to go ahead and close this for now, as discussed. We'll pick it up again when the proper tuple syntax becomes available.

**Pull request closed without merging**
