### PR TITLE
Add owned types to InheritanceRelationshipsQueryTest

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Part of #2266

### CODE REVIEW

**Comment by smitpatel** [comment]
Test failures?

**Comment by AndriySvyryd** [comment]
> Test failures?

Details

**Comment by smitpatel** [comment]
I saw all checks red in previous one so I mentioned. You force pushed so let's see what is outcome now. PR looks good.

**Comment by AndriySvyryd** [comment]
@smitpatel Ping

**Pull request merged**
