### PR TITLE
SqlServer RevEng: Handle included index columns

### LINKED ISSUE #17083: Scaffold Sql Server Database fail on index with include columns
Describe what is not working as expected.

When scaffold a database and  Index have include fields, they are scaffold as key columns.
The scaffold must use .ForSqlServerInclude("IIncludeColumn",...) for the include columns
                
### Steps to reproduce

This is the original index in the database

```
CREATE NONCLUSTERED INDEX [_dta_index_Clientes_54_1472724299__K2_K21_K1_K6_3_4_5_7_8_9_10_11_12_13_14_15_16_17_18_19_20_22_23_24_25_26_27_28_29_30_31_32_] ON [dbo].[Clientes]
(
	[IDTaller] ASC,
	[Referencia] ASC,
	[IDCliente] ASC,
	[Nombre] ASC
)
INCLUDE ( 	[IDComercial],
	[IDTipoCliente],
	[RazonSocial],
	[Apellidos],
	[NIFCIF],
	[Direccion],
	[CP],
	[Poblacion],
	[Provincia],
	[Pais],
	[Contacto],
	[Telefono],
	[Movil],
	[Fax],
	[Email],
	[Web],
	[IDIdioma],
	[FechaCarnet],
	[FechaNacimiento],
	[SeguroNombre],
	[SeguroApellidos],
	[SeguroNIFCIF],
	[BloqueaEnvios],
	[BajaEnvios],
	[MotivoBajaEnvios],
	[TelefonoOk],
	[MovilOk],
	[EmailOk],
	[SmsNoEmailOk],
	[EmailNoSMSOk],
	[LlamadaOk]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

```

this is the scafold, it join all the columns as part of the key
```
            entity.HasIndex(e => new { e.IDComercial, e.IDTipoCliente, e.RazonSocial, e.Apellidos, e.NIFCIF, e.Direccion, e.CP, e.Poblacion, e.Provincia, e.Pais, e.Contacto, e.Telefono, e.Movil, e.Fax, e.Email, e.Web, e.IDIdioma, e.FechaCarnet, e.FechaNacimiento, e.SeguroNombre, e.SeguroApellidos, e.SeguroNIFCIF, e.BloqueaEnvios, e.BajaEnvios, e.MotivoBajaEnvios, e.TelefonoOk, e.MovilOk, e.EmailOk, e.SmsNoEmailOk, e.EmailNoSMSOk, e.LlamadaOk, e.IDTaller, e.Referencia, e.IDCliente, e.Nombre })
                    .HasName("_dta_index_Clientes_54_1472724299__K2_K21_K1_K6_3_4_5_7_8_9_10_11_12_13_14_15_16_17_18_19_20_22_23_24_25_26_27_28_29_30_31_32_");

```

### Further technical details
EF Core version: 2.2.0

Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: W10
IDE: VS 2019 16.2.1

### PR DESCRIPTION
**Pull request by bricelam**
Fixes #17083

### CODE REVIEW

**Comment by smitpatel** [comment]
I was curious.
So when I use lambda based IncludeProperties, the annotation contains property names. If those properties are mapped to different column name, we handle it somewhere (couldn't find in source code yet).
In above we are storing column names rather than property names. Property names could be something different if column name is not valid C# identifier. Where & how that would be handled so that everything aligns properly?

**Comment by bricelam** [comment]
lol, probably a bug. See also https://github.com/dotnet/efcore/issues/14087

**Comment by bricelam** [comment]
Hmm, I wonder where would that code go. We don't know the property names here, and the model generator just blindly copies provider-specific annotations.

**Comment by AndriySvyryd** [comment]
https://github.com/dotnet/efcore/blob/10d9bb9fe327c920418df8c10f3035a758c2beaf/src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs#L151

**Comment by bricelam** [comment]
That handles IIndex -> ITableIndex, but I don't think we have a provider hook for the inverse. I'll file an issue.

**Comment by AndriySvyryd** [comment]
We would need a provider-specific reveng annotation processor

**Comment by bricelam** [comment]
Ugg, adding tests that assert bugs is definitely an anti-pattern.

**Pull request merged**
