### PR TITLE
Add simple in-memory provider configure extension

### PR DESCRIPTION
**Pull request by WeihanLi**
Summary of the changes
        
- Add simple in-memory provider configure extensions

Contribute to #25192

### CODE REVIEW

**Comment by ajcvickers** [comment]
@WeihanLi See #25487. We're not convinced this is a good idea, since we recommend people don't use the in-memory provider.

**Comment by WeihanLi** [comment]
@ajcvickers thanks for your reply, I think in-memory provider is not recommended for common business, but is recommended for test, so maybe this would make the in-memory provider register more easier

**Comment by roji** [comment]
@WeihanLi the use of the in-memory provider is strongly discouraged also for testing purposes, see [the docs](https://docs.microsoft.com/en-us/ef/core/testing/#approach-3-the-ef-core-in-memory-database).

**Comment by WeihanLi** [comment]
Get it, thanks @roji

**Pull request closed without merging**
