### PR TITLE
Long and ULong properties marked as rowversion automatically convert to binary on SQL Server

### LINKED ISSUE #12434: IsRowVersion or [Timestamp] on property that maps to provider byte[] type should generate rowversion column
As described in #5936, mapping a ulong with a store type of "rowversion" (or "timestamp") results in a rowversion column in SQL Server that can be used effectively in LINQ queries. This should also work for cases like this:
```C#
public class Blog
{
    public int Id { get; set; }
    public ulong RowVersion { get; set; }
}

modelBuilder
    .Entity<Blog>()
    .Property(e => e.RowVersion)
    .HasConversion<byte[]>()
    .IsRowVersion();
```
and this:
```C#
public class Blog
{
    public int Id { get; set; }

    [Timestamp]
    public ulong RowVersion { get; set; }
}

modelBuilder
    .Entity<Blog>()
    .Property(e => e.RowVersion)
    .HasConversion<byte[]>();
```
And possibly even when ` .HasConversion<byte[]>()` is not used explicitly, since IsRowVersion or [Timestamp] imply this, at least for SQL Server

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #12434

### CODE REVIEW

**Review by roji — COMMENTED** [review]
Just to note that this introduces implicit usage of NumberToBytesConverter, which means it wouldn't be trimmable. I'm not claiming NumberToBytesConverter specifically is big (and we already do this kind of thing with many other converters), but in the trimming/NativeAOT world there's a tradeoff between making everything "just work" out of the box, and reducing binary size.

It may be worth shifting our mindset to requiring explicit configuration at least in some cases, especially where the explicit gesture is very simple.

**Comment by ajcvickers** [comment]
Keep in mind that NumberToBytesConverter is already brought in anyway.

**Comment by ajcvickers** [comment]
@roji I think we need to consider type mapping like model building. Right now, all of type mapping, including converter selection, is referenced always, and much of it is eagerly initialized. We should get to a place where with a compiled model and queries we don't need any but pre-defined type mappings, including converters, and the rest can be trimmed. But that's not trivial.

**Comment by roji** [comment]
Interesting, we should think about that at some point... It definitely seems less trivial conceptually than model building, where there's a very clear (existing) split between a (runtime) model and all the (non-runtime) infra needed to build it.

Maybe there's some world in which stuff like ValueGeneratorSelector is no longer there at runtime, only in AOT-generated code, I don't know.

**Comment by ajcvickers** [comment]
Yes, the separation is not as clear, but I think it can be done. Note we already have #25926.

**Pull request merged**
