### PR TITLE
[5.0.1] Query: Properly generate expression to read from BufferedDataReader

### LINKED ISSUE #23104: Buffering data reader may not be preserving types correctly
xref: https://github.com/efcore/EFCore.SqlServer.HierarchyId/issues/24

Rather than passing SqlBytes to the converter, we pass object when using buffering data reader. Buffering data reader should match up type correctly.

### LINKED ISSUE #23282: Unable to load entities since upgrading to 5.0.0 (InvalidCastException on entities referencing Owned types containing NetTopologySuite Point properties)
Since upgrading to 5.0.0 I'm finding that attempts to load entities referencing Owned types containing NetTopologySuite  Point properties fails. This worked before; the only change to the project has been to retarget to .NET 5.0 and upgrade packages to 5.0.0. Aside from this issue, my project builds and runs just fine.

### Steps to Reproduce

I've created a barebones project [here](https://github.com/jordanwallwork/EfErrorTest) which demonstrates the issue. I used the ASP.NET Core Web Application project template, upgraded it to .NET 5.0 and added Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite 5.0.0 and a couple of simple enties - a `Location`, which owns an `Address` which has a `Point` property.

### Stack Trace

```
System.InvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader' to type 'Microsoft.Data.SqlClient.SqlDataReader'.
   at lambda_method11(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at EfErrorTest.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Projects\EfErrorTest\EfErrorTest\Startup.cs:line 35
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at EfErrorTest.Program.Main(String[] args) in C:\Projects\EfErrorTest\EfErrorTest\Program.cs:line 16
```

### Output

```
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'EfErrorTest.AppDbContext'.
      System.InvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader' to type 'Microsoft.Data.SqlClient.SqlDataReader'.
         at lambda_method11(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
      System.InvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader' to type 'Microsoft.Data.SqlClient.SqlDataReader'.
         at lambda_method11(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.InvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader' to type 'Microsoft.Data.SqlClient.SqlDataReader'.
         at lambda_method11(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
         at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
         at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
         at EfErrorTest.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Projects\EfErrorTest\EfErrorTest\Startup.cs:line 35
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
         at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
         at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
         at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
         at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
         at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```

### Provider + Version Info

EF Core version: 5.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.8

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #23282
Resolves #23104

Issue: When buffering is enabled, first time when we read particular property slot, we create expression to read into buffer and out of the buffer. We mistakenly bypassed changing expression to read from value buffer when same property slot was being read again, causing cast errors.

**Description**

Any type mapping having custom read expression from data reader throws an exception while retrying strategy is enabled. This was reported for SQL Server spatial types, but we know that Oracle uses the same pattern for some of its type mappings, so this is likely to be broken for Oracle too once they have an updated provider.

**Customer Impact**

When retrying strategy is enabled (which is recommended for all SQL Azure applications), querying for spatial types or any other non-primitive type will hit an exception.

**How found**

Customer reported on 5.0.

**Test coverage**

Added test for affected scenario.

**Regression?**

Yes, this worked in 3.1.

**Risk**

Low.  This reverts back to 3.1 behavior in terms of generating correct expression.

### CODE REVIEW

**Comment by ajcvickers** [comment]
@smitpatel Are you confident we don't need to test any other variations?

**Comment by smitpatel** [comment]
I enabled retrying execution strategy for whole SqlServer functional tests and ran all tests and all passed (except obvious wrong ones in the tests which tests retrying strategy). Further looking at blame (which is on me), it was incorrect refactor and this code is pretty close to what 3.1 did. So I am quite confident.
Though I want @AndriySvyryd & @maumar both to review and approve.

**Comment by ajcvickers** [comment]
Thanks @smitpatel. Makes sense.

**Review by AndriySvyryd — APPROVED** [review]

**Review by maumar — APPROVED** [review]

**Comment by ajcvickers** [comment]
Approved by Tactics for 5.0.1

**Comment by LarysaMatsirka** [comment]
[smitpatel](https://github.com/smitpatel)[smitpatel](https://github.com/smitpatel) is it possible to add the same fox for v.3.1.7? Initially bug was reported for this version (https://github.com/efcore/EFCore.SqlServer.HierarchyId/issues/24)

**Pull request merged**
