### PR TITLE
Minor cleanup for queryable function support

### PR DESCRIPTION
**Pull request by roji**
/cc @smitpatel @pmiddleton

### CODE REVIEW

**Comment by smitpatel** [comment]
Please don't! I am already working in this area and this will just cause merge conflicts!

**Comment by roji** [comment]
No worries, I can rebase this (if necessary!) after you finish your work. Feel free to close this, or just ping me here when you're done for me to rebase.

**Comment by pmiddleton** [comment]
merge-conflicts-merge

**Comment by smitpatel** [comment]
Can you resolve existing conflicts? #20178  can cause some conflicts but nothing major. Either PR going first is fine.

**Comment by roji** [comment]
@smitpatel working on merge conflicts isn't my preferred pre-bedtime activity...! Go ahead and merge yours, I'll take care of resolving conflicts tomorrow.

**Comment by pmiddleton** [comment]
@roji

You might want to checkout #20178 before you say that:)

**Comment by roji** [comment]
@smitpatel already did thumbs-up so I've lost my chance...

**Comment by roji** [comment]
Rebased, not too much left!

**Pull request merged**
