### PR TITLE
Propagate identity seed and increment to sharing columns

### LINKED ISSUE #22358: Owned entity and entity mapped to 'Id' but are configured with different identity increment
A change introduced in `5.0.0-preview3` results in the following error:
```sh
System.InvalidOperationException: 'Map.Id' and 'LatLngBounds.MapId' are both mapped to column 'Id' in 'Map' but are configured with different identity increment.
   at Microsoft.EntityFrameworkCore.SqlServer.Internal.SqlServerModelValidator.ValidateCompatible(IProperty property, IProperty duplicateProperty, String columnName, String tableName, String schema, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedColumnsCompatibility(IReadOnlyList`1 mappedTypes, String tableName, String schema, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Internal.SqlServerModelValidator.ValidateSharedColumnsCompatibility(IReadOnlyList`1 mappedTypes, String tableName, String schema, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.SqlServer.Internal.SqlServerModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValidatingConvention.ProcessModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelFinalized(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FinalizeModel()
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
'Map.Id' and 'LatLngBounds.MapId' are both mapped to column 'Id' in 'Map' but are configured with different identity increment.
```

```cs
    public class Map : UserAuditableEntity, IAggregateRoot
    {
        private readonly List<Marker> markers;

        // NOTE(msschl): Constructor for ef core
        protected Map(int id, Guid mapId, MapMode mode,
            Guid createdBy, DateTime createdAt, Guid? lastModifiedBy = null, DateTime? lastModifiedAt = null)
            : base(createdAt, createdBy, lastModifiedAt, lastModifiedBy)
        {
            this.Id = id;
            this.MapId = mapId;
            this.Mode = mode;

            this.markers = new List<Marker>();
        }

        public int Id { get; }

        public Guid MapId { get; }

        [NotNull]
        public LatLngBounds? Viewport { get; }

        public MapMode Mode { get; }

        public IReadOnlyCollection<Marker> Markers => this.markers;
    }

    public sealed class LatLngBounds : ValueObject
    {
        // NOTE(msschl): ctor for EF Core
        private LatLngBounds()
        { }

        private LatLngBounds(Coordinate southwest, Coordinate northeast)
        {
            this.Southwest = southwest;
            this.Northeast = northeast;
        }

        [NotNull]
        public Coordinate? Southwest { get; }

        [NotNull]
        public Coordinate? Northeast { get; }

        public static LatLngBounds For(double southwestLatitude, double southwestLongitude,
            double northeastLatitude, double northeastLongitude)
        {
            try
            {
                return new LatLngBounds(
                    Coordinate.For(southwestLatitude, southwestLongitude),
                    Coordinate.For(northeastLatitude, northeastLongitude)
                );
            }
            catch (Exception ex)
            {
                throw new LatLngBoundsInvalidException(ex);
            }
        }

        public override string ToString()
            => $"{nameof(LatLngBounds)}(SW: {this.Southwest}; NE: {this.Northeast})";

        protected override IEnumerable<object> GetAtomicValues()
        {
            yield return this.Southwest.Latitude;
            yield return this.Southwest.Longitude;
            yield return this.Northeast.Latitude;
            yield return this.Northeast.Longitude;
        }
    }

    public sealed class Coordinate : ValueObject
    {
        private Coordinate(double latitude, double longitude)
        {
            this.Latitude = latitude;
            this.Longitude = longitude;
        }

        public double Latitude { get; }

        public double Longitude { get; }

        public static Coordinate For(double latitude, double longitude)
        {
            if (latitude < -90.0 || latitude > 90.0)
            {
                throw new CoordinateInvalidException(
                    new ArgumentException("Latitude must be inclusive between -90.0 and 90.0!", nameof(latitude))
                );
            }

            if (longitude < -180.0 || longitude > 180.0)
            {
                throw new CoordinateInvalidException(
                    new ArgumentException("Longitude must be inclusive between -180.0 and 180.0!", nameof(longitude))
                );
            }

            return new Coordinate(latitude, longitude);
        }

        public override string ToString()
            => $"{nameof(Coordinate)}({this.Latitude}x{this.Longitude})";

        protected override IEnumerable<object> GetAtomicValues()
        {
            yield return this.Latitude;
            yield return this.Longitude;
        }
    }
```

```cs
    public class MapEntityTypeConfiguration : IEntityTypeConfiguration<Map>
    {
        public void Configure(EntityTypeBuilder<Map> builder)
        {
            builder.Property(e => e.Id)
                .IsRequired()
                .UseIdentityColumn();

            builder.Property(e => e.MapId)
                .IsRequired()
                .HasMaxLength(36);

            builder.OwnsOne(e => e.Viewport, builder =>
            {
                builder.OwnsOne(e => e.Southwest, builder =>
                {
                    builder.Property(e => e.Latitude)
                        .IsRequired()
                        .HasColumnName("SouthwestLat");

                    builder.Property(e => e.Longitude)
                        .IsRequired()
                        .HasColumnName("SouthwestLng");
                });

                builder.OwnsOne(e => e.Northeast, builder =>
                {
                    builder.Property(e => e.Latitude)
                        .IsRequired()
                        .HasColumnName("NortheastLat");

                    builder.Property(e => e.Longitude)
                        .IsRequired()
                        .HasColumnName("NortheastLng");
                });
            });

            builder.Property(e => e.Mode)
                .HasColumnType("INTEGER")
                .HasDefaultValue(MapMode.Default)
                .IsRequired();

            builder.Property(e => e.CreatedBy)
                .IsRequired()
                .HasMaxLength(36);

            builder.Property(e => e.CreatedAt)
                .IsRequired()
                .HasDefaultValueSql("getdate()");

            builder.Property(e => e.LastModifiedBy)
                .HasMaxLength(36);

            builder.Property(e => e.LastModifiedAt);

            builder.HasKey(e => e.Id);

            builder.HasIndex(e => e.MapId)
                .IsUnique();

            builder.HasMany(e => e.Markers)
                .WithOne(e => e.Map)
                .HasForeignKey(e => e.MapId)
                .IsRequired();

            builder.ToTable("Map");
        }
    }
```

From the exception I suspect that ef core maps the LatLngBounds Id to the wrong property on the Map entity, i.e. `MapId` which is actually not the identity column.
May be there is a way to configure the primary key for the owned entity type?

### Further technical details

EF Core version: 5.0.0-preview3 upwards
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .Net 5.0
Operating system: Win 10 x64
IDE: vscode

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #22358

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
@dotnet/efteam New overloads:

- `GetHiLoSequenceName`, `GetHiLoSequenceSchema`, `FindHiLoSequence`

**Comment by AndriySvyryd** [comment]
@Pilchie For RC2

**Review by smitpatel — APPROVED** [review]

**Comment by bricelam** [comment]
Is RC2 in aks mode? I thought that didn't start until Sept 14...

**Comment by AndriySvyryd** [comment]
@bricelam RC2 is in M2 ask mode, on Sept 14 Tactics ask mode starts

**Comment by Pilchie** [comment]
Approved for .NET 5.0 RC2

**Pull request merged**
