### PR TITLE
Be consistent about ifdefs for .NET 5

### PR DESCRIPTION
**Pull request by ajcvickers**

### CODE REVIEW

**Comment by roji** [comment]
Shouldn't there be the one standard way to test for this, rather than all three options? I'm guessing NET50 is supposed to be that, if it works should just use it?

**Comment by ajcvickers** [comment]
@roji At this point I would rather be safe and consistent than minimal.

**Comment by bricelam** [comment]
It should be `NET5_0`--the SDK unifies to this.

**Comment by ajcvickers** [comment]
@bricelam That's the one that doesn't work universally.

**Comment by bricelam** [comment]
In other words `net50`, `net5.0`, and `netcoreapp5.0` all result in the `NET5_0` define constant

**Comment by bricelam** [comment]
What SDK do you have installed? I'm seeing this in preview.7

**Comment by ajcvickers** [comment]
@bricelam I'm using the one installed by our build--which I believe is preview 7 currently. However, it may be that my IDE doesn't understand it yet.

**Comment by bricelam** [comment]
Does `NET5_0 || NETCOREAPP5_0` work? I'm good with that.

**Comment by ajcvickers** [comment]
Also, `NET5_0` is soooo ugly!

**Comment by bricelam** [comment]
Could just use `NET`...

**Comment by bricelam** [comment]
Oh wait, no we can't. 🤦‍♂️

**Comment by ajcvickers** [comment]
Okay, updated to just NET5_0. This builds for me in my IDE, although there are some syntax highlighting issues.

**Comment by ajcvickers** [comment]
@dotnet/efteam Approve?

**Pull request merged**
