### PR TITLE
Disallow setting custom translation for DbFunction mapped to TVFs

### LINKED ISSUE #20163: Disallow IDbFunction.HasTranslation when mapping the function to a TVF
Since TVFs are UDFs (does not map to built-in methods), having to customize translation becomes less useful. (Also parameters would be in same order too). We will throw error in model validation if IDbFunction is IsQueryable, then configuring custom translation will throw exception.

~Currently it assumes that a scalar SQL will come out. If we are planning to use same IDbFunction for queryable functions too then it needs rework or breaking change.~

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #20163

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
Even if having a custom translation is less useful it's still valid in some scenarios. So instead of just throwing this should be a warning that defaults to throwing.

**Comment by AndriySvyryd** [comment]
Or we can do that when we introduce a better API to set the translation.

**Comment by smitpatel** [comment]
We don't use custom translation in query. (We cannot use it either till API is changed). So throwing is better than warning and then ignoring it.

**Comment by AndriySvyryd** [comment]
Please avoid merging more than 2 PRs per 30 minutes to master

**Pull request merged**
