### PR TITLE
Change some metadata extension methods into DIM properties and annotate for nullability

### PR DESCRIPTION
**Pull request by roji**
@AndriySvyryd we can also move other extension methods to be properties on the interfaces if we want (especially internal ones).

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
All public extensions should continue to be methods to avoid the breaking change, using properties doesn't give any significant enough advantage

**Comment by roji** [comment]
@AndriySvyryd are you saying to want me to add back the extension methods, calling the new properties, to maintain binary backwards compat here? Or that you're against the properties altogether (although we want to do #19213 anyway)?

Re the advantage of properties, the main reason for introducing them was to be able to use the new [MemberNotNullWhen], which isn't usable on extension methods.

**Comment by AndriySvyryd** [comment]
@roji No, I'm saying that they should be methods with DIM. We don't necessarily need binary compat, but we should preserve compile compat.

**Comment by roji** [comment]
Will change.

**Review by AndriySvyryd — APPROVED** [review]
`HasClrType` can become a property, since it was pubternal before

**Comment by smitpatel** [comment]
(Removed auto-merge, I will add it back. Trying to get release/5.0 merged to main)

**Comment by AndriySvyryd** [comment]
(nit) Commit description is not accurate

**Comment by roji** [comment]
@AndriySvyryd fixed, @smitpatel no problem.

**Pull request merged**
