### PR TITLE
Test new sqlite3mc SQLitePCLRaw bundle

### PR DESCRIPTION
**Pull request by bricelam**

### CODE REVIEW

**Review by AndriySvyryd — APPROVED** [review]

**Comment by bricelam** [comment]
@roji It looks like there's a regression in SQLite here. The PrimitiveCollectionsQuerySqliteTest.Parameter_collection_Concat_column_collection test is now failing. Our query hasn't changed, but the result has.

```sql
.param set @__ints_0 '[11,111]'

SELECT "p"."Id", "p"."Bool", "p"."Bools", "p"."DateTime", "p"."DateTimes", "p"."Enum", "p"."Enums", "p"."Int", "p"."Ints", "p"."NullableInt", "p"."NullableInts", "p"."NullableString", "p"."NullableStrings", "p"."String", "p"."Strings"
FROM "PrimitiveCollectionsEntity" AS "p"
WHERE (
    SELECT COUNT(*)
    FROM (
        SELECT "i"."value"
        FROM json_each(@__ints_0) AS "i"
        UNION ALL
        SELECT "i0"."value"
        FROM json_each("p"."Ints") AS "i0"
    ) AS "t") = 2
```

**Comment by bricelam** [comment]
It has something to do with the UNION ALL. It's causing all the counts to be 4. The counts for each component of the union are correct when ran separately.

**Comment by bricelam** [comment]
I recommend we file an issue on SQLite and skip the test for now.

**Comment by ajcvickers** [comment]
Replaced by #32562

**Pull request closed without merging**
