### PR TITLE
[5.0.1] Query: Correctly compute ordering to be copied from outer in collection join

### LINKED ISSUE #23211: ArgumentOutOfRangeException for split query with owned types
Query:
```C#
context.Set<Root>()
    .AsSplitQuery()
    .Include(e => e.OptionalChildren)
    .OrderBy(e => e.Id)
    .Single(r => r.AlternateId == Fixture.RootAK);
```

`Root.RequiredSingle` and `Root.RequiredSingleAk` are owned.

>    System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the 
    List`1.get_Item(Int32 index)
    SelectExpression.ApplyCollectionJoin(Int32 collectionIndex, Int32 collectionId, Expression innerShaper, INavigationBase navigation, Type elementType, Boolean splitQuery) line 1480
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 76
    IncludeExpression.VisitChildren(ExpressionVisitor visitor) line 74
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 97
    IncludeExpression.VisitChildren(ExpressionVisitor visitor) line 73
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 97
    IncludeExpression.VisitChildren(ExpressionVisitor visitor) line 73
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 97
    IncludeExpression.VisitChildren(ExpressionVisitor visitor) line 73
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 97
    CollectionJoinApplyingExpressionVisitor.VisitExtension(Expression extensionExpression) line 97
    RelationalQueryTranslationPostprocessor.Process(Expression query) line 45
    QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) line 177
    Database.CompileQuery[TResult](Expression query, Boolean async) line 72
    QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) line 114
    <>c__DisplayClass9_0`1.<Execute>b__0() line 98
    CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) line 78
    QueryCompiler.Execute[TResult](Expression query) line 94
    EntityQueryProvider.Execute[TResult](Expression expression) line 81
    GraphUpdatesTestBase`1.LoadOptionalGraph(DbContext context) line 649

### LINKED ISSUE #23276: Incorrect result when doing owner + include collection + split query + owned type mapped to different table + single
```C#
public class Program
    {
        public static async Task Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database
                db.Add(new Blog
                {
                    Owned = new OwnedType { Value = "A" },
                    Posts = new List<Post>
                    {
                        new Post{Title = "ABC"},
                        new Post{Title = "DEF"},
                    }
                });

                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                var query = db.Blogs.Include(e => e.Posts).AsSplitQuery().OrderBy(e => e.Id).Single();

                Console.WriteLine(query.Posts.Count);
            }
            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory ContextLoggerFactory
            => LoggerFactory.Create(b =>
            {
                b
                .AddConsole()
                .AddFilter("", LogLevel.Debug);
            });

        // Declare DBSets
        public DbSet<Blog> Blogs { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                //.UseCosmos("https://localhost:8081", @"C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==", "_ModelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(ContextLoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
            modelBuilder.Entity<Blog>().OwnsOne(e => e.Owned, b => b.ToTable("Owned"));
        }
    }

    public class Blog
    {
        public int Id { get; set; }
        public OwnedType Owned { get; set; }
        public List<Post> Posts { get; set; }
    }

    [Owned]
    public class OwnedType
    {
        public string Value { get; set; }
    }

    public class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
    }
```
Version 5.0

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #23211
Resolves #23276 

Adding quirk in a separate commit

**Description**

Same root cause results in two bugs:

1. When an entity type has _two or more owned reference types_ which are mapped to _different tables_, then including the collection on such an entity type with a split query throws. Split queries are a new feature in 5.0.
2. When an entity type has an _owned reference type_ mapped to a _different table_ then including the collection in a split query with a _single result_ generates wrong results which can lead to data corruption.

**Customer impact**

Either exception of data corruption when using new split query feature with owned reference types.

**How found**

We found this while adding MQ test coverage for owned types. It has not been customer reported yet, but we believe that customers will hit this when they start using split queries (which is expected to get very high adoption) and may suffer data corruption.

**Test coverage**

This PR includes test for the affected scenario. A more thorough testing is being added in #23212

**Regression?**

No, split query was added in 5.0 only

**Risk**

Low. The fix only expands scope of pattern match so previously working queries would continue working.

### CODE REVIEW

**Review by maumar — APPROVED** [review]

**Comment by ajcvickers** [comment]
@smitpatel Tactics feedback on, "While adding additional test coverages," is that we should bring this back if we have customer reports. If we are very confident that this is something we should fix even without customer reports, then we should make the case for that. Either way we can bring back to tactics when we have more info.

**Comment by smitpatel** [comment]
According to #23276  this is causing incorrect results to customer which will corrupt database without noticing. Let's discuss in triage. I am also fine waiting for a customer to hit the issue.

**Comment by ajcvickers** [comment]
Approved by Tactics for 5.0.1. However, we should loop back with Tactics once we have customer reports on this to confirm this was the correct choice.

**Comment by smitpatel** [comment]
@msftbot merge this after 1 hour

**Comment by smarts** [comment]
Are there any limitations to this fix, like a certain depth in the object graph?
I have an EF configuration that is still producing the error from #23311.
I'm on an EF Core version that should have this fix, `5.0.6`

**Comment by smitpatel** [comment]
@smarts - There are no limitations to this fix. Though the error msg which arises from this bug is generic and can happen in other totally different scenarios too. Please file a new issue with repro code so that we can investigate.

**Pull request merged**
