### PR TITLE
Move to ubuntu22.04

### LINKED ISSUE #28739: Move to next ubuntu
Build shows warning that 18.04 is deprecated.

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #28739

### CODE REVIEW

**Comment by smitpatel** [comment]
We may also need to backport this eventually to previous release branches depending on when they are fully deprecated and becomes unavailable and how long we are servicing patch branches.

**Review by roji — APPROVED** [review]

**Comment by roji** [comment]
I'd consider backporting this now, to get it over with...

**Comment by ajcvickers** [comment]
@dougbu @wtgodbe Any issues with us backporting this to 6.0 and/or 3.1?

**Comment by wtgodbe** [comment]
Not from my point of view (if it works), we did the same in aspnetcore

**Comment by dougbu** [comment]
@smitpatel where are you on backporting to 2.1 and so on❔

**Comment by smitpatel** [comment]
Created PRs for 3.1/6/7. 2.1 uses Linux agent and the ubuntu is figured out based on arcade code inside "/eng" directory. I think that when arcade moves forward those files will update and automatically moves to next ubuntu for that branch.

**Comment by dougbu** [comment]
Thanks for the new PRs @smitpatel

> 2.1 uses Linux agent and the ubuntu is figured out based on arcade code inside "/eng" directory. I think that when arcade moves forward those files will update and automatically moves to next ubuntu for that branch.

Arcade isn't available for 2.1, just 3.1 and later. https://github.com/dotnet/efcore/blob/release/2.1/build/templates/default-build.yml is local to this repo and either

1. We disable non-Windows builds, as has been done in dotnet/aspnetcore and dotnet/extensions for 2.1.x. (This is my preferred option.)
2. We update the default-build YAML to use 20.04.

**Comment by smitpatel** [comment]
@ajcvickers - Pick an option. 🤔

**Comment by ajcvickers** [comment]
1

**Pull request merged**
