### PR TITLE
Update to SQLitePCLRaw 2.0.4

### LINKED ISSUE #22198: Update 5.0 dependencies
- [x] @AndriySvyryd Downgrade Azure.Cosmos to Microsoft.Azure.Cosmos 3.12.0
- [x] @bricelam Upgrade Microsoft.Data.SqlClient to 2.0.1 [when available](https://github.com/dotnet/SqlClient/milestone/17?closed=1)
- [ ] @bricelam Upgrade SQLitePCLRaw to 2.0.4 [when available](https://github.com/ericsink/SQLitePCL.raw/issues/356)

### PR DESCRIPTION
**Pull request by bricelam**
/cc @ericsink @Pilchie

Resolves #22198

### CODE REVIEW

**Comment by Pilchie** [comment]
How confident are we that a non-prerelease version will be out in time for us to adopt it?  We can't ship 5.0 final with a pre-release dependency.

**Comment by ericsink** [comment]
"How confident are we"

Very confident.

**Comment by Pilchie** [comment]
Should we just wait for that then?

**Comment by ericsink** [comment]
I'll decline to give any advice on your process.  :-)  But for additional background:

The main purpose of this 2.0.4-pre is to let @bricelam verify that certain changes in my 2.0.4 work are working as expected.  If he gives the thumbs-up on this -pre, I expect to do 2.0.4 final next week.  If he finds a problem, I still expect to be able to fix it and do 2.0.4 final next week.  I suspect that this PR is simply Brice's most convenient way to do the verification I just mentioned.

**Comment by bricelam** [comment]
LGTM. Just a few test issues to fix. No product issues found. The new bundle_sqlite3 works like a charm on our macOS and Linux (Ubuntu) agents. We can wait for the final 2.0.4 release. I'll get this PR passing and we can just update it when the package is available.

**Comment by Pilchie** [comment]
Sounds great.  Thanks @bricelam

**Pull request merged**
