### PR TITLE
Added DbUpdateException constructors that accept list of EntityEntry for Entries property

### PR DESCRIPTION
**Pull request by Giorgi**
Implements #24146

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24147) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24147) before we can accept your contribution.<br/><br/>:x: Giorgi [sign now](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24147)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/efcore?pullRequest=24147) it.</sub>

**Comment by Giorgi** [comment]
The new constructor should filter entities by state too but I'll wait for the review before making that change.

**Comment by ajcvickers** [comment]
@Giorgi This looks good to me. I don't think the constructor should do any filtering; I think the caller should filter before calling the constructor.

Can you add some simple unit tests in [ExceptionTest.cs](https://github.com/dotnet/efcore/blob/main/test/EFCore.Tests/ExceptionTest.cs)? Just test that calling the constructor results in the `Entries` property returning the passed in entries.

**Comment by Giorgi** [comment]
@ajcvickers Done

**Review by ajcvickers — APPROVED** [review]

**Comment by ajcvickers** [comment]
@Giorgi Thanks!

**Comment by Giorgi** [comment]
@ajcvickers Any chance to see this change in the 5.X version?

**Comment by roji** [comment]
@Giorgi yeah, once a version has been released (5.0), we only patch for bugs, and not new features or APIs (and even for bugs, they need to be low-risk and relatively severe).

**Pull request merged**
