### PR TITLE
Avoid infinite recursive generics (Fixes #20393)

### LINKED ISSUE #20393: Infinite generic expansions cause efcore perform poorly with AOT compilation
## Infinite generic expansions cause efcore perform poorly with AOT compilation

Original issue in CoreRT see https://github.com/dotnet/corert/issues/8052

Both `ExecuteImplementation` and `ExecuteImplementationAsync` call themselves with different generic arguments and lead to infinite generic expansions, which make efcore impossible to be AOT compiled.

Source:
https://github.com/dotnet/efcore/blob/master/src/EFCore/Storage/ExecutionStrategy.cs#L183
and
https://github.com/dotnet/efcore/blob/master/src/EFCore/Storage/ExecutionStrategy.cs#L276

Above recursive calls should be removed.

### PR DESCRIPTION
**Pull request by hez2010**
Avoid infinite recursive generics

- [x] The code builds and tests pass (verified by our automated build checks)
- [x] Commit messages follow this format
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code meets the expectations our engineering guidelines.
      https://github.com/dotnet/aspnetcore/wiki/Engineering-guidelines

Fixes #20393

Also I think this fix can be backport to branch release/3.1

### CODE REVIEW

**Comment by ajcvickers** [comment]
@hez2010 Thanks for the PR. Given that this is a perf issue, can you show the testing you did to ensure that the perf after the change is better than the perf before the change?

Also, it's extremely unlikely that this will be ported to 3.1.x. See [release planning](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for details on how we decide which issues to patch.

**Comment by hez2010** [comment]
Before:
|                Method |     Mean |     Error |    StdDev |
|---------------------- |---------:|----------:|----------:|
| TestExecutionStrategy | 2.149 us | 0.0363 us | 0.0322 us |

After:
|                Method |     Mean |     Error |    StdDev |
|---------------------- |---------:|----------:|----------:|
| TestExecutionStrategy | 2.087 us | 0.0314 us | 0.0278 us |

**Comment by ajcvickers** [comment]
@hez2010 We discussed this and came to the following conclusions:
* The new code is less maintainable than the original code
* Currently measured perf improvements are marginal
* If AOT changes these perf characteristics, then we need to see those numbers
  * If this means the AOT code needs to updated not to throw before we can get these numbers, then we are happy to wait.

**Comment by AndriySvyryd** [comment]
Closing this PR as this isn't the way we plan to resolve the issue

**Comment by darkguy2008** [comment]
@AndriySvyryd sorry to chip in, but what's the way to solve the issue then?

I'm currently facing the issue mentioned above ( https://github.com/dotnet/runtimelab/issues/283 ) where there isn't a performance or even binary size issue as @hez2010 states. A simple project just doesn't compile, so IMHO the code doesn't look that bad either (and I have rarely worked with Core's source code, go figure). I agree that it can be refactored, as it repeats, but it's a fix to a big problem because any project that includes EFCore and tries to compile with CoreRT just doesn't even build as the process gets stuck in an infinite stackoverflow exception (under Linux) and then crashes (under Windows).

I would've been even more worried if there wasn't a fix, but the fix is here... and it was **rejected** ?? This just doesn't make any sense. What would be the _proper_ way to fix this, then? It's an error, a known error, and there's a proposed fix. Maybe even accepting it and then refactoring the code could've been a better idea, I guess.

**Comment by roji** [comment]
@darkguy2008 I haven't reviewed this PR, but I can only say that I do intend to look at this and probably remove instances of infinite recursive generics in EF for 6.0 (unfortunately there was no time to look into this for 5.0). This isn't a comment on this specific PR and what it does to get rid of the infinite recursion.

**Comment by AndriySvyryd** [comment]
A better way of fixing the issue would be to change the signature of `ExecuteImplementation` in a way that allows recursive calls to be made using the same generic arguments

**Pull request closed without merging**
