### PR TITLE
[release/6.0] Store ApplicationServiceProvider in a WeakReference

### LINKED ISSUE #27169: ServiceProviderCache keeps initially created IServiceProvider indefinitely
The `ServiceProviderCache` uses instances of `IDbContextOptions` as keys for the internal `ConcurrentDictionary`.  A key of type `IDbContextOptions` contains, among other things, the extension `CoreOptionsExtension` which has an `_applicationServiceProvider`.

After creation and disposal of the first `DbContext` the `ServiceProviderCache` keeps the `IDbContextOptions` incl. the (disposed) `IServiceProvider`, which keeps all `IDisposable` instances in it. One of the disposables is the `DbContext` itself.

The result is that the reference `_applicationServiceProvider` prevents GC to reclaim the memory.

image

### Repro

**Program.cs**
```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.Extensions.DependencyInjection;

var rootServiceProvider = new ServiceCollection()
                          .AddDbContext<DemoDbContext>(builder =>
                                 builder.UseSqlServer("server=localhost;database=demo;integrated security=true"))
                          .BuildServiceProvider();

CreateAndDisposeContext(rootServiceProvider);

var cache = ServiceProviderCache.Instance;

static void CreateAndDisposeContext(IServiceProvider rootServiceProvider)
{
   using var scope = rootServiceProvider.CreateScope();

   scope.ServiceProvider.GetRequiredService<DemoDbContext>();
}


public class DemoDbContext : DbContext
{
   public DemoDbContext(DbContextOptions<DemoDbContext> options)
      : base(options)
   {
   }
}

```

**csproj file**

```xml
<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>net6.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
   </PropertyGroup>

   <ItemGroup>
     <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.1" />
   </ItemGroup>

</Project>
```

### Provider and version information

EF Core version: 6.0.1
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET 6.0
Operating system: Windows 10 x64
IDE: Rider 2021.3.2

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #27169

**Description**

In 6.0 we made a change to `ServiceProviderCache` to use instances of `IDbContextOptions` as keys for the internal `ConcurrentDictionary`.  A key of type `IDbContextOptions` contains, among other things, the extension `CoreOptionsExtension` which has an `ApplicationServiceProvider` reference pointing to the service provider that was used to create the options.

After creation and disposal of the first `DbContext` the `ServiceProviderCache` keeps the `IDbContextOptions` incl. the (disposed) service provider scope, which still references all disposed scoped services, including the `DbContext` itself.

**Customer impact**

The first service provider scope per each DbContext type used in the application will never be garbage collected.

**How found**

Customer reported on 6.0.1

**Regression**

Yes. Regressed by #25313

**Testing**

Verified manually.

**Risk**

Low. This reverts the behavior to 5.0 wrt referencing `ApplicationServiceProvider` from `ServiceProviderCache`

### CODE REVIEW

**Comment by ajcvickers** [comment]
@AndriySvyryd Couldn't the `IMemoryCache` also cause the same issue?

**Comment by roji** [comment]
Is there a danger of the application service provider being collected too early under memory pressure, though it may still be needed? (I don't this area too well)

Given that DbContextOptions is already immutable and that OptionsExtensions can be cloned, would it be simpler/safer to just put a cloned copy of DbContextOptions in the ConcurrentDictionary, where the service provider has been nulled out?

**Comment by ajcvickers** [comment]
> Is there a danger of the application service provider being collected too early under memory pressure, though it may still be needed? (I don't this area too well)

No, because if anything else has a reference to it, then it won't be GC'ed. But if this is the only reference, then it can be GC'ed.

> Given that DbContextOptions is already immutable and that OptionsExtensions can be cloned, would it be simpler/safer to just put a cloned copy of DbContextOptions in the ConcurrentDictionary, where the service provider has been nulled out?

I think it's worth exploring this.

**Comment by AndriySvyryd** [comment]
> @AndriySvyryd Couldn't the `IMemoryCache` also cause the same issue?

We don't store services in `IMemoryCache` and since it's a singleton we don't support it being disposed.

**Review by ajcvickers — APPROVED** [review]

**Pull request merged**
