### PR TITLE
Use C# 11 raw SQL literals for all SQL baselines

### PR DESCRIPTION
**Pull request by roji**
This is a test-only change. Since it affects so many files, we want to get this into 7.0 to avoid merge conflicts when later backporting patches.

The massive baseline changes are in a separate commit from baseline management changes for easier reviewing.

Part of #28260

### CODE REVIEW

**Review by AndriySvyryd — APPROVED** [review]

**Comment by ajcvickers** [comment]
@roji FYI, I checkout out your branch and all tests passed locally. Let's see if the infra issues get fixed, but if not we might want to just merge.

**Comment by roji** [comment]
@ajcvickers the failures were actually my fault, a connection string change to config.json accidentally slipped in...

**Pull request merged**
