### PR TITLE
Clean up build configuration

### PR DESCRIPTION
**Pull request by mmitche**
- Remove unneeded .NET 6 feeds
- Remove obselete publishing options
- Remove unused variables
- Fix internal build urls.

### CODE REVIEW

**Comment by mmitche** [comment]
Official build test: https://dev.azure.com/dnceng/internal/_build/results?buildId=1935497&view=results

**Review by AndriySvyryd — APPROVED** [review]

**Comment by mmitche** [comment]
Also noticed that Linux is broken in main: https://dev.azure.com/dnceng/internal/_build/results?buildId=1934585&view=results

**Comment by AndriySvyryd** [comment]
> Also noticed that Linux is broken in main: [dev.azure.com/dnceng/internal/_build/results?buildId=1934585&view=results](https://dev.azure.com/dnceng/internal/_build/results?buildId=1934585&view=results)

It's already fixed

**Pull request merged**
