### PR TITLE
Stop using AddFromFile with many files

### LINKED ISSUE #24933: Don't use AddFromFile() in Scaffold-DbContext
It's really slow in new-style csproj

### PR DESCRIPTION
**Pull request by ErikEJ**
("really slow" on SDK style .csproj)

fixes #24933

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
@bricelam Do you think we'll need to add a note in the docs for non-SDK projects to add the files manually?

**Comment by ErikEJ** [comment]
EF Core 6 will only support .net 5/6 - but this file is global, and also works for 3.1??

**Comment by bricelam** [comment]
@AndriySvyryd We already skip `ProjectItem.Remove()` when it's not needed (for different reasons), so I just intended to copy that code:

https://github.com/dotnet/efcore/blob/b2fc11931a74ca2fcea070df96fb7126373f6a84/src/EFCore.Tools/tools/EntityFrameworkCore.psm1#L355-L362

**Comment by bricelam** [comment]
We might as well do it for Add-Migration too

**Comment by bricelam** [comment]
> EF Core 6 will only support .net 5/6 - but this file is global, and also works for 3.1??

Correct, you can use the 6.0 tools with 2.1 projects. This can happen when you have a solution with both an EF Core 6 and EF Core 2.1/3.1 project.

**Comment by ErikEJ** [comment]
I can update for Add-Migration?

**Review by bricelam — APPROVED** [review]

**Comment by ErikEJ** [comment]
@ajcvickers I don't want to nitpick, but I think you forgot to label this "community contribution"

**Comment by ajcvickers** [comment]
@ErikEJ I'm way behind with this...

**Comment by ronaldhoek** [comment]
This speaks about 'conditionally' adding the created script files (in the past I already noticed, that remove-migration would not remove the file from the project - so might that also be related).

But based on what/which _condition(s)_?

**Pull request merged**
