### PR TITLE
Switch TFM from netcoreapp5.0 to net5.0

### PR DESCRIPTION
**Pull request by roji**
Certain other IDEs seem to support it just fine.

### CODE REVIEW

**Comment by ErikEJ** [comment]
What IDEs will have issues with this change?

**Comment by roji** [comment]
@ErikEJ that's the good thing - apparently none!

**Comment by bricelam** [comment]
Missed one:

https://github.com/dotnet/efcore/blob/7840f8b01fa92d9ddd522866216165eb55284540/eng/helix.proj#L36

**Comment by roji** [comment]
That must explain the pesky Helix failure...

**Comment by roji** [comment]
PS Is it right that we have `<XUnitRuntimeTargetFramework>netcoreapp2.0</XUnitRuntimeTargetFramework>` in helix.proj?

**Comment by ajcvickers** [comment]
Discussed in triage; no need for this since it is testing only.

**Comment by bricelam** [comment]
> Is it right that we have <XUnitRuntimeTargetFramework>netcoreapp2.0</XUnitRuntimeTargetFramework> in helix.proj?

@smitpatel might know what in the world that line does. I've wondered myself.

**Comment by smitpatel** [comment]
Quoting from https://github.com/dotnet/arcade/issues/4839#issuecomment-585967306

> Ah, yeah, I know the issue here. There is no xunit runner for netcoreapp3.0+. You'll need to define those variables separately: XUnitPublishTargetFramework needs to be netcoreapp3.1 and XUnitRuntimeTargetFramework needs to be netcoreapp2.0. The old xunit runner should still work for your tests.

**Pull request closed without merging**
