### PR TITLE
Cosmos: Add translator for Substring method which map to SUBSTRING built-in functions

### PR DESCRIPTION
**Pull request by Marusyk**
Add translator for `string.Substring()`

Issue #16143

Please review.
Thank you in advance

### CODE REVIEW

**Review by roji — COMMENTED** [review]
Thanks for all these translation contributions @Marusyk?

Can you please try enabling NorthwindWhereQueryCosmosTest.Where_string_substring as well? Note that there are other skipped tests for Trim/TrimStart/TrimEnd in NorthwindFunctionsQueryCosmosTest, can you please check those too?

Finally, if you intending to submit more string translations, may I suggest submitting them in a single PR rather than a PR-per-translations? This simplifies the review process and the general project history.

**Comment by Marusyk** [comment]
> Thanks for all these translation contributions @Marusyk!
Not at all, because I need this for my work

> Finally, if you intending to submit more string translations, may I suggest submitting them in a single PR rather than a PR-per-translation? This simplifies the review process and the general project history.

@roji, I will but, I do it in my spare time, so, when I have time to add more than one translation, then I will do it within one PR. But when I have time to add only one translation, I don't see a problem in doing it within different PRs.
Or do you suggest not submit more PRs until I make all the string translations?

Translations are separate parts of the functionality that are not dependent on each other in most cases. Could you explain how this can affect the general history of the project?

**Comment by Marusyk** [comment]
> Note that there are other skipped tests for Trim/TrimStart/TrimEnd in NorthwindFunctionsQueryCosmosTest, can you please check those too?

All of them is not relevant because Cosmos DB TRIM/LTRIM/RTRIM does not take arguments.

https://github.com/dotnet/efcore/blob/1da7f89647d9006fb57d4d29f8da6573307ea072/src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs#L138-L160

image

**Review by maumar — APPROVED** [review]

**Comment by maumar** [comment]
@Marusyk thank you for the contribution!

**Pull request merged**
