### PR TITLE
Attempt to fix 32154

### PR DESCRIPTION
**Pull request by maumar**

### CODE REVIEW

**Comment by maumar** [comment]
@ajcvickers  can you test this one your machine?

**Review by FirdavsAsadov — APPROVED** [review]

**Comment by ajcvickers** [comment]
@maumar Sorry for not getting to this sooner. Could you resolve the merge conflicts with main, and then I'll give it a try?

**Comment by ajcvickers** [comment]
@maumar Still seeing a failure. Let's find some time to look at this together so we can try things on my machine.

```
✘ Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlServerTest.Add_sparse_column_to_temporal_table
Microsoft.Data.SqlClient.SqlException : Cannot alter table 'HistoryTable' because the table either contains sparse columns or a column set column which are incompatible with compression.
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken) in C:\local\code\efcore\src\EFCore.Relational\Storage\RelationalCommand.cs:line 204
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken) in C:\local\code\efcore\src\EFCore.Relational\Storage\RelationalCommand.cs:line 268
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken) in C:\local\code\efcore\src\EFCore.Relational\Storage\RelationalCommand.cs:line 273
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken) in C:\local\code\efcore\src\EFCore.Relational\Migrations\Internal\MigrationCommandExecutor.cs:line 122
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken) in C:\local\code\efcore\src\EFCore.Relational\Migrations\Internal\MigrationCommandExecutor.cs:line 137
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken) in C:\local\code\efcore\src\EFCore.Relational\Migrations\Internal\MigrationCommandExecutor.cs:line 142
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken) in C:\local\code\efcore\src\EFCore.Relational\Migrations\Internal\MigrationCommandExecutor.cs:line 147
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsTestBase`1.Test(IModel sourceModel, IModel targetModel, IReadOnlyList`1 operations, Action`1 asserter, MigrationsSqlGenerationOptions migrationsSqlGenerationOptions) in C:\local\code\efcore\test\EFCore.Relational.Specification.Tests\Migrations\MigrationsTestBase.cs:line 2033
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlServerTest.Add_sparse_column_to_temporal_table() in C:\local\code\efcore\test\EFCore.SqlServer.FunctionalTests\Migrations\MigrationsSqlServerTest.cs:line 6733
--- End of stack trace from previous location ---
```

**Comment by maumar** [comment]
@ajcvickers I updated the code a bit, now also dropping versioning when converting non-sparse column to sparse, but from the exception you posted above, it looks like adding sparse column breaks (which was already trying to drop periods).

Can you try those 3 things and at each step check the compression level of table/history table? (in ssms right click on table -> properties -> storage -> compression type).

step 1 - create non-temporal table:

```sql
CREATE TABLE [Customers] (
    [Id] int NOT NULL IDENTITY,
    [MyColumn] int NULL,
    CONSTRAINT [PK_Customers] PRIMARY KEY ([Id])
);
```

step 2 - convert table to temporal:

```sql
ALTER TABLE [Customers] ADD [End] datetime2 NOT NULL DEFAULT '9999-12-31T23:59:59.9999999';
ALTER TABLE [Customers] ADD [Start] datetime2 NOT NULL DEFAULT '0001-01-01T00:00:00.0000000';
ALTER TABLE [Customers] ADD PERIOD FOR SYSTEM_TIME ([Start], [End])
ALTER TABLE [Customers] ALTER COLUMN [Start] ADD HIDDEN
ALTER TABLE [Customers] ALTER COLUMN [End] ADD HIDDEN
DECLARE @historyTableSchema sysname = SCHEMA_NAME()
EXEC(N'ALTER TABLE [Customers] SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [' + @historyTableSchema + '].[HistoryTable]))')
```

step3 - convert it back to non-temporal (we should have 2 tables now):
```sql
ALTER TABLE [Customers] SET (SYSTEM_VERSIONING = OFF)
ALTER TABLE [Customers] DROP PERIOD FOR SYSTEM_TIME
```


my guess is that 
1. normal table is not compressed (because our old tests adding/modifying sparse column on regular table work).
2. converting to temporal compresses history table as hinted here: https://learn.microsoft.com/en-us/sql/relational-databases/tables/changing-the-schema-of-a-system-versioned-temporal-table?view=sql-server-ver16&redirectedfrom=MSDN#important-remarks
3. when we disable versioning, sql sever doesn't revert compression to the regular table default

If that's the case it seems like a bug to me, but maybe something else is going on.

**Comment by ajcvickers** [comment]
Step 1:

Compression type: None

Step 2:

```
Msg 4924, Level 16, State 5, Line 3
ADD PERIOD FOR SYSTEM_TIME failed because column 'Start' does not exist in table 'Customers'.

Completion time: 2023-11-20T12:05:10.1477817+00:00
```

image

**Comment by maumar** [comment]
@ajcvickers  try running the command in these batches:

1:
```sql
ALTER TABLE [Customers] ADD [End] datetime2 NOT NULL DEFAULT '9999-12-31T23:59:59.9999999';
ALTER TABLE [Customers] ADD [Start] datetime2 NOT NULL DEFAULT '0001-01-01T00:00:00.0000000';
```

2:
```sql
ALTER TABLE [Customers] ADD PERIOD FOR SYSTEM_TIME ([Start], [End])
```

3:
```sql
ALTER TABLE [Customers] ALTER COLUMN [Start] ADD HIDDEN
ALTER TABLE [Customers] ALTER COLUMN [End] ADD HIDDEN
```

3:

```sql
DECLARE @historyTableSchema sysname = SCHEMA_NAME()
EXEC(N'ALTER TABLE [Customers] SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [' + @historyTableSchema + '].[HistoryTable]))')
```

**Comment by ajcvickers** [comment]
@maumar

- After step 1: Customers: None; History: N/A
- After step 2: Customers: None; History: Page
- After step 3: Customers: None; History: Page

**Comment by maumar** [comment]
@ajcvickers can you also try steps 1 and 2, but for step one the table is this:

```sql
CREATE TABLE [Customers] (
    [Id] int NOT NULL IDENTITY,
    [MyColumn] int SPARSE NULL,
    CONSTRAINT [PK_Customers] PRIMARY KEY ([Id])
);
```

**Comment by ajcvickers** [comment]
@maumar On that table, compression type is None for both the Customers and the history table at the end of step 2.

**Comment by maumar** [comment]
closing in favor of https://github.com/dotnet/efcore/issues/32154

**Pull request closed without merging**
