### PR TITLE
Add parentheses around SQL IS NULL (7.0)

### LINKED ISSUE #29222: EF Core 7 RC produces different translation from EF Core 6 (VB/sqlite)
I have the following LINQ query in my VB code:

            Dim testq = From cf In dbContxt.Cashflows
                        Where cf.Date >= #4/1/2022# And cf.Deposit IsNot Nothing
                        Select cf.Date

It produced the following SQL in EF Core 6.0 (using testq.ToQueryString()):

SELECT "c"."Date" 
FROM "Cashflows" AS "c"
WHERE ("c"."Date" >= '2022-04-01 00:00:00') & ("c"."Deposit" IS NOT NULL)

In EF Core 7.0, I am getting a different result, which changes the order of operations of the query:

SELECT "c"."Date" 
FROM "Cashflows" AS "c"
WHERE ("c"."Date" >= '2022-04-01 00:00:00') & "c"."Deposit" IS NOT NULL

Note that if I change the query to:

            Dim testq = From cf In dbContxt.Cashflows
                        Where cf.Date >= #4/1/2022# AndAlso cf.Deposit IsNot Nothing
                        Select cf.Date

I get:

SELECT "c"."Date" 
FROM "Cashflows" AS "c"
WHERE "c"."Date" >= '2022-04-01 00:00:00' AND "c"."Deposit" IS NOT NULL

This works around the issue, giving me the same results I got in EF Core 6.0

Thanks!

EF Core version: 7.0 RC.1.22426.7
Database provider: Microsoft.EntityFrameworkCore.Sqlite.Core
Target framework:  .NET 6.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.3.4

### PR DESCRIPTION
**Pull request by roji**
Fixes #29222

### CODE REVIEW

**Comment by roji** [comment]
Uh, why no checks?

**Comment by ErikEJ** [comment]
72 files changed??

**Comment by roji** [comment]
> 72 files changed??

Yes, test only. The actual product code change is very trivial.

**Review by ajcvickers — APPROVED** [review]

**Pull request merged**
