### PR TITLE
Query: Cleanup in language processing

### PR DESCRIPTION
**Pull request by smitpatel**

### CODE REVIEW

**Comment by maumar** [comment]
@roji

**Comment by roji** [comment]
This removes the simplification from `string.Compare(a, b) == 0` to `a == b` (and the correspond case-insensitive simplification as well). If seems more conducive to working together to first finish explaining why this is necessary before doing this (conversation in #16092).

**Comment by smitpatel** [comment]
I replied to #16092. It needs to be fixed for perf anyway since this simplification did not solve anything for C#. This creates additional code to maintain which is covered by other issue anyway.

**Comment by smitpatel** [comment]
@ajcvickers - I need sign-off for this PR.

**Pull request merged**
