### PR TITLE
Update .Sources package reference

### PR DESCRIPTION
**Pull request by wtgodbe**
In official builds, this version should match the repo version

### CODE REVIEW

**Review by halter73 — APPROVED** [review]

**Comment by AndriySvyryd** [comment]
This needs https://github.com/dotnet/efcore/pull/34035 and a new? korebuild

**Comment by wtgodbe** [comment]
Updated to MacOS 13. The korebuild thing is known flakiness, it usually works on retry (this repo as the same version as aspnetcore & extensions)

**Comment by AndriySvyryd** [comment]
Is korebuild still supported? Any chance this flakiness can be fixed?

Moving to arcade would "fix" it. But that would be about a dev-month of work right?

**Comment by wtgodbe** [comment]
It's very likely that we're done making "real" changes in this repo for the foreseeable future, and its official build happens as a submodule in aspnetcore, where any issues would be caught. Given that, I don't think it's worth doing any investment to fix CI here, as any future changes can just be merged on red.

**Review by AndriySvyryd — APPROVED** [review]

**Pull request merged**
