### PR TITLE
[Release/5.0]Fix ValueGenerated, make ValueGeneratedOnUpdate() and ValueGeneratedOnAddOrUpdate() working

### PR DESCRIPTION
**Pull request by eation**
Fixes [#6999](https://github.com/dotnet/efcore/issues/6999) and [#19765](https://github.com/dotnet/efcore/issues/19765)

When useing **ValueGeneratedOnUpdate()**, set **PropertyBuilder.Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Save)** for update.

When useing **ValueGeneratedOnAddOrUpdate()**, set **PropertyBuilder.Metadata.SetBeforeSaveBehavior(PropertySaveBehavior.Save)** for add and **PropertyBuilder.Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Save)** for update.

### CODE REVIEW

**Comment by ajcvickers** [comment]
@eation I haven't looked at your code, but any enhancement will need to be made against the "main" branch before it can be properly considered. We don't patch previous releases with new enhancements. See the [Release planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for more information.

**Comment by eation** [comment]
@ajcvickers Maybe it wasn't an enhancement , like [5.0 breaking-changes](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#non-added-generation) say that when entity state is changed, it will call Value Generators. this just make a design that already exisits to working, no a new change or a new design.
i'm building and testing "Main" locally, and testing it in a dev product. I need time to switch this code to "Main".

**Comment by eation** [comment]
These codes can also be used and working on 6.0

**Comment by ajcvickers** [comment]
@eation You will need to create a PR against main.

**Comment by eation** [comment]
Created new PR

**Pull request closed without merging**
