### PR TITLE
Soft deletes

### PR DESCRIPTION
**Pull request by AshkanAbd**
Hi there, I try to implement soft deleting to EfCore with deleting entities with their user defined relations please check commit message for more details. I use this implementation in my projects to handle soft delete and force delete records, today I decide to fork EfCore repo and add this useful feature to EfCore source in SoftDelete branch. 
Please also check readme.md file in SoftDelete branch for a quick usage of this feature.  
I hope you like it.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=21524) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=21524) before we can accept your contribution.<br/><br/>:x: AshkanAbd [sign now](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=21524)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/efcore?pullRequest=21524) it.</sub>

**Comment by ajcvickers** [comment]
@AshkanAbd It doesn't look like this is something we will take as-is. If you want to implement soft deletes, then please start by writing a design proposal on #19695 that describes the approach you wish to take, how it interacts with the other parts of EF, and what the application-facing experience will be.

**Comment by AshkanAbd** [comment]
@ajcvickers I'll fix failed tests and a sample project for this type of implementation of soft deletes and try to explain how It works with other part of EfCore. I think it's a good start point.

**Comment by ajcvickers** [comment]
@AshkanAbd I would strongly suggest writing a design proposal before working any more on this PR.

**Comment by ajcvickers** [comment]
Closing this as this implementation is now in a NuGet package and referenced from the extensions docs.

**Pull request closed without merging**
