### PR TITLE
Minor model building perf improvements

### PR DESCRIPTION
**Pull request by AndriySvyryd**

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
@Pilchie For RC1

**Comment by Pilchie** [comment]
Approved for RC1.

**Comment by Saibamen** [comment]
Do you have any before/after benchmarks?

**Comment by AndriySvyryd** [comment]
@Saibamen Sorry, I didn't save them or the model I was using. It was around 1-2% for a model with over 1500 entity types

https://github.com/dotnet/efcore/pull/22314 was actually the big win with around 10% improvement

**Pull request merged**
