### PR TITLE
Merge changes and update SDK

### PR DESCRIPTION
**Pull request by JunTaoLuo**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Once this is in, please update the submodule as part of dotnet/aspnetcore#30056

**Comment by dougbu** [comment]
Not sure which feed should be updated to contain latest from aspnet/BuildTools but unable to download
``` text
KoreBuild korebuild.2.1.7-build-20210209.2
```

**Comment by JunTaoLuo** [comment]
Yea, I didn't copy in the right version, I just updated the PR 😄

**Comment by dougbu** [comment]
> Not sure which feed should be updated&hellip;

Never mind, I missed the typo

**Comment by JunTaoLuo** [comment]
Hmm I'm only allowed to squash and merge? But I don't want to squash...

**Comment by dougbu** [comment]
@JunTaoLuo `git push origin HEAD:release/2.1` from your local johluo/2.1.26 branch

**Comment by JunTaoLuo** [comment]
Hmm it's weird that without `HEAD:` it didn't work:
```
C:\gh\efcore [release/2.1 ↑]> git push origin release/2.1
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 233 bytes | 116.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/release/2.1.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:dotnet/efcore
 ! [remote rejected]     release/2.1 -> release/2.1 (protected branch hook declined)
error: failed to push some refs to 'git@github.com:dotnet/efcore'
```

but with it, the command worked. I thought `HEAD:` was implicit

**Pull request merged**
