### PR TITLE
Use new Hosted build pools

### PR DESCRIPTION
**Pull request by ulisesh**
We are transitioning all servicing build to a new set of pools

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [ ] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [ ] The code builds and tests pass locally (also verified by our automated build checks)
- [ ] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

### CODE REVIEW

**Review by smitpatel — APPROVED** [review]
LGTM. Tagging @dotnet/aspnet-build 

Also may need to do the same update in https://github.com/dotnet/efcore/blob/0ba16959c7c4f38f9162101966a6f863ba707120/azure-pipelines-richnav.yml

**Comment by ulisesh** [comment]
It looks like I don't have enough permissions to merge, @smitpatel could you please merge this PR?

**Comment by TanayParikh** [comment]
I don't have context on this change, going to wait for @dougbu / @wtgodbe to comment/merge.

**Comment by smitpatel** [comment]
Waiting from someone from build team to take a look also. I can merge after approval.

**Comment by TanayParikh** [comment]
> I can merge after approval.

Oh got it, thought you were requesting someone with admin rights to merge 😄

**Review by dougbu — APPROVED** [review]

**Pull request merged**
