### PR TITLE
Tests: Remove MARS fixtures

### PR DESCRIPTION
**Pull request by smitpatel**
Since tests uses retrying execution strategy, MARS is not needed.
The failure I had got which made me add MARS was the race condition which tried to enumerate multiple readers at the same time while buffering.

### CODE REVIEW

**Comment by smitpatel** [comment]
@msftbot Please make sure there are at least one approving review.

**Comment by AndriySvyryd** [comment]
I thought you will fix the race condition, not change the tests :rofl:

**Comment by smitpatel** [comment]
We did that already, https://github.com/dotnet/efcore/pull/21301 
I wonder who approved it. :trollface:

**Comment by smitpatel** [comment]
@Pilchie - bot decided to ignore my PR.

**Comment by Pilchie** [comment]
@msftbot why haven't you merged yet?

**Comment by Pilchie** [comment]
@msftbot please merge in 1 minute

**Comment by Pilchie** [comment]
@msftbot please merge in 1 minute

**Comment by Pilchie** [comment]
@msftbot please merge in 1 minute

**Pull request merged**
