### PR TITLE
Remove invalid optimization of CASE-WHEN expressions

### LINKED ISSUE #33751: Invalid optimization of CASE-WHEN expressions
The `SqlExpressionSimplifyingExpressionVisitor` performs an [invalid optimization](https://github.com/dotnet/efcore/blob/v8.0.5/src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs#L203-L218) of `CASE-WHEN` expressions:

```csharp
        // generic CASE statement comparison optimization:
        // (CASE
        //  WHEN condition1 THEN result1
        //  WHEN condition2 THEN result2
        //  WHEN ...
        //  WHEN conditionN THEN resultN) == result1 -> condition1
        if (sqlBinaryExpression.OperatorType == ExpressionType.Equal
            && sqlConstantComponent?.Value is not null
            && caseComponent is { Operand: null, ElseResult: null })
        {
            var matchingCaseBlock = caseComponent.WhenClauses.FirstOrDefault(wc => sqlConstantComponent.Equals(wc.Result));
            if (matchingCaseBlock != null)
            {
                return Visit(matchingCaseBlock.Test);
            }
        }
```

The simplification has these additional requirements that are currently not being checked:
1. the `sqlConstantComponent?.Value` only appears once in the list of case results
2. the `matchingCaseBlock` is disjoint from all of the previous cases
3. the (omitted) `ELSE` is never reached, aka at least one of the conditions holds

An example program that showcases the bug (and can be conveniently run on https://dotnetfiddle.net/ ;) ) is:

```C#
using System;
using System.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;

using var db = new BloggingContext();

db.Database.EnsureDeleted();
db.Database.EnsureCreated();

db.Blogs
    .Where(x => db.Cases(
        x.Url == "http://efcore/", 3,
        x.Url.StartsWith("http://"), 2,
        x.Url.EndsWith("/"), 3
    ) >= 3)
    .ToList();

db.Blogs
    .Where(x => db.Cases(
        x.Url == "http://efcore/", 3,
        x.Url.StartsWith("http://"), 2,
        x.Url.EndsWith("/"), 3
    ) == 3)
    .ToList();

db.Blogs
    .Where(x => db.Cases(
        x.Url == "http://efcore/", 3,
        x.Url.StartsWith("http://"), 2,
        x.Url.EndsWith("/"), 3
    ) == 2)
    .ToList();

public class BloggingContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options
            .LogTo(Console.WriteLine, Microsoft.Extensions.Logging.LogLevel.Information)
            .UseSqlite($"Data Source=test.db");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasDbFunction(typeof(BloggingContext).GetMethod(nameof(Cases))!)
            .HasTranslation(args =>
                new CaseExpression([
                    new CaseWhenClause(args[0], args[1]),
                    new CaseWhenClause(args[2], args[3]),
                    new CaseWhenClause(args[4], args[5]),
                ])
            );
    }

    public int Cases(bool c1, int v1, bool c2, int v2, bool c3, int v3)
        => throw new NotSupportedException();
}

public class Blog
{
    public int BlogId { get; set; }
    public required string Url { get; set; }
}
```

The first query is correctly translated as:
```sql
SELECT "b"."BlogId", "b"."Url"
FROM "Blogs" AS "b"
WHERE CASE
      WHEN "b"."Url" = 'http://efcore/' THEN 3
      WHEN "b"."Url" LIKE 'http://%' THEN 2
      WHEN "b"."Url" LIKE '%/' THEN 3
END >= 3
```

The second query is simplified to
```sql
SELECT "b"."BlogId", "b"."Url"
FROM "Blogs" AS "b"
WHERE "b"."Url" = 'http://efcore/'
```
which misses all of the `Url`s that would match the 3rd-case (example: `https://efcore/`).

The third query is simplified to
```sql
SELECT "b"."BlogId", "b"."Url"
FROM "Blogs" AS "b"
WHERE "b"."Url" LIKE 'http://%'
```
which incorrectly also matches `http://efcore/`.

### Include provider and version information

EF Core version: 8.0.5
Database provider: Microsoft.EntityFrameworkCore.Sqlite
Target framework: .NET 8.0
Operating system: Linux (/WSL)
IDE: Visual Studio Code 1.89.1

EDIT: added condition about `ELSE`/`NULL`

### PR DESCRIPTION
**Pull request by ranma42**
This PR fixes #33751 by removing the invalid optimization.
Additionally, the CompareTo-specific optimization is extended to handle the `CompareTo(x, y) == {-1, 0, 1}` case (which was previously handled by the generic optimization) in order to prevent regressions.

### CODE REVIEW

**Comment by ranma42** [comment]
I need some guidance regarding the tests: are they adequate?
 - I am unsure if I added them to the correct place
 - I added tests for the "complex" case (results can be `TRUE`, `FALSE` or `NULL`), under the assumption that they are mainly checking the values rather than the SQL (which I would assume would be more relevant if the PR added/updated the optimization); the issue was originally detected on a `WHERE` filter, but the optimization can also run in projection contexts, so it should preserve the difference between `FALSE` and `NULL`

**Comment by maumar** [comment]
@ranma42 thanks for doing the work! For the tests, I would suggest to use NullSemantics model (`NullSemanticsQueryFixtureBase`, `NullSemanticsQueryTestBase`) rather than Northwind. Northwind is somewhat special in our tests, given it has particular well-known structure and data, and we try to keep the configuration clean. We do the customization using `ITestModelCustomizer`, but it's probably overkill for this. 

For the tests themselves, I would maybe do one test in select and one in where, so that we test both "simple" and "complex" cases.

**Comment by ranma42** [comment]
I moved the tests to the `NullSemanticsQueryTestBase` and added tests for the simple (WHERE/filter) case.
Note that the tests do not really involve `NULL`s or NULL-related semantics/optimizations.

**Review by maumar — APPROVED** [review]

**Comment by maumar** [comment]
@ranma42 thank you for the contribution!

**Pull request merged**
