### PR TITLE
(RC2) Fix ESCAPE clause for Azure Synapse. (#34463)

### LINKED ISSUE #33555: StartsWith/EndsWith/Contains with parameter fails on Azure Synapse because ESCAPE isn't supported there
I am using Microsoft.EntityFrameworkCore.SqlServer v8.0.4 to run queries against an Azure Synapse SQL database.  The SQL generated for a parameter used as the pattern for StartsWith/EndsWith/Contains automagically gets rewritten to escape any wildchars.

However, the LIKE keyword's `ESCAPE` clause syntax is not supported by Azure Synapse:  [LIKE (Transact-SQL) - SQL Server](https://learn.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=azure-sqldw-latest#syntax)

Is there a way to suppress the generation of the `ESCAPE` clause?

Repro:

```csharp
await using var ctx = new BlogContext();
await ctx.Database.EnsureDeletedAsync();
await ctx.Database.EnsureCreatedAsync();

var s = "foo";
_ = await ctx.Blogs.Where(b => b.Name.Contains(s)).ToListAsync();

public class BlogContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\MSSQLLocalDB; Database=test; Trusted_Connection=True;")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

This produces the following query:

```sql
Executed DbCommand (84ms) [Parameters=[@__s_0_contains='%foo%' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SELECT [b].[Id], [b].[Name]
FROM [Blogs] AS [b]
WHERE [b].[Name] LIKE @__s_0_contains ESCAPE N'\'
```

Azure Synapse would be fine with the generated SQL if it did not include `ESCAPE N'\'`

NOTE:  I am greatly indebted to @roji for #32432    😄

### PR DESCRIPTION
**Pull request by cincuranet**
Port of #34463
Port of #34506

Fixes #33555

### Description

Fixes translation of `Contains`/`StartsWith`/`EndsWith` into SQL on Azure Synapse.

### Customer impact

Customers using Azure Synapse are unable to run queries using `Contains`/`StartsWith`/`EndsWith` because improper SQL is generated.

### How found

Reported by customer.

### Regression

Yes, in 8.0.

### Testing

Tests added.

### Risk

Low.

### CODE REVIEW

**Comment by roji** [comment]
Maybe just include into #34508? Otherwise this is lacking the template and the M2 ping.

**Review by roji — APPROVED** [review]

**Comment by cincuranet** [comment]
This went into wrong branch (`main` so it's actually empty commit and nothing is broken). #34510 is correct PR.

**Comment by roji** [comment]
Ah, I see.

**Pull request merged**
