### PR TITLE
Fix for issue 16701. Brackets around tables names supports non-SQL Server providers

### PR DESCRIPTION
**Pull request by lajones**
Fixes issue #16701 . The tests work for SQL Server but in other providers the table names need square brackets (which are then re-interpreted as the provider's escape character).

### CODE REVIEW

**Comment by lajones** [comment]
Ping @roji .

**Comment by roji** [comment]
This fails, this time with PostgreSQL complaining about square brackets being present.

These tests use raw SQL (rather than LINQ), but stuff like delimiters vary across databases. For some other raw SQL tests (e.g. FromSqlQuery) we already have RelationalTestStore.NormalizeDelimetersInRawString, where the raw string contains square brackets, but this method replaces them with the provider's delimiters instead - this could be the fix here too.

**Comment by lajones** [comment]
@roji Got it. I've updated the code to use that. Thanks.

**Comment by roji** [comment]
Looks pretty good! Can you please enclose `Id` in brackets as well? As a column identifier it has the same rules as the table identifier, after that everything should be green.

**Comment by lajones** [comment]
@roji Done. Also found some other usages of a table `TheVoid` which I updated for consistency.

**Pull request merged**
