### PR TITLE
Query: Fix Max/Min after DefaultIfEmpty

### LINKED ISSUE #20589: Problem to eliminating 'Sequence contains no elements' error.
When `DbContext.Areas` has no records, the following code throws an exception:

    int sequence = DbContext.Areas
        .Where(a => a.UserId == userId)
        .Select(a => a.Sequence)
        .Max();

> System.InvalidOperationException: 'Sequence contains no elements.'

The standard way of working around this is to use `DefaultIfEmpty()`. But that doesn't work here either.

    int sequence = DbContext.Areas
        .Where(a => a.UserId == userId)
        .Select(a => a.Sequence)
        .DefaultIfEmpty()
        .Max();

> System.InvalidOperationException: 'Sequence contains no elements.'

I also tried setting an explicit default value. That gives me a different error.

    int sequence = DbContext.Areas
        .Where(a => a.UserId == userId)
        .Select(a => a.Sequence)
        .DefaultIfEmpty(0)
        .Max();

> System.InvalidOperationException: 'Processing of the LINQ expression 'DbSet<Area>
    .Where(a => a.UserId == __userId_0)
    .Select(a => a.Sequence)
    .DefaultIfEmpty(__p_1)' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.'

I also tried a manual workaround. And that doesn't work either.

    int sequence = DbContext.Areas
        .Where(a => a.UserId == userId)
        .Select(a => a.Sequence)
        .Concat(new [] { 0 })
        .Max();

> System.InvalidOperationException: 'Processing of the LINQ expression 'DbSet
.Where(a => a.UserId == __userId_0)
.Select(a => a.Sequence)
.Concat(__p_1)' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.'

Ideally, I would just add `DefaultIfEmpty()` here and be good to go. This shouldn't be so difficult.

### Further technical details

EF Core version: 3.1.3
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1
Operating system: Windows 10
IDE: 16.5.1

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #20589

### CODE REVIEW

**Comment by maumar** [comment]
tests are borked

**Comment by smitpatel** [comment]
Average does not work because types are mismatched. I need to correct SqlExpression.Type more accurately. Let me submit PR for that first.

**Comment by smitpatel** [comment]
Blocked on #20637 
@maumar - Do you prefer to get this checked in for Min/Max and fix issue with Avg as part of #20637? It would resolve customer issue for now.

**Comment by maumar** [comment]
@smitpatel yeah, that sounds good to me, we can split the issues

**Comment by SoftCircuits** [comment]
If this has been fixed, any way to know what version it might come out in?

**Comment by smitpatel** [comment]
5.0.0 preview 4

**Pull request merged**
