### PR TITLE
[release/7.0] fixing a typo in quirk string for issue 30330

### PR DESCRIPTION
**Pull request by maumar**

### CODE REVIEW

**Comment by maumar** [comment]
@ajcvickers do we need approval for stuff like this?

**Review by ajcvickers — APPROVED** [review]

**Comment by ajcvickers** [comment]
@maumar Not sure. @danmoseley?

**Comment by wtgodbe** [comment]
@danmoseley do we need tactics approval for this? It's kind of a behavioral change, but it's so trivial it feels like we could get away with tell-mode

**Comment by danmoseley** [comment]
this didn't ship yet, doesn't add any risk to customers or dates, you can just merge. tactics doesn't care if we make a fix with their approval then need to follow up to fix a typo, so long as it didn't ship yet/ doesn't affect dates.

**Comment by danmoseley** [comment]
@ajcvickers pointed out the the original change will ship ahead of this fix. in that case I suggest either to accept both (the code will not exist in main) or drop tactics a note to tell them.

**Pull request merged**
