### PR TITLE
Throw detailed exception message in buffered data reader

### LINKED ISSUE #20364: BufferedDataReader needs to be accommodating to incorrect values
While working on #20278, we enabled tests which has wrong data to verify we throw better exceptions. All the tests are working correctly for Sqlite. But for SqlServer where we use BufferedDataReader, the reader throws early exception while trying to read values. Hence the code not reach the place where we intercept exception to throw better message (that code is part of shaper), BufferedDataReader buffers before calling into shaper.

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #20364

Adds code for error handling when create buffered data reader.
Code needs to handle unexpected nulls and incorrect type of data encountered

### CODE REVIEW

**Comment by smitpatel** [comment]
@Pilchie for RC1 approval.

**Comment by AndriySvyryd** [comment]
@dotnet/efteam New API:

- `ReaderColumn.ctor`
- `ReaderColumn.Create`
- `ReaderColumn.Property `
- `ReaderColumn<>.ctor`
- `RelationalCommandParameterObject.ctor`
- `RelationalCommandParameterObject.DetailedErrorsEnabled`

**Comment by Pilchie** [comment]
Approved for RC1.

**Pull request merged**
