### PR TITLE
Added TimeSpanToHours converter

### LINKED ISSUE #24917: TimeSpanToHoursConverter
I'd like to try contributing to EFCore.

Would a PR with the following code be accepted:
```
// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System;

namespace Microsoft.EntityFrameworkCore.Storage.ValueConversion
{
    /// <summary>
    ///     Converts <see cref="TimeSpan" /> to and <see cref="TimeSpan.TotalHours" />.
    /// </summary>
    public class TimeSpanToHoursConverter : ValueConverter<TimeSpan, double>
    {
        /// <summary>
        ///     Creates a new instance of this converter.
        /// </summary>
        /// <param name="mappingHints">
        ///     Hints that can be used by the <see cref="ITypeMappingSource" /> to create data types with appropriate
        ///     facets for the converted data.
        /// </param>
        public TimeSpanToHoursConverter(ConverterMappingHints? mappingHints = null)
            : base(v => v.TotalHours, v => TimeSpan.FromHours(v), mappingHints)
        {
        }

        /// <summary>
        ///     A <see cref="ValueConverterInfo" /> for the default use of this converter.
        /// </summary>
        public static ValueConverterInfo DefaultInfo { get; }
            = new(typeof(TimeSpan), typeof(double), i => new TimeSpanToHoursConverter(i.MappingHints));
    }
}

```

### PR DESCRIPTION
**Pull request by TonyValenti**
Please check if the PR fulfills these requirements:

- [x] The code builds and tests pass (verified by our automated build checks)
- [x] Commit messages follow this format
        Summary of the changes
        - Added TimeSpanToHours converter.
        - Resolves #24917
- [x] Code follows the same patterns and style as existing code in this repo

Review the guidelines for [contributing](CONTRIBUTING.md) for more details.

### CODE REVIEW

**Comment by TonyValenti** [comment]
@ajcvickers Can you review?

**Comment by ErikEJ** [comment]
You need to add a test ☺️

**Comment by roji** [comment]
I'm not sure this kind of value converter belongs in EF Core...

EF Core comes with a variety of value converters, but which are necessary in order to save certain CLR types where native database support for them doesn't exist. This value converter, on the contrary, seems to support a very specific user scenario, i.e. extracting out only the hours component of a TimeSpan. There's an infinite number of possible similar converters (why just hours, why not minutes, seconds?), and it's trivial (and recommended) for users to have this kind of converter in their project.

If I've missed something, can you provide more context on why this is needed and why you think it belongs in-the-box in EF Core?

**Comment by roji** [comment]
Closing as per triage decision.

**Pull request closed without merging**
