### PR TITLE
Increase timeout for helix build

### PR DESCRIPTION
**Pull request by smitpatel**
System is just slow in scheduling and running the job.

### CODE REVIEW

**Comment by roji** [comment]
Srsly? 3 hours?

**Comment by smitpatel** [comment]
Run from 12noon was finished fully. 1:34PM is still awaiting so..... Should be a temp thingy. If this does not work then I will go to 5 I think. (Fibonacci series)

**Comment by smitpatel** [comment]
Current wait time is about 2.2h. Avg wait time at present is about 1.7h. fun times!

**Comment by smitpatel** [comment]
Helix finished at 126 mins. 🥳

**Pull request merged**
