### PR TITLE
Avoid recreating the LocalDB instance by detaching orphaned databases

### PR DESCRIPTION
**Pull request by AndriySvyryd**

### CODE REVIEW

**Comment by dougbu** [comment]
I suspect this will work pretty well but the scripts don't seem to be referenced from the YAML for our builds. How about changing the YAML to use these scripts?

Also, EF6 is a separate beast that appears to lack scripts wrapping the https://github.com/dotnet/ef6/blob/master/tools/DropAllDatabases.sql content. Are you proposing doing something similar there?

**Comment by AndriySvyryd** [comment]
> How about changing the YAML to use these scripts?

Currently there's no need to do this for efcore

> Are you proposing doing something similar there?

Yes, ef6 tests aren't as resilient

**Comment by dougbu** [comment]
> Yes, ef6 tests aren't as resilient

Awesome, especially if we do this in the servicing branches. I'll just leave dotnet/ef6#1610 through dotnet/ef6#1612 open 'til validation builds can succeed.

**Comment by AndriySvyryd** [comment]
@dougbu So are you going to submit the script changes as a separate PR?

**Comment by dougbu** [comment]
Hmm, I thought we didn't need them in this repo and you were going to handle doing the **Right Thing:tm:** in EF6? What exactly do you want me to take?

**Comment by AndriySvyryd** [comment]
@dougbu That's fine, just wanted to be clear about your plans

**Pull request merged**
