### PR TITLE
Unpin Microsoft.Extensions.Caching.Memory and Microsoft.Extensions.Logging

### PR DESCRIPTION
**Pull request by mmitche**
Fixes https://github.com/dotnet/efcore/issues/25148

### CODE REVIEW

**Comment by mmitche** [comment]
@bricelam Legit failures here..can you take a look?

**Comment by ajcvickers** [comment]
@mmitche Looks like the dependency update brought in breaking changes. Are these intentional? If so, where can we find more information?

**Comment by mmitche** [comment]
> @mmitche Looks like the dependency update brought in breaking changes. Are these intentional? If so, where can we find more information?

I'm not sure... https://docs.microsoft.com/en-us/dotnet/api/system.span-1.copyto?view=net-5.0 seems to indicate that CopyTo is netstandard 2.1...so something else is going on.

**Comment by mmitche** [comment]
@ajcvickers I have a hunch and am attempting to update to the p6 sdk.

**Review by dougbu — APPROVED** [review]
Just curious: Why was an Arcade update needed❔

**Comment by dougbu** [comment]
I thought @bricelam already reacted to logging API changes in this repo❔

``` text
      Application startup exception
      System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.Mvc.MvcCoreLoggerExtensions' threw an exception.
       ---> System.MissingMethodException: Method not found: 'System.Action`4<Microsoft.Extensions.Logging.ILogger,!!0,!!1,System.Exception> Microsoft.Extensions.Logging.LoggerMessage.Define(Microsoft.Extensions.Logging.LogLevel, Microsoft.Extensions.Logging.EventId, System.String, Boolean)'.
         at Microsoft.AspNetCore.Mvc.MvcCoreLoggerExtensions..cctor()
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory..ctor(IModelMetadataProvider metadataProvider, IOptions`1 options, IServiceProvider serviceProvider) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000629+0x35
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004eca+0x63
```

Might need newer ASP.NET bits too

**Comment by mmitche** [comment]
> Just curious: Why was an Arcade update needed❔

It was a hunch based on one of the previous errors (a missing method exception). I thought there may be a mismatch between the runtime that tests were executing on and the compiled code. It did actually resolve that exception.

**Comment by bricelam** [comment]
Duplicate of #25244

**Pull request closed without merging**
