### PR TITLE
Update SDK

### PR DESCRIPTION
**Pull request by surayya-MS**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by MackinnonBuck** [comment]
@bricelam Could you or someone on the EF team look into the failure here?
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGeneratorTest.Test(DbContext context, CompiledModelCodeGenerationOptions options, Action`1 assertScaffold, Action`1 assertModel, Type additionalDesignTimeServices, Action`1 useContext, String expectedExceptionMessage) in D:\a\_work\1\s\test\EFCore.Design.Tests\Scaffolding\Internal\CSharpRuntimeModelCodeGeneratorTest.cs:line 8001
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGeneratorTest.Global_namespace_works() in D:\a\_work\1\s\test\EFCore.Design.Tests\Scaffolding\Internal\CSharpRuntimeModelCodeGeneratorTest.cs:line 133
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by AndriySvyryd** [comment]
Filed https://github.com/dotnet/runtime/issues/84644

**Comment by AndriySvyryd** [comment]
Superseded by https://github.com/dotnet/efcore/pull/30679

**Pull request closed without merging**
