### PR TITLE
Update dotnet-ef to roll forward across major .NET Core versions

### PR DESCRIPTION
**Pull request by bricelam**
This should unblock https://github.com/dotnet/aspnetcore/pull/17947

### CODE REVIEW

**Comment by dougbu** [comment]
Hmm, no validation build got kicked off. I suspect the org change busted our AzDO integration. This is important here because I wanted to double-check the created package ☹️ 

@mmitche @Pilchie @wtgodbe @JunTaoLuo @anurse what needs to happen to get our pipelines running again? Is it just renaming the pipelines too?

**Comment by dougbu** [comment]
Thanks @mmitche❕

**Comment by dougbu** [comment]
Things got very confused as pipelines were renamed. Closing and reopening&hellip;

**Comment by JunTaoLuo** [comment]
@BrennanConroy just updated the pipelines so builds should be triggering now.

**Comment by dougbu** [comment]
Thanks for doing that work @BrennanConroy❕

**Comment by dougbu** [comment]
BTW I'll sign off once I see the added tag in action i.e. once the validation builds produce artifacts.

**Comment by dougbu** [comment]
Shoot. I forgot we don't create package artifacts for PR builds of forks. @bricelam I suggest checking this in and checking the next official build to make sure this works as expected.

**Pull request merged**
