### PR TITLE
Use right hand type mapping for more binary expressions when left is an object

### LINKED ISSUE #34618: 'Expression in the SQL tree does not have a type mapping assigned' on ternary with non-null condition and string operation only
## File a bug

When projecting to a string concatenation of a numeric value and a constant string I received an `InvalidOperationException` stating the `Expression '&lt;EXPRESSION>' in the SQL tree does not have a type mapping assigned. This seems to occur only under the following circumstances (as evidenced by the test cases):
- Ternary operator is used with `!= null` condition
- String concatenation is used with first argument being numeric
- Where condition is applied that uses a string operator (`Contains`, `StartsWith`)

If any of above conditions is not met the issue doesn't occur.

### Include your code

```C#
// Fails with either SQL LocalDB or actual SQL Server, no other DBs tested

public class Test
{
    // Fails
    [Theory]
    [AutoFakeItEasyData]
    internal void Ternary_Not_Null_Contains(TestDbContext db)
    {
        db.Database.EnsureCreated();
        try
        {
            db.Set<Entity>().Select(x => x != null ? x.Id + "" : null).FirstOrDefault(x => x!.Contains("1"));
        }
        finally
        {
            db.Database.EnsureDeleted();
        }
    }

    // Fails
    [Theory]
    [AutoFakeItEasyData]
    internal void Ternary_Not_Null_StartsWith(TestDbContext db)
    {
        db.Database.EnsureCreated();
        try
        {
            db.Set<Entity>().Select(x => x != null ? x.Id + "" : null).FirstOrDefault(x => x!.StartsWith("1"));
        }
        finally
        {
            db.Database.EnsureDeleted();
        }
    }

    // Pass
    [Theory]
    [AutoFakeItEasyData]
    internal void Ternary_Not_Null_Contains_Non_Numeric_First_Part(TestDbContext db)
    {
        db.Database.EnsureCreated();
        try
        {
            db.Set<Entity>().Select(x => x != null ? "" + x.Id + "" : null).FirstOrDefault(x => x!.Contains("1"));
        }
        finally
        {
            db.Database.EnsureDeleted();
        }
    }

    // Pass
    [Theory]
    [AutoFakeItEasyData]
    internal void Ternary_Not_Null_Equals(TestDbContext db)
    {
        db.Database.EnsureCreated();
        try
        {
            db.Set<Entity>().Select(x => x != null ? x.Id + "" : null).FirstOrDefault(x => x == "1");
        }
        finally
        {
            db.Database.EnsureDeleted();
        }
    }

    // Pass
    [Theory]
    [AutoFakeItEasyData]
    internal void Ternary_Null_Contains(TestDbContext db)
    {
        db.Database.EnsureCreated();
        try
        {
            db.Set<Entity>().Select(x => x == null ? null : x.Id + "").FirstOrDefault(x => x!.Contains("1"));
        }
        finally
        {
            db.Database.EnsureDeleted();
        }
    }

    // Pass
    [Theory]
    [AutoFakeItEasyData]
    internal void Ternary_Null_StartsWith(TestDbContext db)
    {
        db.Database.EnsureCreated();
        try
        {
            db.Set<Entity>().Select(x => x == null ? null : x.Id + "").FirstOrDefault(x => x!.StartsWith("1"));
        }
        finally
        {
            db.Database.EnsureDeleted();
        }
    }

    internal class TestDbContext(DbContextOptions options) : DbContext(options)
    {
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Entity>();

            base.OnModelCreating(modelBuilder);
        }
    }

    private class Entity
    {
        public int Id { get; set; }
    }
}
```

### Include stack traces

Exception only happens in `Ternary_Not_Null_Contains` and `Ternary_Not_Null_StartsWith`, stack trace seems identical so this is only the trace from `Ternary_Not_Null_Contains`.

```
System.InvalidOperationException
Expression 'CASE
    WHEN Not(e.Id == NULL) THEN Convert(e.Id) + 
    ELSE NULL
END' in the SQL tree does not have a type mapping assigned.
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.RelationalInferredTypeMappingApplier.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.SqlServerInferredTypeMappingApplier.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.LikeExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.RelationalInferredTypeMappingApplier.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.SqlServerInferredTypeMappingApplier.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.VisitChildren(ExpressionVisitor visitor, Boolean updateColumns)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression.VisitChildren(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.RelationalInferredTypeMappingApplier.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.SqlServerInferredTypeMappingApplier.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.RelationalInferredTypeMappingApplier.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.SqlServerInferredTypeMappingApplier.VisitExtension(Expression expression)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerQueryableMethodTranslatingExpressionVisitor.ApplyInferredTypeMappings(Expression expression, IReadOnlyDictionary`2 inferredTypeMappings)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at <redacted>.Test.Ternary_Not_Null_Contains(TestDbContext db) in <redacted>\EFCoreProjection.cs:line 14
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

### Include verbose output

NA

### Include provider and version information

EF Core version: 8.0.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer, 8.0.8
Target framework: .NET 8.0
Operating system: Windows 10 (10.0.19045.4780)
IDE: Visual Studio 2022 17.10.3

### PR DESCRIPTION
**Pull request by ChrisJollyAU**
- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

With a query like `Select(x => x != null ? x.Id + "" : null).FirstOrDefault(x => x!.Contains("1"));` you have a binary expression of `x.Id + ""`. The left hand side comes through from LINQ without any type mapping and when inferring the type mapping for the result of the binary expression it always looks at the left hand side so you end up with a Type of `object` and a null type mapping for the expression

With the order of the `Select` it ends up trying to take the type mapping of `x.Id + ""` for the result of the `CASE`. When you then do a `StartsWith`, `EndsWith`. `Contains` all those are translated as a `LIKE` and no type mapping is changed.

It works with the equals `Select(x => x != null ? x.Id + "" : null).FirstOrDefault(x => x == "1");` as that code does look at the right hand side if the left is an object.

See line 185 in SqlExpressionFactory
```
inferredTypeMapping = ExpressionExtensions.InferTypeMapping(left, right)
    // We avoid object here since the result does not get typeMapping from outside.
    ?? _typeMappingSource.FindMapping(
        left.Type != typeof(object) ? left.Type : right.Type,
        Dependencies.Model);
```

When you flip the Select around (`Select(x => x == null ? null : x.Id + "").FirstOrDefault(x => x!.Contains("1"));`) it works because the `null` result with type mapping of string is used for the result of the `CASE` and the type mapping is applied on all expressions

This change adds the same type of logic elsewhere in the `ApplyTypeMappingOnSqlBinary` for the Add, Subtract etc operations

Tests added in AdHocMiscellaneousQueryTestBase.
- Is there a better test class to put it in?
- Currently only overriding it in SQL Server to assert the sql - sqlite only uses base
- Cosmos?

Fixes #34618

### CODE REVIEW

**Comment by maumar** [comment]
@ChrisJollyAU sorry for delayed response. Changes look good. Wrt testing, we try to put straightforward queries into classes that use AssertQuery. This way we take advantage of result verification and some other perks. AdHoc should generally be used for tests with complicated mappings (not covered by AssertQuery models) or if there is some other gimmick that is required for the test. There are a lot of those AssertQuery classes and it can sometimes be hard to pick the best place. When in doubt, you can always use GearsOfWar class, which is our dumping ground for all sort of query tests.

When it comes to sql verification, we do require SQL Server, Sqlite is usually very similar to there is no point. If there is some specific sqlite construct or translation differs significantly between sql server and sqlite, it's good idea to add the SQL verification. But we don't require it. 

Cosmos doesn't translate this scenario - added translation error verification, so that if in the future the scenario is enabled we will catch it.

Also, I removed some of the tests, there is no need to do all the combinations. It took me way to long to reply, so I made the testing changes, rather than burden you with them.

**Review by maumar — APPROVED** [review]

**Comment by maumar** [comment]
Thank you for the contribution @ChrisJollyAU !

**Comment by ChrisJollyAU** [comment]
@maumar Thanks for sorting the tests out. You are right that we probably didn't need all those combinations - especially when things like contains/startswith/endswith all follow the same path (at least in sql server)

Was happy to wait for you to get to it - I expect the current priority was finalizing EFCore 9.

Quick question: Do I need to a backport PR or is this just going to stay on the 10.0 branch?

**Comment by roji** [comment]
> Cosmos doesn't translate this scenario - added translation error verification, so that if in the future the scenario is enabled we will catch it.

@maumar maybe Cosmos doesn't translate this particular query, but isn't the fix as-is relevant to Cosmos as well (whose SqlExpressionFactory was basically a copy-paste of the relational one)? We really should start keeping Cosmos in mind and applying fixes there too, to not have to deal with the same bugs again there later...

**Comment by roji** [comment]
@ChrisJollyAU thanks for taking a look... Yeah, the Cosmos provider is definitely behind in many ways - it was basically copy-pasted from relational a long time ago, and not well-maintained since (we did a big push for 9.0 but there's a lot of stuff will remaining). I do have some ideas on how to try to merge more parts of Cosmos and relational so we have less duplication to manage, but in the meantime this situation is precisely why we should try to apply fixes to both relational and Cosmos, to keep them from diverging even further.

Concretely, it sounds like a new issue is needed for the string concatenation problem you ran into. However, the specific fix in this PR seems correct regardless of whether it actually fixes any specific bugs/tests (hopefully it doesn't break any...). So I'd still port the fix across, unless you think there's some reason not to?

**Comment by ChrisJollyAU** [comment]
Sure, we can apply this fix. It's just a 1 liner.

Quick run through locally doesn't show any that it breaks. (I do have some in JsonQueryCosmosTest that fail on a JsonSerializationException but that doesn't look like anything to do with this error and the tests have the `[SkipOnCiCondition]` attribute.

First time I'm looking at Cosmos and did find myself wondering why things like the `SqlExpressionFactory` and others are all on their own separate to the relational ones. Would be nice if the common things were all together and not duplicated

**Comment by ChrisJollyAU** [comment]
Definitely new issue. Note that test like `Concat_string_int` passes for Cosmos because it is in the top level projection which falls back to client-side concatenation. Will create a new issue sometime

**Comment by roji** [comment]
> Sure, we can apply this fix. It's just a 1 liner.

Great, thanks! Feel free to submit a PR.

> First time I'm looking at Cosmos and did find myself wondering why things like the SqlExpressionFactory and others are all on their own separate to the relational ones. Would be nice if the common things were all together and not duplicated

There are non-trivial reasons for this... For example, in the query pipeline design, SqlExpression represents a scalar and so references a type mapping (which describes the type of that scalar), but type mappings are provider-specific (RelationalTypeMapping vs. CosmosTypeMapping). This causes the need to duplicate SqlExpression, and from there also SqlExpressionFactory.

I definitely agree that we should rethink this design and see how we can get mure reuse across the providers - but that's a deep architectural task that we don't currently have the bandwidth for (there are more urgent deep architectural tasks that would get priority)... So unfortunately for now we need to do our best to keep things more or less aligned, e.g. fixing bugs on both.

**Comment by ChrisJollyAU** [comment]
> but that's a deep architectural task that we don't currently have the bandwidth for (there are more urgent deep architectural tasks that would get priority)... So unfortunately for now we need to do our best to keep things more or less aligned, e.g. fixing bugs on both.

Yeah. that might be a whole feature release on its own

**Pull request merged**
