### PR TITLE
Add support for DATA_COMPRESSION and SORT_IN_TEMPDB SQL Server index options

### LINKED ISSUE #30408: SQL Server Index options SortInTempDB and DataCompression
I want to be able to use Fluent API to specify more index options. I have a particular interest in `SORT_IN_TEMPDB` and `DATA_COMPRESSION`.

Want something like: 
```
indexBuilder.IsSortedInTempDb(true);

indexBuilder.HasDataCompression(DataCompression.Page);
```
This can be done by following the pattern set by the fill factor option - #20634.

SORT_IN_TEMPDB can be ON or OFF
DATA_COMPRESSION has the options NONE, ROW, and PAGE ([link](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver16#data_compression))

I could work this if determined it would be a good first issue.

### PR DESCRIPTION
**Pull request by hmajerus**
Closes #30408

Please check whether the PR fulfills these requirements

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a (loosely) detailed description of how I am planning to contribute and got approval from a member of the team
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

### CODE REVIEW

**Comment by hmajerus** [comment]
@dotnet-policy-service agree company="Buildertrend"

**Comment by hmajerus** [comment]
@ajcvickers and/or @bricelam Sorry for the ping, but let me know if there is anything I can provide or do to make this PR more manageable to review. I have the time to account for any recommendations you may have.

**Comment by hmajerus** [comment]
Cool, I'm busy here at the end of the week, but will get to fixing that next week.

**Comment by bricelam** [comment]
No rush, sorry it took us so long to get to

**Comment by hmajerus** [comment]
Updated to use SqlServerIndexBuilderExtensions for DataCompression and SortInTempDb in snapshots. 

Want to point out that without that update the snapshots would still contain something that looks like this:
```
b.HasIndex("Id").HasAnnotation("SqlServer:DataCompression", DataCompressionType.Row);
```
Which will prevent those drop-creates. This is currently the case for the `IsCreatedOnline` Index option. 

This update makes the snapshot look like the following, which I imagine is preferred to the one above anyway.
```
SqlServerIndexBuilderExtensions.UseDataCompression(b.HasIndex("Id"), DataCompressionType.Row);
```

**Review by AndriySvyryd — APPROVED** [review]

**Review by bricelam — APPROVED** [review]

**Pull request merged**
