### PR TITLE
Using not readonly stuct with in modifier

### PR DESCRIPTION
**Pull request by SergerGood**

### CODE REVIEW

**Review by roji — APPROVED** [review]
@AndriySvyryd can you confirm this is right too?

**Review by AndriySvyryd — APPROVED** [review]
If these were on hot path we could've switched to using `ref`

**Comment by roji** [comment]
Yeah, though there's a struct size threshold below which it's better to pass by value and avoid the extra dereferencing etc., at least for `Nullable<MemberIdentity>` I wouldn't assume ref improves things.

Anyway... :)

**Comment by roji** [comment]
Thanks @SergerGood!

**Pull request merged**
