### PR TITLE
Implement remaining Migrations Bundles features

### LINKED ISSUE #19693: Migrations Bundles
We currently have `dotnet ef migrations script` and `database update` to apply migrations. Unfortunately, they each have their shortcomings.

`migrations script` is pretty good at producing SQL scripts (there are some known issues with the scripts), but figuring out what to do with those scripts may not be obvious. Publish from Visual Studio wraps these scripts up in a web deployment package and uses MSDeploy to run them on the server. This works well for SQL Server on Windows, but nothing else.

`database update` is a lot better at applying migrations. It doesn't have any of the issues the SQL script does. Unfortunately, it requires the .NET Core SDK, your app's source code, and a direct connection to the production database. Having all of these things available where you need them is't always possible.

I propose we introduce a new `migrations bundle` command. This would create a self-contained EXE that you could use to apply migrations. It would behave the same as `database update` and let you specify the connection string. This would make SSH/Docker/PowerShell deployment a lot easier. You wouldn't need to copy your source files to a server inside the firewall and you wouldn't need to install the .NET Core SDK. Here is an example of what it might look like to use SSH:

```sh
dotnet ef migrations bundle
scp bundle me@myhost.com:./
ssh me@myhost.com "./bundle --connectionString ${DEPLOYMENT_CONNECTION_STRING}"
ssh me@myhost.com "rm bundle"
```

Taking this further, Visual Studio could do all of this for you like they do today on MSDeploy but when you're deploying to Docker. They could even create a new SSH deployment experience.

---

### TODO

- [x] Add `--output` to allow renaming the bundle
- [x] Match TargetFramework, ~~RuntimeIdentifier, and SelfContained~~ of startup project by default
  - ~~Add `--no-self-contained`~~
- [x] `--self-contained` doesn't work
  > error NETSDK1031: It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier. You must either specify a RuntimeIdentifier or set SelfContained to false.
- [x] `--runtime` doesn't work between Windows and other OSes. We look for *.exe based on the *current* runtime instead of the *target* runtime.
- [x] Add automated tests
- [x] Add `--force` to overwrite an existing bundle #25271
- [x] Refine command output #25274
- [x] `--configuration` and `--runtime` optoins are repeated in help

### PR DESCRIPTION
**Pull request by bricelam**
Changes:
- Use TargetFramework from startup project
- Add --output and --force
- Fix --runtime and --self-contained
- Output bundle path
- Move the MigrationsBundle class under the Migrations namespace

Fixes #19693, part of #24743

### CODE REVIEW

**Review by smitpatel — APPROVED** [review]
:shipit:

**Comment by smitpatel** [comment]
🙄

**Comment by bricelam** [comment]
Race condition?

**Comment by bricelam** [comment]
Merged as 65fd0cb71ffee292d9c5cbb0331c1817edb54bdc

**Pull request closed without merging**
