### PR TITLE
[release/5.0] Recategorize runtime dependencies

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Review by dougbu — APPROVED** [review]
Agree these are product dependencies after all.

/cc @bricelam @ajcvickers

**Review by bricelam — APPROVED** [review]
Yes for servicing branch; maybe for main.

**Comment by smitpatel** [comment]
@bricelam - "maybe" may need an answer so we know if we should flow this commit as is to main while merging.

**Comment by bricelam** [comment]
I'm fine either way for now. We'll react to the consequences as they become a problem.

**Pull request merged**
