### PR TITLE
Use file-scoped namespaces and implicit usings in tests

### LINKED ISSUE #26772: Use file scoped namespaces

### LINKED ISSUE #26773: Use implicit usings

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #26772
Fixes #26773

### CODE REVIEW

**Review by AndriySvyryd — APPROVED** [review]
Also consider adding `System.Text` and `Xunit`

**Comment by roji** [comment]
I'd consider adding all non-internal Microsoft.EntityFrameworkCore namespaces. This can also be done at a global level for the entire solution (another good reason why I think Microsoft.Data.Sqlite shouldn't be in the repo, btw). [Here's the EFCore.PG setup](https://github.com/npgsql/efcore.pg/blob/main/Directory.Build.props#L27).

**Comment by ajcvickers** [comment]
> I'd consider adding all non-internal Microsoft.EntityFrameworkCore namespaces. 

Which ones are missing?

**Comment by roji** [comment]
Nested ones (e.g. Metadata.Conventions etc.). Also, if we move the implicit usings to the global repo level, we can also put the relational ones in there (Migrations) - unless we think it's important to not have those usings in non-relational projects (I'm not sure I see a problem with that though).

**Comment by ajcvickers** [comment]
@roji As far as I can tell, you can't have implicit usings for namespaces that don't exist in the project--the compiler complains that the namespace does not exist. Also, there were problems using them in projects that target .NET Framework TFMs.

**Comment by roji** [comment]
> As far as I can tell, you can't have implicit usings for namespaces that don't exist in the project--the compiler complains that the namespace does not exist.

Seems like you're right... That's too bad.

> Also, there were problems using them in projects that target .NET Framework TFMs.

It may be possible to just disable implicit usings at the project level here, but this is moot in any case because of the 1st point...

I guess it's per-project then...!

**Comment by ajcvickers** [comment]
Added more implicit namespaces

**Review by roji — APPROVED** [review]
:sheep: :it:

**Pull request merged**
