### PR TITLE
[release/9.0] Nominally upgrade Microsoft.Build.Framework to 17.8.3

### PR DESCRIPTION
**Pull request by AndriySvyryd**

### CODE REVIEW

**Review by halter73 — APPROVED** [review]

**Review by SamMonoRT — APPROVED** [review]

**Comment by roji** [comment]
Thanks @AndriySvyryd, maybe do this for the analyzers package too, to not have problematic versions anywhere in it dependency graph?

**Review by artl93 — APPROVED** [review]

**Comment by AndriySvyryd** [comment]
@roji Can you be more specific? EFCore.Analyzers doesn't bring in `Microsoft.Build.Framework` or `System.Drawing.Common`

**Comment by roji** [comment]
> @roji Can you be more specific? EFCore.Analyzers doesn't bring in Microsoft.Build.Framework or System.Drawing.Common

Ah sorry... EFCore.Analyzers does depend on an older version of Microsoft.CodeAnalysis (4.8.0) and I thought that brought in transitive dependencies with security advisories, but that indeed doesn't seem to be the case.

**Comment by ericstj** [comment]
This change needs to be made in main as well.

**Comment by AndriySvyryd** [comment]
@ericstj That's handled by https://github.com/dotnet/efcore/pull/34621

**Comment by ericstj** [comment]
Oh, interesting, you do codeflow differently in EFCore - understood.  For runtime we make the change in main first then backport.

**Pull request merged**
