### PR TITLE
[release/7.0] Fix to #31448 Use token for NonQueryResultAsync

### PR DESCRIPTION
**Pull request by dsgordeev**
Fixes (https://github.com/dotnet/efcore/issues/31448)

### CODE REVIEW

**Comment by ajcvickers** [comment]
@dsgordeev Please re-target this to the main branch.

**Comment by dsgordeev** [comment]
@ajcvickers, it's done. Thanks for feedback.

**Review by ajcvickers — APPROVED** [review]

**Comment by ajcvickers** [comment]
Thanks!

**Comment by dsgordeev** [comment]
Welcome! Very interesting framework to dive into. Especially in part of language translation (AST to SQL).

**Pull request merged**
