### PR TITLE
[release/3.1] Check if parameter.Name is not null before comparing it with query pa…

### LINKED ISSUE #18502: Query: use TryGetValue where we access parameter values.
when accessing parameter values based on name we access them directly, rather than using TryGetValue. We should change that and add test for the negative case.

### LINKED ISSUE #20485: ParameterExpression.Name can be null but EF doesn't handle that
If you build an expression on a DbContext and execute it like so `lambdaExpression.Compile().DynamicInvoke(myArgs);` you will get an error if you create `ParameterExpression`s with no name. Which the API lets you do - `Expression.Parameter(typeof(MyType))`. But code in EF 3.1 (note 2.x worked) expects there is a name e.g.

```
if (target is ParameterExpression baseParameterExpression
                && baseParameterExpression.Name.StartsWith(CompiledQueryCache.CompiledQueryParameterPrefix, StringComparison.Ordinal))
```

in `EntityEqualityRewritingExpressionVisitor.cs` line 941.

This is EF 3.1.3.

Obviously I'm not building expression, but a library is, this one - https://github.com/lukemurray/EntityGraphQL

Yes I'll update to add names for all parameters, but if someone can create a `ParameterExpression` with a null name should EF handle that?

This is 1 place I found, but I guess it could be in many places?

### Steps to reproduce

Use the above library on 3.1. Or, not tested but should be something like 
``` C#
var p = Expression.Parameter(typeof(MyDbContext));
var prop = Expression.Property(p, "SomeRelation");
var lambda = Expression.Lambda(prop, new [] { p });
var result = lambda.Compile().DynamicInvoke(instanceOfDbContext);
```

### Further technical details

EF Core version: 3.1.3
Database provider: Npgsql
Target framework: .net core 3.1
Operating system: Mac OS
IDE: VS Code

### PR DESCRIPTION
**Pull request by smitpatel**
…rameter

Resolves #20485

Parameters which are used inside lambda should get replaced with appropriate shaper/selector.
All other parameters should be query parameters otherwise it is an error.

### CODE REVIEW

**Comment by smitpatel** [comment]
Description
EF does special processing for certain parameters which are created by query during parameter extraction (for caching). To do this we compare the prefix of parameter name. This threw NRE when a parameter which had no name encountered.
Fix is to do null safe comparison. If parameter does not have name then we don't need to do any processing required for query parameter.

Customer Impact
Error for dynamically generated queries by multiple different libraries as parameter name is not required during expression tree generation.

How found
Reported by multiple customers.

Test coverage


Regression?
No.

Risk
Low. Fix only affects make comparison null safe without affecting existing functionality.

**Comment by ajcvickers** [comment]
@smitpatel Can you add a regression test that creates a couple of expression trees without parameter names?

Also, I think this likely is a regression in the sense that I think that we handled this case in the previous pipeline, or am I wrong about that?

**Comment by smitpatel** [comment]
Updated. Added regression test and quirk.

**Comment by ajcvickers** [comment]
@smitpatel Approved by tactics for 3.1.4. Please merge ASAP.

**Pull request merged**
