### PR TITLE
Fix for issue #23027

### PR DESCRIPTION
**Pull request by dmitry-lipetsk**
This PR resolves a problem #23027 and provides easy way for override ColumnModification behaviour.

In other words, now custom data provider may create new class, that inherited ColumnModification, and without any problems integrate it into current EFCore infrastructure.

All what requires for this - write own implementation of new interface IColumnModificationFactory, that will create custom ColumnModification objects, and register this factory in EFCore services by standard way through call of

`TryAdd<IColumnModificationFactory, MyColumnModificationFactory>()
`

----
Without this PR need override ModificationCommand and another classes, which create ColumnModification directly.

----
New interface Microsoft.EntityFrameworkCore.Update.IColumnModificationFactory

New class Microsoft.EntityFrameworkCore.Update.Internal.ColumnModificationFactory

Changes in ColumnModification:
- [added] protected [R] GenerateParameterName
- [added] protected [RW] InternalValueOfParameterName
- [added] protected [RW] InternalValueOfOriginalParameterName

Changes in CommandBatchPreparerDependencies:
 - [added] public [RI] ColumnModificationFactory
 - Constructor requires columnModificationFactory and setup it into ColumnModificationFactory

Changes in CommandBatchPreparer:
 - [added] _columnModificationFactory
 - Constructor setup dependencies.ColumnModificationFactory to _columnModificationFactory
 - CreateModificationCommands sends _columnModificationFactory into ModificationCommand

Changes in EntityFrameworkRelationalServicesBuilder
 - RelationalServices registers IColumnModificationFactory
 - TryAddCoreServices added IColumnModificationFactory -> ColumnModificationFactory

Changes in MigrationsSqlGeneratorDependencies
 - [added] public [RI] ColumnModificationFactory
 - Constructor requires columnModificationFactory and setup it into ColumnModificationFactory

Changes in MigrationsSqlGenerator
 - GenerateModificationCommands [all variants] use Dependencies.ColumnModificationFactory.CreateColumnModification

Changes in ModificationCommand
 - [added] _columnModificationFactory
 - [added] private static class SingleColumnModificationFactory
 - [added] New constructors which requres columnModificationFactory and setup it into _columnModificationFactory
 - Old constructors call new constructors with SingleColumnModificationFactory.Instance
 - GenerateColumnModifications uses _columnModificationFactory.CreateColumnModification

Updated tests:
 - CommandBatchPreparerTest
 - FakeModificationCommand
 - MigrationCommandListBuilderTest
 - ModificationCommandComparerTest
 - ModificationCommandTest
 - ReaderModificationCommandBatchTest
 - SqlServerModificationCommandBatchFactoryTest
 - SqlServerModificationCommandBatchTest
 - UpdateSqlGeneratorTestBase

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
The `ColumnModification` is tightly coupled with `ModificationCommand`, so it would be more appropriate to have an `IModificationCommandSource`. In the future it could also be used to pool `ModificationCommand` instances.

The signature for the factory method should be `ModificationCommand Create(ModificationCommandParameters)` to avoid breaking changes if we need to change the passed in parameters.

`ModificationCommand` would need a `ModificationCommand AddModificationCommand(ModificationCommandParameters)` method for `MigrationsSqlGenerator` use.

You don't need to change Obsolete methods to use this.

**Comment by dmitry-lipetsk** [comment]
Hello @AndriySvyryd,

I'm afraid I didn't understand your idea.

You are suggesting to:

1. Create new interface:
```
interface IModificationCommandSource
{
 ModificationCommand Create(ModificationCommandParameters);
};
```

2. To ModificationCommand append new public virtual method

`ColumnModification AddColumnModification(ColumnModificationParameters)
`
?

Or AddColumnModification must be in IModificationCommandSource?

---
In any case - why AddColumnModification but not CreateColumnModification?

**Comment by AndriySvyryd** [comment]
@dmitry-lipetsk `AddColumnModification` will be on `ModificationCommand`. This way ColumnModifications are encapsulated by ModificationCommand making them easier to change.

**Comment by AndriySvyryd** [comment]
@dmitry-lipetsk Do you have any more question about the requested changes?

**Comment by dmitry-lipetsk** [comment]
Hello Andriy,

No, thanks :-)

I remember about this PR.

This is the only thing (currently) that needs to be implemented in EFCore for my provider. All another problems were resolved.

I want to finish the main things first. And then I will return to this question.

I hope - before end of this spring.

**Comment by dmitry-lipetsk** [comment]
@AndriySvyryd 

I have some additional question about ModificationCommand.

ModificationCommand::get_ColumnModifications uses "atomic" initialization of _columnModifications:

https://github.com/dotnet/efcore/blob/a1216b1de00f7443a38f8efe3387adfc5d7c21d0/src/EFCore.Relational/Update/ModificationCommand.cs#L131-L133

command.GenerateColumnModifications() may change own state through call of  _entries.Sort(_comparer);

https://github.com/dotnet/efcore/blob/a1216b1de00f7443a38f8efe3387adfc5d7c21d0/src/EFCore.Relational/Update/ModificationCommand.cs#L271-L274

It is OK from point of multithreaded call of ModificationCommand::get_ColumnModifications?

**Comment by AndriySvyryd** [comment]
The changes are in the right direction, but I assume there are more coming as you still need to remove `IColumnModificationFactory` and introduce `IModificationCommandSource`.

For parameter objects I'd suggest using sealed records instead of structs as they are more refactor-friendly, unless there's a measurable perf benefit.

Also please try to use the code style consistent with other files in this repo (e.g. remove redundant `this.` and "closing" comments like `//struct ColumnModificationParameters`).

**Comment by AndriySvyryd** [comment]
@dmitry-lipetsk What's the benefit of having `ModificationCommandBuilder` separate from `ModificationCommand`?

**Comment by dmitry-lipetsk** [comment]
> @dmitry-lipetsk What's the benefit of having `ModificationCommandBuilder` separate from `ModificationCommand`?

In exact describing of interfaces for each stage.

I removed AddEntry from IModificationCommand interface for prevent modification (as much as possible) of object during its lifetime.

As result - ModificationCommand has become a little easier and more reliable.

In first time, I described CommandModificationBuilder as private (helper) class of CommandBatchPreparer. But the tests use AddEntry, so I rewrote it as a separate class (with virtual methods in public interface). And finally, for avoid any question in future, I added the way for replacing of this class to external implementation (IModificationCommandBuilder, IModificationCommandBuilderFactory).

ModificationCommand may implements both IModificationCommand and IModificationCommandBuilder interfaces. But this unnecessary economy that degrades the internal structure.

---
I hope (in whole) this PR is completed. But I offer also to define IColumnModification interface and restore original ColumnModification (with minimal modifications). In my code I will provide my complete implementation for IColumnModification, that will resolves original issue from #23027.

**Comment by AndriySvyryd** [comment]
> ModificationCommand may implements both IModificationCommand and IModificationCommandBuilder interfaces. But this unnecessary economy that degrades the internal structure.

Separating `ModificationCommand` into a mutable and immutable interfaces makes sense, but making `IModificationCommandBuilder` a separate service from `IModificationCommandBuilderFactory` adds another abstraction layer that doesn't provide any more flexibility in practice.

I'm also concerned about existing providers that have classes derived from `ModificationCommand`, we should preserve the existing members to make the upgrade easier, including `PropagateResults`.  And I don't see any significant improvement in the internal structure due to the separation. Replace `IModificationCommandBuilder` with `IMutableModificationCommand` that derives from `IModificationCommand` and merge `ModificationCommand` with `ModificationCommandBuilder`

Additionally `IModificationCommandFactory` and `IColumnModificationFactory` should be registered as `Singleton` to be able to use them to pool/cache the instances in the future.

**Comment by dmitry-lipetsk** [comment]
Current state [will be updated]

New interfaces
- IColumnModification
- IModificationCommand
- IModificationCommandBuilder

New factories
- IColumnModificationFactory [singleton]
- IModificationCommandFactory [singleton]
- IModificationCommandBuilderFactory [singleton]

New records
- ModificationCommandBuilderFactoryDependencies [singleton]
- ColumnModificationParameters
- ModificationCommandParameters

New classes
- ColumnModificationFactory
- ModificationCommandFactory
- ModificationCommandBuilderFactory

Changes
- ModificationCommand implements IModificationCommand
- ColumnModification implements IColumnModification
- EFCore works with IModificationCommand, IColumnModification

**Beware change (1)**
ModificationCommand.PropagateResults moved to AffectedCountModificationCommandBatch.PropagateResultsToModificationCommand

Reasons
- One point of usage.
- Removing dependence between (source) IModificationCommand and (target) ValueBuffer class
- Reducing size of IModificationCommand interface

**Beware changes (2)**
ModificationCommand.AddEntry moved into IModificationCommandFactory 

Reason
- Prevent modification (as much as possible) of ModificationCommand object during its lifetime at design layer

**Comment by dmitry-lipetsk** [comment]
@AndriySvyryd 

About renaming of xxxFactory to xxxSource.

It is not problem, but I want to understand one thing.

- Factories (expected behavior) creates new instances.
- Sources may return exists instances.

I'm right?

ColumnModification contains the data, which linked with current operation with database (INSERT/UPDATE) - Value, OriginalValue. This prevent to reuse this object in another operations.

Also, ColumnModification uses generator of parameter name. Each operation with database creates own generator.

So, I not see any way for reuse ColumnModification object.

ModificationCommand delivers (newly created) ColumnModification objects. So, each operation with database will create new ModificationCommand object, which linked with new ColumnModification objects.

As result - where and how you are want to reuse these objects (ModificationCommand, ColumnModification)?

**Comment by AndriySvyryd** [comment]
> About renaming of xxxFactory to xxxSource.

> It is not problem, but I want to understand one thing.

> Factories (expected behavior) creates new instances.
Sources may return exists instances.
I'm right?

Yes

> ColumnModification contains the data, which linked with current operation with database (INSERT/UPDATE) - Value, OriginalValue. This prevent to reuse this object in another operations.

> Also, ColumnModification uses generator of parameter name. Each operation with database creates own generator.

> So, I not see any way for reuse ColumnModification object.

> ModificationCommand delivers (newly created) ColumnModification objects. So, each operation with database will create new ModificationCommand object, which linked with new ColumnModification objects.

> As result - where and how you are want to reuse these objects (ModificationCommand, ColumnModification)?

All that state can be reset and the instances returned to the pool. Though resetting it might take longer then just creating a new one. Whether it makes sense to do or not will be determined by benchmarking in the future, for now we want to keep the possibility open.

**Comment by AndriySvyryd** [comment]
@dmitry-lipetsk Are you planning to wrap this up this month? Otherwise I'll take over it.

**Comment by dmitry-lipetsk** [comment]
> @dmitry-lipetsk Are you planning to wrap this up this month? Otherwise I'll take over it.

I don't mind if you make your own adjustments to this patch.

**Comment by AndriySvyryd** [comment]
Superseded by https://github.com/dotnet/efcore/pull/25327

**Pull request closed without merging**
