### PR TITLE
Code cleanup (3)

### PR DESCRIPTION
**Pull request by ajcvickers**

### CODE REVIEW

**Comment by ajcvickers** [comment]
Replaces #34450 with rules changed as required by @AndriySvyryd

**Comment by ajcvickers** [comment]
### Description

Code cleanup before release to ease backporting.

### Customer impact

None.

### How found

N/A

### Regression

N/A

### Testing

N/A

### Risk

Low.

**Review by AndriySvyryd — APPROVED** [review]

**Comment by SamMonoRT** [comment]
IMO - we should avoid such changes in RC1/RC2 -- do we really need this backported to release\9.0?

**Comment by AndriySvyryd** [comment]
@SamMonoRT As @ajcvickers said this is needed in release\9.0 to make is easier to backport future changes. It doesn't have any functional changes, so there's no risk. Why should we avoid changes like this in release\9.0?

**Comment by SamMonoRT** [comment]
It is recommended we don't take any changes other than most necessary regression fixes post RC1 snap. This one looks ok, will need M2 approval.

**Comment by roji** [comment]
Discussed offline, we're OK to merge this (or an equivalent replacing PR, after review).

**Comment by ajcvickers** [comment]
Replaced by #34474

**Pull request closed without merging**
