### PR TITLE
Update to .NET SDK 7 Preview 6

### PR DESCRIPTION
**Pull request by roji**

### CODE REVIEW

**Review by AndriySvyryd — APPROVED** [review]
Seems that we need to wait for the image to be updated first.

With this https://github.com/dotnet/efcore/pull/28328 can be reverted

Also we should add `Timeout` to the `Start-CosmosDbEmulator` call. The default 240 is clearly not enough

**Comment by bricelam** [comment]
Also, can we remove this NoWarn?

https://github.com/dotnet/efcore/blob/d42e736e06c948000da11e6d76a7801d08e92c8b/test/EFCore.AspNet.Specification.Tests/EFCore.AspNet.Specification.Tests.csproj#L12

**Comment by roji** [comment]
> Also we should add Timeout to the Start-CosmosDbEmulator call. The default 240 is clearly not enough

It actually seems to have been relatively green lately, looking at the github actions history....

I don't see a timeout in the [PS docs](https://docs.microsoft.com/en-us/azure/cosmos-db/emulator-command-line-parameters#manage-the-emulator-with-powershell), were you referring to a Github Actions timeout? If so, I'm only seeing [timeout-minutes](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes) which seems to be 360 minutes by default...

**Comment by AndriySvyryd** [comment]
> I don't see a timeout in the [PS docs](https://docs.microsoft.com/en-us/azure/cosmos-db/emulator-command-line-parameters#manage-the-emulator-with-powershell), were you referring to a Github Actions timeout?

It's not documented, but it's there if you open `Microsoft.Azure.CosmosDB.Emulator.psm1`

**Comment by bricelam** [comment]
Ah, they changed the behavior of Arcade to use the system-installed version of dotnet.exe if it's the right version. [This line](https://github.com/dotnet/efcore/blob/2939c9e504f3238b52c189b054574de334550ab2/.github/workflows/TestCosmos.yaml#L30) should probably be changed to something like:
```diff
-         run: .dotnet\dotnet test test\EFCore.Cosmos.FunctionalTests
+         run: |
+           $env:PATH = "$PWD\.dotnet;$env:PATH"
+           dotnet test test\EFCore.Cosmos.FunctionalTests
```

**Comment by bricelam** [comment]
Hmm, never mind. That doesn't really make sense since it's already looking in C:\\Program Files\\dotnet. Maybe they changed the places it looks for runtimes to no longer include directories relative to the running dotnet.exe. Maybe setting DOTNET_HOME would also help.

**Comment by roji** [comment]
Ended up fixing this by using Arcade's test.cmd instead of running dotnet sdk directly, this way it sets up the environment whichever way it likes. Also added -Timeout=360 for the Cosmos Emulator startup, let's see how it goes.

@bricelam suppressing CS8981 still seems necessary, since EFCore.AspNet.Specification.Tests.csproj still contains lowercase-only type aliases in Protobuf auto-generated code, seems like this would have to be fixed on their side (or suppressed by them there specifically) unless I'm missing something.

**Comment by smitpatel** [comment]
> With this https://github.com/dotnet/efcore/pull/28328 can be reverted

This didn't work.

**Pull request merged**
