### PR TITLE
Run tests on .NET 8

### PR DESCRIPTION
**Pull request by bricelam**
@roji I expect we'll need to react to the benchmark changes somewhere...

### CODE REVIEW

**Comment by bricelam** [comment]
(Package mirroring requested)

**Review by AndriySvyryd — APPROVED** [review]

**Comment by bricelam** [comment]
```
dyld : error : Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from : error : /Users/runner/work/1/s/.packages/grpc.tools/2.53.0/tools/macosx_x64/protoc (which was built for Mac OS X 12.5)
  Expected in : error : /usr/lib/libc++.1.dylib
   in /Users/runner/work/1/s/.packages/grpc.tools/2.53.0/tools/macosx_x64/protoc
```

**Comment by bricelam** [comment]
CI version of macOS: 11
.NET 8 min required version: 10.15

**Comment by bricelam** [comment]
Failed with lots of new trimming warnings /cc @roji @ajcvickers

**Comment by JamesNK** [comment]
It's a known issue in Grpc.Tools that it doesn't work in macOS 11: https://github.com/dotnet/aspnetcore/issues/47336

**Comment by bricelam** [comment]
Superseded by PR #31270

**Pull request closed without merging**
