### PR TITLE
[release/8.0] Pass sequence annotations (#33780)

### LINKED ISSUE #33780: Sequence annotations are not passed to code generation
There's infrastructure prepared to have custom annotations on sequences. I need to use it for [EFCore.Snowflake](https://github.com/Sielnix/EFCore.Snowflake). However, when scaffolding DbContext from existing database, sequence annotations are not passed to code generation.

To verify it just extend (fix) test `RelationalScaffoldingModelFactoryTest.Sequences` to include any annotation

```C#
[ConditionalFact]
public void Sequences()
{
    var info = new DatabaseModel
    {
        Sequences =
        {
            new DatabaseSequence
            {
                Database = Database,
                Name = "CountByThree",
                IncrementBy = 3,
                ["CustomAnnotation"] = "Hello there"
            }
        }
    };

    var model = _factory.Create(info, new ModelReverseEngineerOptions());

    Assert.Collection(
        model.GetSequences(), first =>
        {
            Assert.NotNull(first);
            Assert.Equal("CountByThree", first.Name);
            Assert.Equal(3, first.IncrementBy);
            Assert.Null(first.Schema);
            Assert.Null(first.MaxValue);
            Assert.Null(first.MinValue);
            Assert.False(first.IsCyclic);
            Assert.True(first.IsCached);
            Assert.Null(first.CacheSize);
            Assert.Equal("Hello there", first["CustomAnnotation"]);
        });
}
```

Only change is `CustomAnnotation` added and asserted.

Please include fix for that in 8.0.x version.

### Include provider and version information

EF Core version: v8.0.5, 9.0-preview5

### PR DESCRIPTION
**Pull request by Sielnix**
Fixes #33780

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] I've posted a comment on an issue with a detailed description of how I am planning to contribute
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

### CODE REVIEW

**Comment by Sielnix** [comment]
@dotnet-policy-service agree


czw., 23 maj 2024 o 19:15 dotnet-policy-service[bot] <
***@***.***> napisał(a):

**Comment by cincuranet** [comment]
@Sielnix can you please create the PR for `main` branch and we will backport to 8, if it passes the bar. Thanks.

**Comment by Sielnix** [comment]
Thank you @cincuranet , created new PR [33804](https://github.com/dotnet/efcore/pull/33804), this one can be closed.

**Comment by cincuranet** [comment]
Thanks.

**Pull request closed without merging**
