### PR TITLE
Update to 6.0.0-preview5

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by dougbu** [comment]
@ajcvickers looks like the PR pipeline has lost necessary access:
``` text
##[error]
ef-nightly-cosmos-key: "Could not fetch access token for Azure. Verify if the Service Principal used is valid and not expired."
ef-pr-cosmos-test: "Could not fetch access token for Azure. Verify if the Service Principal used is valid and not expired."
```

Is there a quick fix❔

**Comment by ajcvickers** [comment]
@smitpatel @AndriySvyryd Cosmos issues?

**Comment by smitpatel** [comment]
Not really cosmos issue
image

Pipeline is failing to download test secrets (key vault where cosmos keys are stored). KeyVault are associated with the build via the build pipeline in azdo directly.

**Comment by smitpatel** [comment]
Not really cosmos issue
image

Pipeline is failing to download test secrets (key vault where cosmos keys are stored). KeyVault are associated with the build via the build pipeline in azdo directly.

**Comment by wtgodbe** [comment]
@MattGal do we need to update some secrets?

**Comment by mmitche** [comment]
@dotnet/dnceng

**Comment by jonfortescue** [comment]
The issue here is that the client secret on one of our service principals expired yesterday and needs to be regenerated. Trying to find someone who has permissions to regenerate it now.

**Comment by MattGal** [comment]
> The issue here is that the client secret on one of our service principals expired yesterday and needs to be regenerated. Trying to find someone who has permissions to regenerate it now.

We already have Service Connections set up to use instead of these auto-generated ones, hopefully this just got switched over...

**Comment by riarenas** [comment]
@MattGal There was no service connection for the ASPNET test subscription. Will created that on Friday, and we moved this variable group to use it.

**Pull request merged**
