### PR TITLE
Fix22287

### LINKED ISSUE #22287: Scaffolding takes a long time to retrieve Indexes on large databases which causes timeous and scaffolding failure
Reverse-engineering a sufficiently large database utilizes an inefficient query to retrieve indexes which causes the reveng to fail.
The query is emitted (here)[https://github.com/dotnet/efcore/blob/release/5.0/src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs#L842]

Please note that I have a resolution ready to PR if this issue is deemed valid and reasonable.

### Steps to reproduce
\- Obtain a sufficiently large database (note: not the easiest)
\- Attempt to scaffold the context
\- ???
\- Timeout

### Further technical details

EF Core version: 3.1.7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: Net Core 3.1
Operating system: Win10-x64
IDE: VS 2019 16.7.1

### The good stuff

Straight up, our database is a monolith, but I understand we're not alone here. Here is a snapshot of where we stand - 
image

The query to get Indexes, in all its glory, takes over a minute. Anything over 30 seconds is unacceptable given that's the error condition.

By locating the SQL ran by `SqlServerDatabaseModelFactory.GetIndexes()` through MS SQL Profiler and running it myself, the following time is taken:
image

Inspecting the execution plan leads to:
image

And the top-right step of the plan reveals
image

Over 120 million records read for the tight loop here.

### Resolution
In my mind I see three resolution paths.

#### Easiest

Extend the timeout of the DbCommand(s) created such that scaffolding is given a reasonable amount of time to complete (how long is reasonable?)

#### Easy

Refactor the query. I have already done so, with the following result:
image

#### Medium  

Refactor Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations to use DbContextOperations to retrieve the IDesignTimeDbContextFactory<TContext> from the user.*  This allows the user to set arbitrary timeouts by utilizing the DbConnection created by their context, and allow users to specify startup assemblies instead of a connection string.
Note, I have tried to grock through this code within a reasonable amount of time, but to the best of my understanding it does not already take into account the user's design-time factory ([source](https://github.com/dotnet/efcore/blob/release/5.0/src/EFCore.Design/Design/Internal/DatabaseOperations.cs#L36-L58)), while MigrationsOperations does [here](https://github.com/dotnet/efcore/blob/release/5.0/src/EFCore.Design/Design/Internal/MigrationsOperations.cs#L66).

--------------------------------------------

If you guys feel like this is a valid enough issue, I can submit a PR that modifies the query issued by GetIndexes(), which should speed up this process immensely for larger databases while leaving smaller databases unaffected.

### PR DESCRIPTION
**Pull request by svengeance**
Fixes #22287 

This is a light retouching of the query execute by EF to retrieve a list of indexes.
I don't expect to be smarter than the query optimizer in MSSQL in any case, but for some reason it was unable to optimize the tight loop below, and this resulted in exponential rows read.
image

In my work environment, I have the follow counts from the sys.* schema -
image

Given this setup, the current query takes an excess of 30 seconds, which is past the timeout for a DbCommand, and thus I am unable to successfully reverse engineer data.

My proposed query takes about 2 seconds on my large database, and incurs no noticeable overhead for the smaller database. The tests under `Microsoft.EntityFrameworkCore.Scaffolding.SqlServerDatabaseModelFactoryTest` all still pass, which I expect is a reasonable set of tests, but I am more than willing to add additional ones as necessary.

Below is the proposed query. **We may need to make the temp-table name more unique.** Thank you!
```sql

SELECT * INTO #TempIndexes
FROM
(
   SELECT CAST([i].[object_id] AS nvarchar(12)) + '#' + CAST([i].[index_id] AS nvarchar(12))
   FROM [sys].[indexes] i
   JOIN [sys].[tables] AS [t] ON [i].[object_id] = [t].[object_id]
   JOIN [sys].[index_columns] AS [ic] ON [i].[object_id] = [ic].[object_id] AND [i].[index_id] = [ic].[index_id]
   JOIN [sys].[columns] AS [c] ON [ic].[object_id] = [c].[object_id] AND [ic].[column_id] = [c].[column_id]
   WHERE [t].[is_ms_shipped] = 0
AND NOT EXISTS (SELECT *
    FROM [sys].[extended_properties] AS [ep]
    WHERE [ep].[major_id] = [t].[object_id]
        AND [ep].[minor_id] = 0
        AND [ep].[class] = 1
        AND [ep].[name] = N'microsoft_database_tools_support'
    )
AND [t].[name] <> '__EFMigrationsHistory'
AND [t].[temporal_type] <> 1
AND[c].[is_hidden] = 1
AND[i].[is_hypothetical] = 0
) AS TempIndexes([name])
SELECT
    SCHEMA_NAME([t].[schema_id]) AS [table_schema],
    [t].[name] AS [table_name],
    [i].[name] AS [index_name],
    [i].[type_desc],
    [i].[is_primary_key],
    [i].[is_unique_constraint],
    [i].[is_unique],
    [i].[has_filter],
    [i].[filter_definition],
    [i].[fill_factor],
    COL_NAME([ic].[object_id], [ic].[column_id]) AS [column_name],
    [ic].[is_included_column]
FROM [sys].[indexes] AS [i]
JOIN [sys].[tables] AS [t] ON [i].[object_id] = [t].[object_id]
JOIN [sys].[index_columns] AS [ic] ON [i].[object_id] = [ic].[object_id] AND [i].[index_id] = [ic].[index_id]
JOIN [sys].[columns] AS [c] ON [ic].[object_id] = [c].[object_id] AND [ic].[column_id] = [c].[column_id]
WHERE [i].[is_hypothetical] = 0
AND [t].[is_ms_shipped] = 0
AND NOT EXISTS (SELECT *
    FROM [sys].[extended_properties] AS [ep]
    WHERE [ep].[major_id] = [t].[object_id]
        AND [ep].[minor_id] = 0
        AND [ep].[class] = 1
        AND [ep].[name] = N'microsoft_database_tools_support'
    )
AND [t].[name] <> '__EFMigrationsHistory'
AND [t].[temporal_type] <> 1
AND CAST([i].[object_id] AS nvarchar(12)) + '#' + CAST([i].[index_id] AS nvarchar(12)) NOT IN
(
	SELECT * FROM #TempIndexes ti
)
ORDER BY [table_schema], [table_name], [index_name], [ic].[key_ordinal]
DROP TABLE #TempIndexes
```

### CODE REVIEW

**Comment by svengeance** [comment]
@ErikEJ You were interested in this on the issue

**Comment by ErikEJ** [comment]
SQL Server takes care of the temp table name uniqueness.

LGTM

None of the other schema queries were causing issues?

**Comment by svengeance** [comment]
Not that I am aware of - before we close this PR let me do some legwork and run all of the queries necessary for scaffolding against my large database, and I'll report back.

**Comment by ErikEJ** [comment]
Don't hold your breath, this PR will not go into 5.0 I'm sure.

**Comment by svengeance** [comment]
I fully expect it to be too late to make it into 5.0. I am working with our internal DB team on a resolution in the interim. Worst case scenario I will rebuild dotnet-ef and distribute the tool internally with the updated `Microsoft.SqlServer.Design.dll`

**Comment by smitpatel** [comment]
@svengeance - You should be able to easily replace `IDatabaseModelFactory` with your custom `SqlServerDatabaseModelFactory` which contains your fix, even without having to put any custom build of EF in your project.

**Comment by svengeance** [comment]
> 
> 
> @svengeance - You should be able to easily replace `IDatabaseModelFactory` with your custom `SqlServerDatabaseModelFactory` which contains your fix, even without having to put any custom build of EF in your project.

I will take a look. Given that I am using the reverse generation UI tool built by @ErikEJ I am unsure if I have that capability to hook into the services provider, but I will give it a shot and see what I see. Thank you for the lead.

Speaking of - Erik, I have individually ran each of the follow queries necessary for scaffolding on my supersized DB, and nothing took longer than 3 seconds to execute.
image

**Comment by ErikEJ** [comment]
Correct, EF Core Power Tools does not (currently) allow you to replace services.

**Comment by svengeance** [comment]
Thanks Erik - I didn't think so, but you saved me some time searching. Might make a snazzy feature for advanced use-cases like this.

Just a note regarding this PR and an attempt to repro the issue - I've generated a database using a [quick-and-dirty tool I made](https://github.com/svengeance/DirtyDatabaseGenerator) to populate a database with an arbitrary number of tables, columns, indexes, and rows. With a fresh MSSQL install on localDB the existing query runs just fine for very plain databases (I configured it for roughly 500 tables, 20 columns, 10 indexes, and 500 rows of data per table). I'm unsure at this time if there's something simply wrong with our database at work, but I doubt there's such a fundamental issue given its overall health and performance.

**Comment by ErikEJ** [comment]
Interesting - what SQL Server build version and Edition is your production database?

**Comment by svengeance** [comment]
Microsoft SQL Server 2017 (RTM-CU19) (KB4535007) - 14.0.3281.6 (X64)
Jan 23 2020 21:00:04
Copyright (C) 2017 Microsoft Corporation
Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

In my latest attempt at repro steps I took our database and scripted it out using Tasks->Generate Script, grabbing all schemas, tables, and indexes. Applying this script to a new database **on the same server** and running the current Index-Retrieval script on it works just fine.

I'm lead to believe that it is not a raw numbers issue with respect to schema, but something that accrues over time with the use of indexes. Unfortunately I do not understand the internals of the systems tables such as `sys.sysidxstats` to have much confidence here

**Comment by ErikEJ** [comment]
>> Thanks Erik - I didn't think so, but you saved me some time searching. Might make a snazzy feature for advanced use-cases like this.

This is already logged here: https://github.com/ErikEJ/EFCorePowerTools/issues/427 - but I am reluctant to consider this an "advanced use case".

**Comment by ErikEJ** [comment]
I did some more testing, and with a sufficient amount of columns, I can make the GetColumns query timeout, so this PR does not fix the underlying issue of timeouts.

Suggest using Microsoft.Data.SqlClient 2.1 instead (which has "Command Timeout" connection string property). Available as preview by the end this month, and RTM planned for end November.

(I admit I tested with SQL Express 2017 and a database with 2 million columns)

**Comment by svengeance** [comment]
Well this PR strictly addresses GetIndexes; even with the monolithic database I have (and probably the other user on the Issue had), the timeout was never about GetColumns.

At this point the PR is a tossup between the complexity of the code with respect to the generated query, and how much time it saves on X number of users. It certainly works and addresses **a** scenario where the default configuration of EF will fail to reverse generate. What's the value on that and is it worth it?

**Comment by ErikEJ** [comment]
FWIW, Microsoft.Data.SqlClient 2.1.0-preview2 is now out, which allows you to create a connection string to override the default command timeout of 30 seconds:

   "Data Source=(local);Integrated Security=true;Initial Catalog=Chinook;Command Timeout=300"

https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.0-preview2.20297.7

**Comment by ErikEJ** [comment]
@smitpatel What are the plans for this PR?

**Comment by smitpatel** [comment]
Need to verify proper access rights for creating temp tables. If it requires any permissions then changing script could break people.

**Comment by ErikEJ** [comment]
@smitpatel there are no limitations 

https://www.google.com/amp/s/jasonstrate.com/2013/05/21/security-questions-what-permissions-are-required-to-create-temporary-tables/amp/

**Comment by svengeance** [comment]
For what it's worth I've been using this modified version with EF Core Power Tools for the past few months with my hefty DB and have had no issues. @ErikEJ I'm still using your nightly releases, but has this been promoted into the main release channel and has anyone reported any issues?

**Comment by ErikEJ** [comment]
@svengeance The fix was in EF Core Power Tools for a while, and I never heard of any issues with the  fix, but I removed it from the latest release. EF Core Power Tools now rely on "Command Timeout" with Microsoft.Data.SqlClient 2.1.0 instead, in order to avoid pulling too much EF Core code into Power Tools. https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/RevEng.Core/TableListBuilder.cs#L37

**Comment by ErikEJ** [comment]
I would be great if this could be shipped with EF Core 6, as it would make EF Core Power Tools more responsive when working with large databases.

**Comment by smitpatel** [comment]
I looked at existing query and modified query in detail. Sadly, I cannot get a proper repro no northwind/adventureworks due to not really large data. This behavior causes an interesting question that why it is happening this way. Is the computation of a subquery happening for each row? If that is the case should we avoid all the subqueries in the scaffolding scripts.
Further, looking at temp table definition and how it is used, it should be written using CTE rather than temp table. Given temp table is not being used outside the scope of this one particular query, CTE saves on write. Again I couldn't get statistics for this compared to temp table query due to not large enough database. For me temp table query is the slowest to fetch data for now.

@svengeance - Would you be able to test out query with CTE and see how it performs?

```SQL
WITH tempindexes([name])
AS (
	SELECT CAST([i].[object_id] AS nvarchar(12)) + '#' + CAST([i].[index_id] AS nvarchar(12))
	FROM [sys].[indexes] i
	JOIN [sys].[tables] AS [t] ON [i].[object_id] = [t].[object_id]
	JOIN [sys].[index_columns] AS [ic] ON [i].[object_id] = [ic].[object_id] AND [i].[index_id] = [ic].[index_id]
	JOIN [sys].[columns] AS [c] ON [ic].[object_id] = [c].[object_id] AND [ic].[column_id] = [c].[column_id]
	WHERE [t].[is_ms_shipped] = 0
		AND NOT EXISTS (
			SELECT *
			FROM [sys].[extended_properties] AS [ep]
			WHERE [ep].[major_id] = [t].[object_id]
				AND [ep].[minor_id] = 0
				AND [ep].[class] = 1
				AND [ep].[name] = N'microsoft_database_tools_support')
		AND [t].[name] <> '__EFMigrationsHistory'
		AND [t].[temporal_type] <> 1
		AND [c].[is_hidden] = 1
		AND [i].[is_hypothetical] = 0)
SELECT
    SCHEMA_NAME([t].[schema_id]) AS [table_schema],
    [t].[name] AS [table_name],
    [i].[name] AS [index_name],
    [i].[type_desc],
    [i].[is_primary_key],
    [i].[is_unique_constraint],
    [i].[is_unique],
    [i].[has_filter],
    [i].[filter_definition],
    [i].[fill_factor],
    COL_NAME([ic].[object_id], [ic].[column_id]) AS [column_name],
    [ic].[is_included_column]
FROM [sys].[indexes] AS [i]
JOIN [sys].[tables] AS [t] ON [i].[object_id] = [t].[object_id]
JOIN [sys].[index_columns] AS [ic] ON [i].[object_id] = [ic].[object_id] AND [i].[index_id] = [ic].[index_id]
JOIN [sys].[columns] AS [c] ON [ic].[object_id] = [c].[object_id] AND [ic].[column_id] = [c].[column_id]
WHERE [i].[is_hypothetical] = 0
	AND [t].[is_ms_shipped] = 0
	AND NOT EXISTS (
		SELECT *
		FROM [sys].[extended_properties] AS [ep]
		WHERE [ep].[major_id] = [t].[object_id]
			AND [ep].[minor_id] = 0
			AND [ep].[class] = 1
			AND [ep].[name] = N'microsoft_database_tools_support')
	AND [t].[name] <> '__EFMigrationsHistory'
	AND [t].[temporal_type] <> 1
	AND CAST([i].[object_id] AS nvarchar(12)) + '#' + CAST([i].[index_id] AS nvarchar(12)) NOT IN (
		SELECT * FROM tempindexes
	)	
ORDER BY [table_schema], [table_name], [index_name], [ic].[key_ordinal]
```

**Comment by svengeance** [comment]
Hey @smitpatel - thanks for following up. Running the query above with the CTE produces a similar time to the default query emitted by the reverse generator, about 37-40 seconds, with the same bottleneck on sys.sysidxstats
image

Re-running the temp-table-based query produces the same sub-second query time as before.

Let me know how else I can help.

**Comment by ErikEJ** [comment]
Have you tried updating statistics?

UPDATE STATISTICS sys.sysidxstats WITH FULLSCAN;

**Comment by svengeance** [comment]
Done with no change I'm afraid.

Would it be worth me getting in touch with a group dedicated to MSSQL engine to see if there's a likely reason our databases have this difference? It bothers me that there is no trivial way to repro this.

**Comment by ErikEJ** [comment]
Best repro would be to share a schema script, potentially with statistics.

**Comment by svengeance** [comment]
When this issue first occurred some 8 months ago I didn't have permission to share much about the database unfortunately, and I'm unlikely to get it now since this is no longer a blocking issue (thanks to the connection-string-based-command-timeouts).

For what it's worth - I have also tried these scripts on a schema-only copy of our database (we have one regularly staged for testing) and it had no issues running there. 

The only other person I've seen have the issue (and have it resolved) was @LynxWall (chimed in on the issue #22287).

Unfortunately trying to understand how and why these tables work is a pain in the butt... https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/system-base-tables?view=sql-server-ver15#system-base-table-metadata

**Comment by ajcvickers** [comment]
Based on this thread and discussion with the team, we are closing this PR for now. We will still track the issue in #22287 and may revisit this based on further info/feedback.

**Comment by svengeance** [comment]
I think that's a fair call - I wasn't able to glean anything more from selecting data from these indexes unfortunately. If you need more information outside of the full schema or want to verify other approaches in the future, let me know.

**Pull request closed without merging**
