### PR TITLE
switched the unary expression type and operand type in the check

### LINKED ISSUE #18658: Contains on a readonly collection throws InvalidOperation exception.
A query that uses a `collection.Contains` will fail when the collection is marked `readonly`. It works as expected without the `readonly`.

### Steps to reproduce

```csharp
public class QueryTests
{
    // If this is marked "readonly", the query will fail. Remove "readonly" and it works.
    static readonly IEnumerable<TagCategoryType> Types =
        new TagCategoryType[] { TagCategoryType.Custom, TagCategoryType.Subject };

    [TestMethod]
    public void EFCoreQuery_WhereIn()
    {
        using var db = GetContext();
        var tags = db.Set<Tag>()
            .Where(t => Types.Contains(t.Type))
            .ToList();

        Assert.IsNotNull(tags);
        Assert.IsTrue(tags.Count > 0);
    }
}
```

#### Exception
```
Message: 
    Test method Enroller.Tests.Dev.EntityFrameworkCore.QueryTests.EFCoreQuery_WhereIn threw exception: 
    System.InvalidOperationException: Processing of the LINQ expression 'AsQueryable<TagCategoryType>((IEnumerable<TagCategoryType>)TagCategoryType[] { Custom, SecurityGroup, })' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
  Stack Trace: 
    NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    NavigationExpandingExpressionVisitor.ExpandNavigationsInExpression(NavigationExpansionExpression source, Expression expression)
    NavigationExpandingExpressionVisitor.ExpandNavigationsInLambdaExpression(NavigationExpansionExpression source, LambdaExpression lambdaExpression)
    NavigationExpandingExpressionVisitor.ProcessWhere(NavigationExpansionExpression source, LambdaExpression predicate)
    NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    NavigationExpandingExpressionVisitor.ExpandAndReduce(Expression query, Boolean applyInclude)
    NavigationExpandingExpressionVisitor.Expand(Expression query)
    QueryTranslationPreprocessor.Process(Expression query)
    QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
    Database.CompileQuery[TResult](Expression query, Boolean async)
    QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
    <>c__DisplayClass9_0`1.<Execute>b__0()
    CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
    CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
    QueryCompiler.Execute[TResult](Expression query)
    EntityQueryProvider.Execute[TResult](Expression expression)
    EntityQueryable`1.GetEnumerator()
    List`1.ctor(IEnumerable`1 collection)
    Enumerable.ToList[TSource](IEnumerable`1 source)
   ```

### Further technical details

EF Core version: 3.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET Core 3.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3

### PR DESCRIPTION
**Pull request by andreichuk**
fixes #18658

### CODE REVIEW

**Comment by ajcvickers** [comment]
@andreichuk You'll need to add tests that verify this fix, and also make sure all other tests are passing.

**Comment by smitpatel** [comment]
This is incorrect fix.

**Comment by andreichuk** [comment]
> This is incorrect fix.

could you please provide more details why it is incorrect so I can try to adjust the code?

**Comment by ajcvickers** [comment]
@andreichuk At this point, I don't think we know what the correct fix is here. This will require debugging of the code to figure out the root cause, followed by or at the same time as adding new tests to cover the issue filed and any related scenarios that might be effected. We will of course do this work when we fix the bug. However, if you want to send a PR to fix it sooner, then that would be appreciated, but this is going to require that you figure out the root cause and correct fix and add appropriate tests to verify this.

**Comment by ajcvickers** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
