### PR TITLE
Add fill factor to keys and unique constraints

### LINKED ISSUE #32803: SqlServer FillFactor for PK is missing
"FillFactor" was added several versions ago but it is incomplete/broken.
.HasFillFactor() is only settable on explicit/defined Indexes.
In SqlServer, FillFactor can be set on the PK without additional complexity to the Schema.
This is not available with the FillFactor implementation of EFC 8. 
This is an incomplete implementation of the feature which is why I am filing as a bug and not as a feature request.

To advertise FillFactor is supported in EF, code like this:
```C#
builder.HasKey(x => x.Id).HasFillFactor(90);
```
Should produce Sql Schema as:
```sql
CREATE TABLE [dbo].[MyTable](
	[Id] [int] IDENTITY(1,1) NOT NULL
 CONSTRAINT [PK_MyTable] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
```

or at a minimum, provide a fluent option that ultimately executes the following sql as it will cover the PK:
```sql
ALTER TABLE MyTable REBUILD WITH (FILLFACTOR = 90);
GO
```

EF Core version: 8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0
Operating system: Win10
IDE: Visual Studio 2022 17.4

### PR DESCRIPTION
**Pull request by deano-hunter**
Add a fill factor to keys and unique contraints for SqlServer to work with the HasFillFactor extension method.

Fixes #32803

- [X] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [X] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [X] The code builds and tests pass locally (also verified by our automated build checks)
- [X] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Code follows the same patterns and style as existing code in this repo

### CODE REVIEW

**Comment by deano-hunter** [comment]
@dotnet-policy-service agree company="Scott Logic"

**Review by AndriySvyryd — APPROVED** [review]

**Comment by ajcvickers** [comment]
@AndriySvyryd Any reason you didn't merge this after reviewing?

**Comment by AndriySvyryd** [comment]
@ajcvickers It wasn't assigned to me 😉

**Comment by ajcvickers** [comment]
@deano-hunter Thanks for the contribution!

**Pull request merged**
