### PR TITLE
Update branding to preview4

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by AraHaan** [comment]
So preview.3 is out now? Does this mean that my PR that is yet to be merged with a fix will make it into preview4 when it gets merged (if it does, it fixes a crash in the tool when running with only .NET 6+ runtimes installed)?

**Comment by dougbu** [comment]
@AraHaan yes, preview3 is now available. See https://dotnet.microsoft.com/en-us/download/dotnet/7.0

I have no context on #27671 nor the problem you're attempting to solve. Unless the PR is merged tomorrow, it won't be in preview4.

**Comment by AraHaan** [comment]
> I have no context on #27671 nor the problem you're attempting to solve. Unless the PR is merged tomorrow, it won't be in preview4.

It fixes an crash in ``dotnet ef dbcontext list/scaffold`` which basically makes it unable to load for some reason ``System.Runtime 6.0.0``: https://github.com/dotnet/efcore/issues/27660 The PR fixes it by setting both parts of the tools to .NET 6 at minimum and to both roll forward in case they are not installed to the latest installed runtime.

**Review by smitpatel — APPROVED** [review]

**Comment by bricelam** [comment]
@AraHaan I get the feeling that you're trying to use features way too early in the release cycle. You might want to consider waiting for a Release Candidate (RC). Many of the 7.0 features are still very much in development and the experience of using them is going to be very rough. Also, we'll probably break any code that you do manage to get working since each of the features still have to go through a rigorous API Review process that usually ends up changing the names and shape of the public APIs.

**Review by bricelam — APPROVED** [review]

**Pull request merged**
