### PR TITLE
[preview7] Unpin Microsoft.Extensions.Caching.Memory and Microsoft.Extensions.Logging

### PR DESCRIPTION
**Pull request by mmitche**
Fixes https://github.com/dotnet/efcore/issues/25148

### CODE REVIEW

**Comment by mmitche** [comment]
@bricelam @ajcvickers FYI...this is current blocking p7.

**Comment by mmitche** [comment]
@AndriySvyryd, since @bricelam is on vacation, can you take a look?

**Comment by smitpatel** [comment]
It is failing OData related breaking changes.

**Comment by dougbu** [comment]
> It is failing OData related breaking changes.

Looks very much like the failures in #25323. I'm hoping an ASP.NET update will react more completely to the logging API changes. But, it's possible we need OData to react first.

**Comment by AndriySvyryd** [comment]
@mmitche You can disable `EFCore.OData.FunctionalTests` in p7 and we'll deal with this later in main.

**Comment by mmitche** [comment]
> @mmitche You can disable `EFCore.OData.FunctionalTests` in p7 and we'll deal with this later in main.

Can you do that? (you should have perms to push to this PR). I'm not familiar with the infra.

**Comment by dougbu** [comment]
> @mmitche You can disable EFCore.OData.FunctionalTests in p7 and we'll deal with this later in main.

Not a great idea because dotnet/runtime#54581 was checked in long before that repo branched for preview7. We're going to end up with incoherent runtime dependencies in the efcore packages. See also #25244 which could 'a, should 'a reacted to the runtime changes.

**Comment by dougbu** [comment]
Ahhhhh&hellip;

This repo doesn't use the removed `skipEnabledCheck:` parameter in `LoggerMessage.Define(...)` calls as far as I can tell. The issue is building against ASP.NET Core bits (either from the preview6 SDK or transitively through OData because it builds against `net5.0` or `netcoreapp3.1`) that _do_ use that parameter.

If compatibility w/ OData isn't required, suggest building with a preview 7 SDK that brings in post-break ASP.NET Core bits.

**Comment by ericstj** [comment]
Exception looks to me like it's coming from https://github.com/dotnet/efcore/blob/main/test/EFCore.OData.FunctionalTests/EFCore.OData.FunctionalTests.csproj

According to the stack trace the offending caller is `Microsoft.AspNetCore.Mvc.MvcCoreLoggerExtensions` which comes from `Microsoft.AspNetCore.Mvc.Core.dll`.

Suspect that project is picking up the new Logging assembly, but running on older ASP.NET core.  Is it possible that this test is on latest runtime shared framework but stale ASP.NETCore shared framework?

**Comment by dougbu** [comment]
> Suspect that project is picking up the new Logging assembly

Agreed. This PR brings in the latest and greatest preview 7 Logging package but a preview 6 SDK. That SDK pulls in older ASP.NET Core bits.

**Comment by mmitche** [comment]
> > Suspect that project is picking up the new Logging assembly
> 
> Agreed. This PR brings in the latest and greatest preview 7 Logging package but a preview 6 SDK. That SDK pulls in older ASP.NET Core bits.

Update to a newer SDK in this PR?

**Comment by dougbu** [comment]
> Update to a newer SDK in this PR?

Plz

**Comment by mmitche** [comment]
LE SIGH `artifacts\obj\EFCore.Abstractions\Release\net6.0\EFCore.Abstractions.ImplicitNamespaceImports.cs(2,1): error CS8773: (NETCORE_ENGINEERING_TELEMETRY=Build) Feature 'global using directive' is not available in C# 9.0. Please use language version 10.0 or greater.`

**Comment by AndriySvyryd** [comment]
> LE SIGH artifacts\obj\EFCore.Abstractions\Release\net6.0\EFCore.Abstractions.ImplicitNamespaceImports.cs(2,1): error CS8773: (NETCORE_ENGINEERING_TELEMETRY=Build) Feature 'global using directive' is not available in C# 9.0. Please use language version 10.0 or greater.

Change `<LangVersion>9.0</LangVersion>` to 10.0 in `Directory.Build.props` ?

**Comment by mmitche** [comment]
@ajcvickers Can you have someone look at this? It's currently blocking shipping of p7.

**Comment by Pilchie** [comment]
@bricelam - if you're around, can you take a look at this one?

**Comment by AndriySvyryd** [comment]
Seems that we need to react to nullability changes. I can do it in about 2 hours, when I get home.

**Comment by AndriySvyryd** [comment]
2 tests fail to compile now. Filed https://github.com/dotnet/runtime/issues/56285

**Review by AndriySvyryd — APPROVED** [review]

**Review by ajcvickers — APPROVED** [review]

**Comment by lukas-lansky** [comment]
@AndriySvyryd @ajcvickers Thanks for the approvals! Can we merge this now to start the flow that would end in a coherent build? (I don't have rights.)

**Comment by ajcvickers** [comment]
Thanks all! This is now merged.

**Comment by mmitche** [comment]
Thanks @ajcvickers!

**Comment by dougbu** [comment]
Just curious: How did this get in while dotnet/runtime#56285 is open❔ Checks here were green.

**Comment by mmitche** [comment]
> Just curious: How did this get in while dotnet/runtime#56285 is open❔ Checks here were green.

Looks like those couple places got commented out.

**Comment by AndriySvyryd** [comment]
> Looks like those couple places got commented out.

Yes, the break didn't look like a ship-stopper

**Pull request merged**
