### PR TITLE
[release/6.0-preview6] Unpin Microsoft.Extensions.Logging

### PR DESCRIPTION
**Pull request by bricelam**
Part of #25148

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Review by AndriySvyryd — APPROVED** [review]

**Comment by bricelam** [comment]
I've tried a few different things, but I keep getting this error:

> C:\Projects\efcore\All.sln(2,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 2, position 1.

What I've tried:
* Updating the SDK to Preview 6
* Staying on the Preview 4 SDK and updating Microfot.NETCore.App to Preview 6

Staying on Preview 4 gives us the same error we pinned for in the first place:

> System.MethodAccessException : Attempt by method 'System.Text.ValueStringBuilder.AppendSlow(System.String)' to access method 'System.String.CopyTo(System.Span`1`<Char>)' failed.

**Comment by dougbu** [comment]
Strange failures with the All.sln file and that hasn't changed since mid December. The newer SDK doesn't seem to like that file for some reason. Perhaps try the `6.0.100-preview.6.21313.2` SDK❔ That's where we're at in dotnet/aspnetcore but, then again, we don't use the solution file in CI builds.

**Comment by bricelam** [comment]
Any ideas @rainersigwald?

**Comment by bricelam** [comment]
> try the 6.0.100-preview.6.21313.2 SDK

Weird. That seems to work 🤷‍♂️

**Comment by rainersigwald** [comment]
This is a regression in preview6 builds that will be fixed by dotnet/sdk#18526. cc @rokonec for another test case after the `dotnet/installer` one.

You can work around the issue by setting the environment variable `DOTNET_CLI_DO_NOT_USE_MSBUILDNOINPROCNODE=1`, or (as you discovered) use a preview6 build from before the regression went into SDK (and the final preview6 build should also be fine).

**Comment by mmitche** [comment]
@bricelam Do you need p6? Could the shipping p5 work instead?

**Comment by bricelam** [comment]
> Do you need p6?

We need the p6 *runtime* for the tests to pass.

I think I found a combination that'll work. 🤞

**Comment by mmitche** [comment]
> > Do you need p6?
> 
> We need the p6 _runtime_ for the tests to pass.
> 
> I think I found a combination that'll work. 🤞

sounds good.

Usually most repos are using the following pattern to install the runtime that just flowed to the repo: https://github.com/dotnet/sdk/blob/main/global.json#L6

Then then flow that via this dependency: https://github.com/dotnet/sdk/blob/main/eng/Version.Details.xml#L33-L36

I think efcore doesn't strictly need to flow the runtime on every commit, just needs to have one such that the tests will pass. So if this pattern was used, we would remove it after RTM.

**Comment by bricelam** [comment]
Oops, hope I didn't step on your toes, @mmitche. Look like we both effectively just rebased...

**Comment by mmitche** [comment]
No problem. There's another flow from runtime I think, so it will align itself.

**Pull request merged**
