### PR TITLE
[master] Update hosted and BYOC agents used in our builds

### PR DESCRIPTION
**Pull request by dougbu**
- dotnet/aspnetcore-internal#3540
- nit: Consistently use `in` / `notin` with `Build.Reason`
  - YAML was inconsistent and this aligns w/ the Arcade code

### CODE REVIEW

**Comment by dougbu** [comment]
@bricelam @smitpatel @ajcvickers Helix testing here seems to miss some older supported OSes, macOS 10.13 and Linux 16.04 in particular. Should I switch things around a bit there too (in this PR and the upcoming one for 5.0 Preview2)? If yes, do you prefer I add queues for the earlier releases or switch to test there?

**Comment by smitpatel** [comment]
Leave current queues as is. File a new issue which others should we consider.

**Comment by dougbu** [comment]
#20218

**Comment by Pilchie** [comment]
Looks ok except the conflicts.

**Comment by Pilchie** [comment]
Ah - can be merged, can't be squashed.  I didn't know GitHub showed conflicts differently.

**Pull request merged**
