### PR TITLE
Simplify and improve null semantics rewrites

### PR DESCRIPTION
**Pull request by ranma42**
This PR contains:
 - exhaustive testing of null rewrites
 - a simpler implementation of the rewrite, which instead of hand-coding all of the cases, combines the generic case and the already available simplifications
 - a more generic translation of the rewrite optimized for predicates, which simplifies some existing tests.

### CODE REVIEW

**Comment by ranma42** [comment]
These changes stemmed from #34048, in particular the testing part.

**Comment by ranma42** [comment]
Note that the translation is (mostly) the same as before:
```csharp
x == y
```
in C# translates to the SQL expression
```sql
(x = y AND x IS NOT NULL AND y IS NOT NULL) OR (x IS NULL AND y IS NULL)
```

other translations are possible, such as:
```sql
CASE
  WHEN x = y OR (x IS NULL AND y IS NULL) THEN TRUE
  ELSE FALSE
END
```
(or, which is essentially the same `COALESCE(x = y OR (x IS NULL AND y IS NULL), FALSE)`). This is basically using the translation optimized for predicates and covering the NULL cases with `ELSE` or `COALESCE`. This might further cleanup the SqlServer translations such as:
```sql
SELECT [e].[Id], CASE
    WHEN [e].[NullableIntA] = [e].[IntB] AND [e].[NullableIntA] IS NOT NULL THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END AS [X]
FROM [Entities1] AS [e]
```
but maybe it is better to tackle this in other ways (for example changing how the pipeline runs, so that the `SearchConditionConvertingExpressionVisitor` can inform the `NullProcessor` that an expression is within a predicate).

**Comment by maumar** [comment]
now that is one hell of a simplification! 🎉  RIP truth tables (ຈ ﹏ ຈ )

**Review by maumar — APPROVED** [review]

**Comment by maumar** [comment]
AWESOME stuff, thanks a lot @ranma42 !

**Comment by ranma42** [comment]
> now that is one hell of a simplification! 🎉 RIP truth tables (ຈ ﹏ ຈ )

They are useful, but as much as possible I would like to leave that approach to machines (they are much better than people at exhaustively checking that all of the cases match the expectations 😉 )

**Pull request merged**
