### PR TITLE
Αccount for new Queryable.ElementAt/Take overloads

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Updates the reflection code so that the newly added Queryable overloads in https://github.com/dotnet/runtime/issues/28776 are tolerated.

### CODE REVIEW

**Comment by roji** [comment]
Would probably be better to wait until these new APIs are merged and the runtime dependency is flown to EF Core, this way we can add the proper tests.

**Comment by smitpatel** [comment]
Also add the members for new methods & update EnumerableMethods.

**Comment by eiriktsarpalis** [comment]
> Also add the members for new methods & update EnumerableMethods.

The scope of my change is to prevent the existing code from breaking when the new changes are rolled out. I leave it to the maintainers of efcore to determine if and how they want to support the new queryable methods.

**Comment by smitpatel** [comment]
What I mentioned is in the scope of new method overloads being added in LINQ. It is not about adding support for those operators.

**Comment by smitpatel** [comment]
Superseded by #24090

**Pull request closed without merging**
