### PR TITLE
[6.0] Fix API docs errors

### LINKED ISSUE #23260: API xref errors
**Microsoft.EntityFrameworkCore.Design/OperationExecutor+GetMigrations**
 Cross reference not found: 'Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddDbContext'.
**Microsoft.EntityFrameworkCore.Design/OperationExecutor+UpdateDatabase**
 Cross reference not found: 'Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.AddDbContext'.
**Microsoft.EntityFrameworkCore.Diagnostics/DbTransactionInterceptor**
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransaction'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransactionAsync'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransaction'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransactionAsync'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransaction'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransactionAsync'.
**Microsoft.EntityFrameworkCore.Diagnostics/IDbTransactionInterceptor**
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransaction'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransactionAsync'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransactionAsync'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransactionAsync'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransaction'.
 Cross reference not found: 'RelationalDatabaseFacadeExtensions.UseTransaction'.
**Microsoft.EntityFrameworkCore.Diagnostics/ISaveChangesInterceptor**
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAync'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChanges'.
**Microsoft.EntityFrameworkCore.Diagnostics/SaveChangesInterceptor**
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
**Microsoft.EntityFrameworkCore.Infrastructure/CosmosDbContextOptionsBuilder**
 Cross reference not found: 'CosmosDbContextOptionsExtensions.UseCosmos{TContext}'.
**Microsoft.EntityFrameworkCore.Metadata.Builders/EntityTypeBuilder**
 Cross reference not found: 'HasIndex'.
**Microsoft.EntityFrameworkCore.Metadata.Builders/OwnedNavigationBuilder2**
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
 Cross reference not found: 'WithOwner'.
**Microsoft.EntityFrameworkCore.Metadata/LazyLoaderParameterBindingFactory**
 Cross reference not found: 'Microsoft.EntityFrameworkCore.Metadata.LazyLoaderParameterBindingFactory.IsLazyLoader(System.Type)'.
**Microsoft.EntityFrameworkCore.Metadata/SqlQueryExtensions**
 Cross reference not found: 'RelationalEntityTypeBuilderExtensions.ToSqlQuery'.
**Microsoft.EntityFrameworkCore.Metadata/StoreObjectIdentifier**
 Cross reference not found: 'RelationalEntityTypeBuilderExtensions.ToSqlQuery'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/CrossApplyExpression**
 Cross reference not found: 'Table'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/CrossJoinExpression**
 Cross reference not found: 'Table'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/ExceptExpression**
 Cross reference not found: 'Source1'.
 Cross reference not found: 'Source2'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/InnerJoinExpression**
 Cross reference not found: 'Table'.
 Cross reference not found: 'JoinPredicate'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/IntersectExpression**
 Cross reference not found: 'Source1'.
 Cross reference not found: 'Source2'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/LeftJoinExpression**
 Cross reference not found: 'Table'.
 Cross reference not found: 'JoinPredicate'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/OuterApplyExpression**
 Cross reference not found: 'Table'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/SelectExpression**
 Cross reference not found: 'Alias'.
**Microsoft.EntityFrameworkCore.Query.SqlExpressions/UnionExpression**
 Cross reference not found: 'Source1'.
 Cross reference not found: 'Source2'.
**Microsoft.EntityFrameworkCore.Query/IMemberTranslator**
 Cross reference not found: 'MemberExpression.Type'.
**Microsoft.EntityFrameworkCore.Query/IMemberTranslatorProvider**
 Cross reference not found: 'MemberExpression.Type'.
**Microsoft.EntityFrameworkCore.Query/QueryableMethods**
 Cross reference not found: 'Queryable.Average'.
 Cross reference not found: 'Queryable.Average'.
 Cross reference not found: 'Queryable.Sum'.
 Cross reference not found: 'Queryable.Sum'.
 Cross reference not found: 'Queryable.Average'.
 Cross reference not found: 'Queryable.Average'.
 Cross reference not found: 'Queryable.Sum'.
 Cross reference not found: 'Queryable.Sum'.
**Microsoft.EntityFrameworkCore.Storage/ReaderColumn**
 Cross reference not found: 'System.Func{DbDataReader, Int32[], T}'.
 Cross reference not found: 'System.Func{DbDataReader, Int32[], T}'.
**Microsoft.EntityFrameworkCore.Storage/RelationalTypeMappingSource**
 Cross reference not found: 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingInfo@)'.
 Cross reference not found: 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingInfo@)'.
**Microsoft.EntityFrameworkCore.Storage/TypeMappingSource**
 Cross reference not found: 'Microsoft.EntityFrameworkCore.Storage.TypeMappingSourceBase.FindMapping(Microsoft.EntityFrameworkCore.Storage.TypeMappingInfo@)'.
**Microsoft.EntityFrameworkCore.Storage/TypeMappingSourceBase**
 Cross reference not found: 'Microsoft.EntityFrameworkCore.Storage.TypeMappingSourceBase.FindMapping(Microsoft.EntityFrameworkCore.Storage.TypeMappingInfo@)'.
**Microsoft.EntityFrameworkCore/DbContext**
 Cross reference not found: 'SaveChanges'.
 Cross reference not found: 'SaveChangesAsync'.
 Cross reference not found: 'SaveChanges'.
 Cross reference not found: 'SaveChangesAsync'.
 Cross reference not found: 'SaveChanges'.
 Cross reference not found: 'SaveChangesAsync'.
**Microsoft.EntityFrameworkCore/IDbContextFactory`1**
 Cross reference not found: 'EntityFrameworkServiceCollectionExtensions.AddDbContextPool'.
**Microsoft.EntityFrameworkCore/RelationalDatabaseFacadeExtensions**
 Cross reference not found: 'UseTransaction'.
 Cross reference not found: 'UseTransaction'.
 Cross reference not found: 'UseTransaction'.
 Cross reference not found: 'UseTransaction'.
 Cross reference not found: 'UseTransaction'.
 Cross reference not found: 'UseTransaction'.
 Cross reference not found: 'UseTransaction'.
**Microsoft.EntityFrameworkCore/RelationalEntityTypeExtensions**
 Cross reference not found: 'RelationalEntityTypeBuilderExtensions.ToSqlQuery'.
**Microsoft.EntityFrameworkCore/SaveChangesEventArgs**
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
**Microsoft.EntityFrameworkCore/SaveChangesFailedEventArgs**
 Cross reference not found: 'DbContext.SaveChanges'.
 Cross reference not found: 'DbContext.SaveChangesAsync'.
**Microsoft.EntityFrameworkCore/SavingChangesEventArgs**
 Cross reference not found: 'DbContext.SavingChanges'.

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #23260

### CODE REVIEW

**Comment by smitpatel** [comment]
@Pilchie - XML doc only change.

**Comment by Pilchie** [comment]
👍🏻

**Review by AndriySvyryd — APPROVED** [review]

**Comment by roji** [comment]
@smitpatel is there some document somewhere explaining the prefixes (`O` vs. `M`)? I remember we discussed this at some point but am not sure I know what to use when...

**Comment by ajcvickers** [comment]
Thanks for doing this, @smitpatel. Great to get XML docs updated before they are published for 6.0.

**Comment by smitpatel** [comment]
@roji https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/#id-strings
here is list of all IDs. "O:" is missing. I have filed a doc issue to update docs.

**Pull request merged**
