### PR TITLE
Return ValueTask in loggers and interceptors

### LINKED ISSUE #21109: Switch to returning ValueTask in loggers and interceptors
Many of our loggers currently return generic Tasks in order to support interception, incurring lots of needless heap allocations. For example, [RelationalCommand.ExecuteReaderAsync](https://github.com/dotnet/efcore/blob/a1931d9e0f7f327a0431b494b1af29f8299a1dfe/src/EFCore.Relational/Storage/RelationalCommand.cs#L469) calls [CommandReaderExecutingAsync](https://github.com/dotnet/efcore/blob/016256850c227897b2c2b4a3125210483d0318f8/src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs#L410) and [CommandReaderExecutedAsync](https://github.com/dotnet/efcore/blob/016256850c227897b2c2b4a3125210483d0318f8/src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs#L803), both of which actually return synchronously in almost all cases but allocate Task instances.

In addition, our interceptor API surface also returns generic Tasks from all methods. This means that the moment an interceptor is set up, the user starts paying additional allocations for all of its methods, regardless of whether those are intercepted or if they complete synchronously.

As this is a (minor) breaking change in a relatively new API, it may be good to do this early.

### PR DESCRIPTION
**Pull request by roji**
Closes #21109

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
Should target release/5.0-preview6

**Comment by roji** [comment]
Don't we merge to master first and then cherry-pick? Or should I send an additional PR for release/5.0-preview6?

**Comment by AndriySvyryd** [comment]
I thought it was release/5.0-preview6 first and then merge to master.
@dotnet/efcore

**Comment by AndriySvyryd** [comment]
Doing it either way should be fine though

**Comment by smitpatel** [comment]
Apart from patch which requires additional approval, we merge into earlier release first then cascade the changes to later releases. For patch we started doing other way around because if the fix in master is already risky, we may not actually patch it.

**Comment by roji** [comment]
Thanks @AndriySvyryd @smitpatel, for this one will merge the PR to master first since it's already submitted and there's little difference.

A small nit - I think submitting to master first is slightly better.. when submitting the PR against release/5.0.0-*** we can cherry-pick the commit from master, and include a reference to that commit (git cherry-pick -x) for reference. If we do it the other way around, master's git history is polluted with references to release branches, which seems less ideal..

**Comment by roji** [comment]
Also, when there are conflicts (as there are in this case), it seems better to first do the work against the latest master as we're used to, and then resolve conflicts against older versions rather than the other way around...

**Comment by smitpatel** [comment]
>  If we do it the other way around, master's git history is polluted with references to release branches, which seems less ideal..

We always merge release to master anyway so what is the pollution.

**Comment by roji** [comment]
Did not realize that, guess I'm used to a different flow - I'm used to work always happening in master, and getting cherry-picked to release or patch branches as appropriate. Release/patch commits always reference the master commits they were cherry-picked from (`git cherry-pick -x`), see [the current Npgsql patch branch](https://github.com/npgsql/efcore.pg/commits/hotfix/3.1.4) for an example

Indeed if we always merge release branches back to master it doesn't matter.

**Pull request merged**
