### PR TITLE
New database seeder approach for EFCore.

### PR DESCRIPTION
**Pull request by AshkanAbd**
New database seeder approach for EFCore.
Seeder placed in `EFCore\Seeder` directory
Please check [readme](https://github.com/AshkanAbd/efcore/blob/master/README.md) and [sample project](https://github.com/AshkanAbd/efCoreSeederSample) for more details.
DatabaseSeederExtension.cs:
- The extension for IServiceCollection to setup and process seeders.
SeederAttribute.cs:
- The Attribute that determine seeder methods in project. Add this attribute to the method that you want to act as a seeder.
IDatabaseSeeder.cs:
- The interface which runs seeder methods and seeds database.
- Use EnsureSeeded method for seeding database. Note that seeders should not run in a dotnet-ef process.
- Use SetEnvironment to run only production seeds or both development and production seeds.
DatabaseSeeder.cs:
- The class that implements IDatabaseSeeder.
SeederInfo.cs:
- The class that holds informations about seeder during seeding database.

### CODE REVIEW

**Comment by roji** [comment]
Could be related to #14922

**Comment by AndriySvyryd** [comment]
@AshkanAbd It seems that this PR was opened by error on the official EF Core repo.

If this isn't the case then open an issue with a detailed design and wait for approval before submitting another PR.

**Comment by AshkanAbd** [comment]
As @roji said this PR related to #14922 and ef core seed design.
@AndriySvyryd take a look at [this comment](https://github.com/dotnet/efcore/issues/14922#issuecomment-474277573), it's really painful. Seeds are placed in migrations and you have to create migration for your seeds and seeds will be a part of your migrations. also current  seed design won't increase the primary key and indexes of tables. And there is no difference between development seeds and production seeds.
Related issue was created before and I put details for suggested design in [readme.md](https://github.com/AshkanAbd/efcore/blob/master/README.md).
Do I need to create an issue for this new design?

**Comment by roji** [comment]
@AshkanAbd yes - for anything non-trivial, users need to submit a design proposal so that things can be discussed and agreed-upon, preferably before coding starts. [See our contribution guide](https://github.com/dotnet/efcore/blob/main/.github/CONTRIBUTING.md#workflow).

**Comment by roji** [comment]
The readme.md is the general description of what EF Core is, and is shown on [the Github repo page for EF Core](https://github.com/dotnet/efcore). That's definitely not the right place for a design proposal etc.

**Comment by AshkanAbd** [comment]
Sorry I forget to create a new branch for it. I will create an issue for it.

**Pull request closed without merging**
