### PR TITLE
Use conventions and model snapshot in the migration tests

### LINKED ISSUE #11193: Migrations: Test using snapshot
The test suite with most scenarios for migrations - `MigrationsModelDifferTest` currently doesn't use the product pipeline to run the tests. It creates two models and then diffs them. Whereas the product generates a snapshot of the first model, compiles it, loads it and then diffs it with the second model.

The model snapshot could be significantly different from the model (e.g. it uses different CLR types for properties that have a value conversion). And we are missing cases where the generated code doesn't compile at all.

However doing this for every test case might be too slow.

### LINKED ISSUE #20157: Build models with conventions in MigrationsTestBase

### PR DESCRIPTION
**Pull request by roji**
Closes #11193
Closes #20157

### CODE REVIEW

**Comment by maumar** [comment]
will simplify after the PR is checked in. Will have to add a bunch more tests to cover #26676

**Comment by AndriySvyryd** [comment]
This doesn't fix #11193 completely as it doesn't change tests in `MigrationsModelDifferTest`

**Review by AndriySvyryd — APPROVED** [review]

**Comment by roji** [comment]
@maumar this is now merged - you can add your stuff to it.

**Pull request merged**
