### PR TITLE
add support for System.Text.Json not including LazyLoader

### PR DESCRIPTION
**Pull request by EfimenkoAndrew**
- [ + ] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [ + ] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [ + ] The code builds and tests pass locally (also verified by our automated build checks)
- [ + ] Commit messages follow this format:
```
        Summary of the changes
        - Detail 1
        - Detail 2

        Fixes #bugnumber
```
- [ - ] Tests for the changes have been added (for bug fixes / features) I do not know how to test attribute, i am sorry, i am stupid
- [ + ] Code follows the same patterns and style as existing code in this repo

Related issue https://github.com/dotnet/efcore/issues/28083

### CODE REVIEW

**Comment by EfimenkoAndrew** [comment]
Hi
if it ever gonna be reviewed and merged please add the fix to the .net 6 version of library

**Review by ajcvickers — APPROVED** [review]

**Comment by ajcvickers** [comment]
@EfimenkoAndrew Thanks for the contribution.

> please add the fix to the .net 6 version of library

It's unlikely that we will patch EF Core 6.0 for this. See [the release planning process](https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning) for information on how we decide what to patch.

**Comment by Grauenwolf** [comment]
Would it have been better to convince the `System.Text.Json` team to just honor `IgnoreDataMember`?

**Comment by roji** [comment]
The decision in https://github.com/dotnet/runtime/issues/29975 seems pretty clear/final, and in any case, just adding a [JsonIgnore] doesn't really have any drawbacks...

**Comment by Grauenwolf** [comment]
Did EF Core already have a dependency on System.Text.Json.Serialization? I ask because that sounds like an odd dependency for an ORM.

**Comment by ajcvickers** [comment]
@Grauenwolf It's in the BCL.

**Pull request merged**
