### PR TITLE
Add ValueGenerated.OnUpdateSometimes for shared columns

### LINKED ISSUE #21139: Exception when saving value to a shared column
This scenario was broken by https://github.com/dotnet/efcore/pull/21128

See test in https://github.com/dotnet/efcore/commit/347e9cf5017c90a888f8aec5609ba7c92d1cfc4e

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #21139

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
@dotnet/efteam New API:
- `ValueGenerated.OnUpdateSometimes`
- `PropertyBuilder.ValueGeneratedOnUpdateSometimes()`

**Comment by smitpatel** [comment]
> ValueGenerated.OnUpdateSometimes

😄

**Comment by ajcvickers** [comment]
@Pilchie for RC1

**Comment by ErikEJ** [comment]
Could someone add a few words about the SomeTimes part? That may give some ideas for the new name.

**Comment by AndriySvyryd** [comment]
@ErikEJ In this particular case it indicates that the value will be "generated" by the database when a property that is sharing the column is updated. But since `ValueGenerated` is in Core the name shouldn't reference any relational concepts. It also might be used to describe other situations.

**Comment by Pilchie** [comment]
Approved for RC1.

**Comment by AndriySvyryd** [comment]
If a better name comes up we'll rename in a separate PR.

**Pull request merged**
