### PR TITLE
Add AddOrUpdate (Upsert) support

### PR DESCRIPTION
**Pull request by dan-giddins**
Adds support for upserting based on the existing architecture for adding and updating.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24956) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24956) before we can accept your contribution.<br/><br/>:x: dan-giddins [sign now](https://cla.dotnetfoundation.org/dotnet/efcore?pullRequest=24956)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/efcore?pullRequest=24956) it.</sub>

**Comment by dan-giddins** [comment]
This fixes #4526

**Comment by dan-giddins** [comment]
I'm trying to test the code in a test project, but I'm having difficulty getting the correct preview packages installed, as I think some of them haven't even been released yet. Could who already has main working in a test project please test this for me?

**Comment by Timovzl** [comment]
@dan-giddins Out of curiosity, how and when does this determine whether the entity exists? I don't see it doing anything async like performing a query, but I may have overlooked it.

Also, does it base existence on the primary key or on something else?

**Comment by dan-giddins** [comment]
@Timovzl in `GetOrCreateEntryReturnAlreadyExists()` (formally `GetOrCreateEntry()`) in `statemanager.cs`, `TryGetEntry()` is called. If this returns `null` I assume that the entity does not already exist as the reference maps are updated with a new object.

**Comment by Timovzl** [comment]
I wonder if that's right. Anything that goes to the database should be async, and `TryGetEntry()` is not. Are you sure that doesn't that merely check something in-memory? (Or have async overloads been overlooked here?)

**Comment by dan-giddins** [comment]
@Timovzl you might be correct. I haven't been able to test this as main currently relies on packages that have not yet been released. I would have to load most of the dependencies up via the source code, which I could do, but will take quite a while to actually set up. I wanted some feedback before then, just to make sure I'm working in the right direction, and to see if someone else already has a working setup with everything loaded.

**Comment by ajcvickers** [comment]
@dan-giddins This is not something we plan to merge. It doesn't address #4526, which is about generated database insert/updates   at the SQL-level that will do the correct thing.

**Pull request closed without merging**
