### PR TITLE
Remove nullability errors

### LINKED ISSUE #26995: Static analysis indicates issues with either NRT annotations or usage
XML file of inspections attached.

Specific issues to consider:
* AssignNullToNotNullAttribute
* ConstantConditionalAccessQualifier
* ConstantNullCoalescingCondition
* ExpressionIsAlwaysNull
* NotNullMemberIsNotInitialized
* PossibleNullReferenceException
* RedundantNullableFlowAttribute
* RedundantSuppressNullableWarningExpression
* UseNullableAnnotationInsteadOfAttribute

[EFCoreInspection.zip](https://github.com/dotnet/efcore/files/7711139/EFCoreInspection.zip)

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #26995

### CODE REVIEW

**Review by roji — APPROVED** [review]
LGTM (but see test failures).

Just to note that this could cause runtime failures.. When originally annotating, in cases of uncertainty I sometimes left runtime checks (i.e. coalescing operator) for members annotated as non-nullable - just in case. This removes these, which may cause NREs if the annotations are wrong. But it's a good time to do this in the beginning of the 7.0 cycle.

**Comment by smitpatel** [comment]
Errors don't seem to be related to nullable changes. Helix connects to external SqlServer causing all those tests to fail. The single test failure in windows look random as it passed for async but not for sync.

**Comment by ajcvickers** [comment]
@smitpatel Build was broken: https://github.com/dotnet/efcore/pull/27182

**Pull request merged**
