### PR TITLE
Switch from Apache to MIT license

### LINKED ISSUE #19844: Adopt MIT license
https://github.com/dotnet/aspnetcore/issues/18873

### PR DESCRIPTION
**Pull request by Pilchie**
Fixes #19844.

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @richlander @ChrisSfanos @sharwell.

I suggest reviewing commit-by-commit, but skipping the second one.  I'll squash at the time when I merge, but no one wants to look at 3700 file headers ;)

**Comment by ajcvickers** [comment]
@Pilchie I'm hesitant to sign-off on StyleCop changes without @bricelam taking a look. We have historically done the license through the R# settings, which get applied when we run code cleanup.

**Comment by bricelam** [comment]
LGTM

**Review by ajcvickers — APPROVED** [review]
:sheep: :it:

**Pull request merged**
