### PR TITLE
Don't ask how! :cry:

### LINKED ISSUE #21700: Perf regression in query compilation
image

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #21700

### CODE REVIEW

**Comment by smitpatel** [comment]
@msftbot require 1 approval

**Comment by AndriySvyryd** [comment]
Wouldn't this allow a hash collision?

**Comment by smitpatel** [comment]
> Wouldn't this allow a hash collision?

Yes, it will. 
- This code was added in #21668 so queries did work without it just fine previously. So there is at least no customer issue.
- Projections are comprised of ColumnExpressions or combination of them. SelectExpression.Tables will visit those to add hash code in case those differs. 
- Just anecdotal very rarely we have 2 select expressions which only differs in client or expanded projection but in no other component. 

The way I see it is hash collision in rare case vs slow compilation in all cases. Also a hash collision will go through equals so that no 2 different entities are matched. Equals part is still in place to avoid any issue in collision case.

**Comment by smitpatel** [comment]
I also tried out another approach though it ran into issue so definitely not a cheap fix. I wrote detailed comment about that in https://github.com/dotnet/efcore/issues/18923#issuecomment-661532920
Hopefully we can improve this in future release. (also reason for adding TODO)

**Comment by roji** [comment]
Looks very related to #19859 - I'm really not sure why we're recursing through the entire tree when calculating hash codes (as opposed to equality comparisons)... Hash collisions are completely normal, and as long as we achieve reasonable spread of keys everything should be fine (and fast)...

A great example is [ColumnExpression](https://github.com/dotnet/efcore/blob/master/src/EFCore.Relational/Query/SqlExpressions/ColumnExpression.cs#L116), where we recurse into the Table (which can be an arbitrarily deep subquery). I think it should be perfectly fine to only include the column name.

**Pull request merged**
