### PR TITLE
Fix for 17509. Do not allow migration to have same name as context.

### PR DESCRIPTION
**Pull request by lajones**
See #20126 
@bricelam  - this is the same code - but had problems with merge conflicts and old branch got corrupted, so created new branch to check this in.

### CODE REVIEW

**Comment by ajcvickers** [comment]
@lajones Was there discussion around this:

> How complicated would it be to scaffold [DbContext(typeof(The.Full.Namespace.Of.TheDbContext))] as needed instead?

**Comment by bricelam** [comment]
@ajcvickers Yes, it started getting complicated since the model snapshot needs to know if *any* migration is named the same as the DbContext.

**Comment by ajcvickers** [comment]
@bricelam Makes sense. Will throwing here break if people have edited their migrations to use a qualified name? In other words, does this change increase visibility but reduce the space of allowable workarounds? (The value here seems very low, so just trying to make sure we're not making anything worse.)

**Comment by bricelam** [comment]
They could edit the code, but unless they've customized the code generation, they have to edit the model snapshot code every migration.

I'm also fine just closing the issue as wont-fix

**Comment by ajcvickers** [comment]
@bricelam I think it's okay to merge.

**Pull request merged**
