### PR TITLE
[preview8] Avoid StackOverflowException in IndexBuilder.HasName()

### LINKED ISSUE #21734: HasName() throws System.StackOverflowException
HasName() is marked "obsolete", but should not result in

System.StackOverflowException
  HResult=0x800703E9
  Message=Exception of type 'System.StackOverflowException' was thrown.

### Steps to reproduce

protected override void OnModelCreating(ModelBuilder mb)
{
mb.Entity<Flight>().HasIndex(x => x.FreeSeats).HasName("Index_FreeSeats");
}

Not happening if I use HasDatabaseName()

### Further technical details

EF Core version: 5.0 Preview 7
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 5.0 Preview 6 und 7
Operating system: Windows 10
IDE: Visual Studio 2019 16.6

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #21734

### CODE REVIEW

**Comment by Saibamen** [comment]
Could you release patch version for preview 7?
7 was released 2 days ago, so we need to wait few weeks for preview 8 to be released...

**Comment by AndriySvyryd** [comment]
@Saibamen preview8 is the patch for preview7, we have no practical way of releasing something in-between

**Comment by bricelam** [comment]
@Saibamen Consider using the [daily builds](https://github.com/dotnet/aspnetcore/blob/master/docs/DailyBuilds.md) for a while.

**Comment by ajcvickers** [comment]
I have been informed we are not in ask-mode yet, so merging this now.

**Comment by Saibamen** [comment]
@ajcvickers: Ask mode for what?

**Comment by ajcvickers** [comment]
@Saibamen Ask-mode is Microsoft jargon for needing to ask for approval to get a change into a specific release. In this case we didn't need to wait for approval to get a change into preview 8.

**Pull request merged**
