### PR TITLE
Revert "Fix to #18147 - Where bool column needs to convert to equalit…

### PR DESCRIPTION
**Pull request by smitpatel**
…y when value converter is applied"

This reverts commit e922850b9fb52dd7cb9e5c04ba21dd79de02b9de.

### CODE REVIEW

**Comment by smitpatel** [comment]
Will merge on build pass. We can discuss later in #18147

**Comment by roji** [comment]
Note to @smitpatel @maumar: when syncing EFCore.PG against ac4633559b117b92156d75f07b7ef81dc920b4fd (latest nuget available), I get a test failure on Where_bool_gets_converted_to_equality_when_value_conversion_is_used_using_EFProperty, where PostgreSQL complains that WHERE must receive a boolean type, not character varying:

```sql
SELECT b."BlogId", b."Discriminator", b."IndexerVisible", b."IsVisible", b."Url", b."RssUrl"
        FROM "Blog" AS b
        WHERE b."IsVisible"
```

I see the change has been reverted anyway, I guess just keep in mind for when fixing again.

**Comment by roji** [comment]
Oops, was looking at the wrong commit. I'm actually synced against 87714065027c161e29d8b5901813a07682e93538, which already has this revert inside it - the test still fails. Do you guys want a new issue to track this?

**Comment by smitpatel** [comment]
#18147 has been re-opened. I left skipped tests behind in this PR. Tests are not skipped in specs since SqlServer can run them. Individual providers have skipped them.

You need some sleep @roji

**Comment by roji** [comment]
Thanks @smitpatel, good to know. And I definitely do need some sleep at some point.

**Pull request merged**
