### PR TITLE
Using Debug.Fail

### PR DESCRIPTION
**Pull request by SergerGood**

### CODE REVIEW

**Comment by roji** [comment]
This looks OK, but at least for EF Core we've made the decision to not use Debug.Assert (or Fail) since they crash the test process and can make it hard to understand what happened (we use Check.DebugAssert which throws an exception instead). Do we want to do the same in Microsoft.Data.Sqlite? @bricelam @ajcvickers

**Comment by ajcvickers** [comment]
I'll leave that up to @bricelam.

**Review by bricelam — APPROVED** [review]
:shipit:

These are left over from when we targeted .NET Standard 1.3

**Comment by bricelam** [comment]
I'm perfectly fine keeping Debug.Assert--I use a *good* test runner that doesn't crash 😉

**Pull request merged**
