### PR TITLE
Assumptions are correct till they are not

### LINKED ISSUE #12239: When using variable in a .Select() from parent .SelectMany() scope I get an InvalidOperationException
When using a call to `.Select()` from within a `.SelectMany()` call, if I reference the variable from the `.SelectMany()` scope I get an `InvalidOperationException`, I would expect this to work the same way it does in EF6, as the left side of a join.

```
Exception message: System.InvalidOperationException: variable 'product' of type 'EFCoreBugs.SelectManyBug.Product' referenced from scope '', but it is not defined
Stack trace:
System.InvalidOperationException: variable 'product' of type 'EFCoreBugs.SelectManyBug.Product' referenced from scope '', but it is not defined
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.Create(Shaper originalShaper, LambdaExpression materializer)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.LiftSubQuery(IQuerySource querySource, SubQueryExpression subQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.CompileAdditionalFromClauseExpression(AdditionalFromClause additionalFromClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitAdditionalFromClause(AdditionalFromClause fromClause, QueryModel queryModel, Int32 index)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitAdditionalFromClause(AdditionalFromClause fromClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at EFCoreBugs.SelectManyBug.Program.Main(String[] args) in C:\Users\Phil\Documents\Visual Studio 2017\Projects\EFCoreBugs\EFCoreBugs.SelectManyBug\Program.cs:line 32
```

### Steps to reproduce
Here's an example project that demonstrates the issue: [EFCoreBugs.SelectManyBug.zip](https://github.com/aspnet/EntityFrameworkCore/files/2070916/EFCoreBugs.SelectManyBug.zip)

Following is code that throws the excption:
```c#
var queryThrowsException = db.Product
    .SelectMany(product => product.ProductCategory
        .Select(pc => new
        {
            product
        }))
    .ToArray();
```
But I would expect it to work the same way as:

```c#
var queryWorksFine = (
    from product in db.Product
    from pc in product.ProductCategory
    select new { product })
    .ToArray();
```

### Further technical details
EF Core version: 2.1.0 (still exists in 2.2.0-preview1-34386)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Version 1709 (OS Build 16299.431)
IDE: Visual Studio 2017 15.7.3

### PR DESCRIPTION
**Pull request by smitpatel**
Query: Get mapped projection from associated query expression

Since projection binding can come from parent query expression too

Resolves #12239

### CODE REVIEW

**Comment by smitpatel** [comment]
@Pilchie for RC1 approval

**Comment by Pilchie** [comment]
Approved for RC1.

**Comment by alexandis** [comment]
Still getting this error in EfCore5. What am I doing wrong below?

> variable 'articleTexts' of type 'System.Collections.Generic.IEnumerable`1[AbxEps.Fines.LawArticles.LawArticleDetail]' referenced from scope '', but it is not defined

```
           var articlesQuery =
                dbSet.Select(x => new { x.TenantId, x.LawArticleId }).Distinct()
                .GroupJoin(
                    dbSet,
                    x => new { x.TenantId, x.LawArticleId },
                    x => new { x.TenantId, x.LawArticleId },
                    (articleId, articleTexts) => new
                    {
                        ArticleId = articleId,
                        ArticleTexts = articleTexts
                    }
                )
                .SelectMany(
                    x => x.ArticleTexts,
                    (all, articleDetail) => new { ArticleId = all.ArticleId, ArticleTexts = all.ArticleTexts }
                )
                .Select(x => new LawArticleAggregated
                {
                    TenantId = x.ArticleId.TenantId,
                    LawArticleId = x.ArticleId.LawArticleId,
                    ArticleTexts = x.ArticleTexts.ToList()
                });
```

**Comment by smitpatel** [comment]
@alexandis - Please file a new issue with a runnable code and exception+stack trace you are seeing.

**Pull request merged**
