### PR TITLE
Revert HasKey binary breaking change and add a test for IdentityServer4

### PR DESCRIPTION
**Pull request by AndriySvyryd**

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
cc @davidfowl

**Comment by ajcvickers** [comment]
@AndriySvyryd I we just not going to allow a generic key builder ever, or should we have a plan to try to do this in some other way, or in conjunction with Identity Server changes?

**Comment by lajones** [comment]
@AndriySvyryd Agree with @ajcvickers above. Could we add a comment saying why we are not doing this the normal way in the generic `EntityTypeBuilder` ?

**Comment by davidfowl** [comment]
Maybe add an extension method to hide the cast?

**Comment by AndriySvyryd** [comment]
> @AndriySvyryd I we just not going to allow a generic key builder ever, or should we have a plan to try to do this in some other way, or in conjunction with Identity Server changes?

We can try again when we have a more compelling reason to do this or when Identity Server is going to be broken by a different change. I don't think it's worth it to keep this on the backlog.

> @AndriySvyryd Agree with @ajcvickers above. Could we add a comment saying why we are not doing this the normal way in the generic EntityTypeBuilder ?

It would be basically the comment that's applicable to any public API: "Don't change this, it breaks stuff". The test I added is more reliable.

> Maybe add an extension method to hide the cast?

We'll consider this in the future. For now the users don't *need* to have the generic type.

**Comment by AndriySvyryd** [comment]
@dougbu EF can be unpinned now

**Pull request merged**
