### PR TITLE
Use matching type mapping when translating `BoolSwitch`

### LINKED ISSUE #34900: EFCore 9 rc1 - sql server - Problem with type mapping during linq to sqlexpression translation
When running the  CaseOpWhen_predicate() test in efcore\9.0\test\EFCore.SqlServer.FunctionalTests\Query\NullSemanticsQuerySqlServerTest.cs.  The sql that should be generated is

```sql

SELECT [e].[Id], [e].[BoolA], [e].[BoolB], [e].[BoolC], [e].[IntA], [e].[IntB], [e].[IntC], [e].[NullableBoolA], [e].[NullableBoolB], [e].[NullableBoolC], [e].[NullableIntA], [e].[NullableIntB], [e].[NullableIntC], [e].[NullableStringA], [e].[NullableStringB], [e].[NullableStringC], [e].[StringA], [e].[StringB], [e].[StringC]
FROM [Entities1] AS [e]
WHERE CASE CASE
    WHEN [e].[StringA] = N'Foo' THEN CAST(1 AS bit)
    ELSE CAST(0 AS bit)
END
    WHEN 1 THEN 3
    WHEN 0 THEN 2
END = 2
```

The 1 and 0 in the two when clauses (  WHEN 1 THEN 3 and   WHEN 0 THEN 2 ) in the case expression are supposed to represent boolean true and false.  While debugging we noticed that the type mapping of the sqlConstantExpression ("0" and "1") in the when clause is Microsoft.entityFrameworkCore.Storage.BoolTypeMapping. It is not the provider specific type mapping.

In such case, a providers will not be able to generate provider specific boolean values( such as true and false instead of 0 and 1).
For example, on running the above test using sqlServer-

Image

If you expand the computed value of visitedExpression and look at left -> whenClause -> test -> typeMapping , you shall find it is Microsoft.entityFrameworkCore.Storage.BoolTypeMapping

Is this the expected behavior or should the typeMapping be provider specific?

EF Core version: 9.0.0-rc.1.24451.1
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 8.0)
Operating system: windows
IDE: (e.g. Visual Studio 2022 17.4)

### PR DESCRIPTION
**Pull request by ranma42**
Fixes #34900.

### CODE REVIEW

**Comment by ChrisJollyAU** [comment]
You'll need to fix CaseOpWhen_projection as well for the SQL output. There's 2 tests that use that `BoolSwitch`

**Comment by ranma42** [comment]
Oops! That's what I get for not running the fill test suite before pushing 💩 (the CI would have caught it ;) ).
Thank you @ChrisJollyAU !

**Comment by ranma42** [comment]
Locally the test suite passes (on Linux, Sqlite+SqlServer)

**Review by roji — APPROVED** [review]
Thanks for fixing @ranma42!

**Pull request merged**
